METplus: command_builder.CommandBuilder Class Reference
command_builder.CommandBuilder Class Reference
Common functionality to wrap all MET applications.
Detailed Description
Common functionality to wrap all MET applications.
Definition at line 34 of file command_builder.py.
Public Member Functions
def __init__ (self, config, logger)
def create_c_dict (self)
def clear (self)
Unset class variables to prepare for next run time.
def log_error (self, error_string)
def set_user_environment (self, time_info=None)
Set environment variables defined in [user_env_vars] section of config.
def add_common_envs (self, time_info=None)
def print_all_envs (self)
def handle_window_once (self, c_dict, dtype, edge, app_name)
Check and set window dictionary variables like OBS_WINDOW_BEG or FCST_FILE_WINDW_END Args:
def handle_window_variables (self, c_dict, app_name, dtypes=['FCST', OBS)
Handle all window config variables like [FCST/OBS]_<app_name>_WINDOW_[BEGIN/END] and [FCST/OBS]_<app_name>_FILE_WINDOW_[BEGIN/END] Args:
def set_output_path (self, outpath)
Split path into directory and filename then save both.
def get_output_path (self)
Combine output directory and filename then return result.
def add_env_var (self, key, name)
Sets an environment variable so that the MET application can reference it in the parameter file or the application itself.
def print_env (self)
Print all environment variables set for this application.
def print_env_copy (self, var_list=None)
def get_env_copy (self, var_list=None)
Print list of environment variables that can be easily copied into terminal.
def print_env_item (self, item)
Print single environment variable in the log file.
def print_user_env_items (self)
Prints user environment variables in the log file.
def handle_fcst_and_obs_field (self, gen_name, fcst_name, obs_name, default=None, sec='config')
Handles config variables that have fcst/obs versions or a generic variable to handle both, i.e.
def find_model (self, time_info, var_info, mandatory=True, return_list=False)
Finds the model file to compare Args:
def find_obs (self, time_info, var_info, mandatory=True, return_list=False)
Finds the observation file to compare Args:
def find_data (self, time_info, var_info, data_type, mandatory=True, return_list=False)
Finds the data file to compare Args:
def find_exact_file (self, level, data_type, time_info, mandatory=True, return_list=False)
def find_file_in_window (self, level, data_type, time_info, mandatory=True, return_list=False)
def write_list_file (self, filename, file_list)
Writes a file containing a list of filenames to the staging dir.
def find_and_check_output_file (self, time_info)
Look for expected output file.
def format_list_string (self, list_string)
Add quotation marks around each comma separated item in the string.
def check_for_externals (self)
def check_for_gempak (self)
def check_gempaktocf (self, gempaktocf_jar)
def get_output_prefix (self, time_info)
def check_for_python_embedding (self, input_type, var_info)
Check if field name of given input type is a python script.
def get_command (self)
Builds the command to run the MET application string.
def build_and_run_command (self)
def build (self)
Build and run command.
def run_at_time (self, input_dict)
Used to output error and exit if wrapper is attemped to be run with LOOP_ORDER = times and the run_at_time method is not implemented.
def run_all_times (self)
Loop over time range specified in conf file and call METplus wrapper for each time.
Public Attributes
isOK
errors
logger
config
env_list
debug
args
input_dir
infiles
outdir
outfile
param
env
c_dict
cmdrunner
Member Function Documentation
check_for_python_embedding()
def command_builder.CommandBuilder.check_for_python_embedding (self, input_type, var_info)
Check if field name of given input type is a python script.
If it is not, return the field name. If it is, check if the input datatype is a valid Python Embedding string, set the c_dict item that sets the file_type in the MET config file accordingly, and set the output string to 'python_embedding. Used to set up Python Embedding input for MET tools that support multiple input files, such as MTD, EnsembleStat, and SeriesAnalysis. Args:
Parameters
input_type type of field input, i.e. FCST, OBS, ENS, POINT_OBS, GRID_OBS, or BOTH
var_info dictionary item containing field information for the current *_VAR<n>_* configs being handled
Returns
field name if not a python script, 'python_embedding' if it is, and None if configuration is invalid
Definition at line 634 of file command_builder.py.
Referenced by ensemble_stat_wrapper.EnsembleStatWrapper.get_all_field_info(), series_analysis_wrapper.SeriesAnalysisWrapper.run_at_time(), and mtd_wrapper.MTDWrapper.run_at_time_loop_string().
find_and_check_output_file()
def command_builder.CommandBuilder.find_and_check_output_file (self, time_info)
Look for expected output file.
If it exists and configured to skip if it does, then return False
Definition at line 551 of file command_builder.py.
Referenced by series_analysis_wrapper.SeriesAnalysisWrapper.run_at_time(), ascii2nc_wrapper.ASCII2NCWrapper.run_at_time_once(), and pb2nc_wrapper.PB2NCWrapper.run_at_time_once().
find_data()
def command_builder.CommandBuilder.find_data (self, time_info, var_info, data_type, mandatory = True, return_list = False)
Finds the data file to compare Args:
Parameters
time_info dictionary containing timing information
var_info object containing variable information
data_type type of data to find (FCST or OBS)
mandatory if True, report error if not found, warning if not default is True string
Returns
Returns the path to an observation file
Definition at line 335 of file command_builder.py.
Referenced by command_builder.CommandBuilder.find_model(), command_builder.CommandBuilder.find_obs(), series_analysis_wrapper.SeriesAnalysisWrapper.run_at_time(), and ensemble_stat_wrapper.EnsembleStatWrapper.run_at_time_all_fields().
find_model()
def command_builder.CommandBuilder.find_model (self, time_info, var_info, mandatory = True, return_list = False)
Finds the model file to compare Args:
Parameters
time_info dictionary containing timing information
var_info object containing variable information
mandatory if True, report error if not found, warning if not default is True string
Returns
Returns the path to an model file
Definition at line 307 of file command_builder.py.
Referenced by compare_gridded_wrapper.CompareGriddedWrapper.run_at_time_all_fields(), mtd_wrapper.MTDWrapper.run_at_time_loop_string(), mode_wrapper.MODEWrapper.run_at_time_one_field(), and compare_gridded_wrapper.CompareGriddedWrapper.run_at_time_one_field().
find_obs()
def command_builder.CommandBuilder.find_obs (self, time_info, var_info, mandatory = True, return_list = False)
Finds the observation file to compare Args:
Parameters
time_info dictionary containing timing information
var_info object containing variable information
mandatory if True, report error if not found, warning if not default is True string
Returns
Returns the path to an observation file
Definition at line 321 of file command_builder.py.
Referenced by pb2nc_wrapper.PB2NCWrapper.find_input_files(), compare_gridded_wrapper.CompareGriddedWrapper.run_at_time_all_fields(), mtd_wrapper.MTDWrapper.run_at_time_loop_string(), ascii2nc_wrapper.ASCII2NCWrapper.run_at_time_once(), mode_wrapper.MODEWrapper.run_at_time_one_field(), and compare_gridded_wrapper.CompareGriddedWrapper.run_at_time_one_field().
get_command()
def command_builder.CommandBuilder.get_command (self)
Builds the command to run the MET application string.
Returns
Returns a MET command with arguments that you can run
Definition at line 666 of file command_builder.py.
Referenced by tcmpr_plotter_wrapper.TCMPRPlotterWrapper.build(), command_builder.CommandBuilder.build(), make_plots_wrapper.MakePlotsWrapper.create_plots_grid2grid_anom(), make_plots_wrapper.MakePlotsWrapper.create_plots_grid2grid_pres(), make_plots_wrapper.MakePlotsWrapper.create_plots_grid2grid_sfc(), make_plots_wrapper.MakePlotsWrapper.create_plots_grid2obs_conus_sfc(), make_plots_wrapper.MakePlotsWrapper.create_plots_grid2obs_upper_air(), make_plots_wrapper.MakePlotsWrapper.create_plots_precip(), make_plots_wrapper.MakePlotsWrapper.create_plots_user(), stat_analysis_wrapper.StatAnalysisWrapper.filter_for_plotting(), command_builder.CommandBuilder.get_command(), tc_pairs_wrapper.TCPairsWrapper.process_data(), ensemble_stat_wrapper.EnsembleStatWrapper.process_fields(), compare_gridded_wrapper.CompareGriddedWrapper.process_fields(), mode_wrapper.MODEWrapper.process_fields_one_thresh(), mtd_wrapper.MTDWrapper.process_fields_one_thresh(), tc_pairs_wrapper.TCPairsWrapper.run_all_times(), series_analysis_wrapper.SeriesAnalysisWrapper.run_at_time(), gempak_to_cf_wrapper.GempakToCFWrapper.run_at_time_once(), pb2nc_wrapper.PB2NCWrapper.run_at_time_once(), stat_analysis_wrapper.StatAnalysisWrapper.run_stat_analysis_job(), pcp_combine_wrapper.PCPCombineWrapper.setup_add_method(), pcp_combine_wrapper.PCPCombineWrapper.setup_derive_method(), pcp_combine_wrapper.PCPCombineWrapper.setup_subtract_method(), and pcp_combine_wrapper.PCPCombineWrapper.setup_sum_method().
handle_fcst_and_obs_field()
def command_builder.CommandBuilder.handle_fcst_and_obs_field (self, gen_name, fcst_name, obs_name, default = None, sec = 'config')
Handles config variables that have fcst/obs versions or a generic variable to handle both, i.e.
FCST_NAME, OBS_NAME, and NAME. If FCST_NAME and OBS_NAME both exist, they are used. If both are don't exist, NAME is used.
Definition at line 262 of file command_builder.py.
Referenced by mode_wrapper.MODEWrapper.add_merge_config_file().
handle_window_once()
def command_builder.CommandBuilder.handle_window_once (self, c_dict, dtype, edge, app_name)
Check and set window dictionary variables like OBS_WINDOW_BEG or FCST_FILE_WINDW_END Args:
Parameters
c_dict dictionary to set items in
dtype type of data 'FCST' or 'OBS'
edge either 'BEGIN' or 'END'
Definition at line 147 of file command_builder.py.
Referenced by command_builder.CommandBuilder.handle_window_variables().
handle_window_variables()
def command_builder.CommandBuilder.handle_window_variables (self, c_dict, app_name, dtypes = ['FCST', OBS)
Handle all window config variables like [FCST/OBS]_<app_name>_WINDOW_[BEGIN/END] and [FCST/OBS]_<app_name>_FILE_WINDOW_[BEGIN/END] Args:
Parameters
c_dict dictionary to set items in
Definition at line 188 of file command_builder.py.
Referenced by mode_wrapper.MODEWrapper.add_merge_config_file(), point_stat_wrapper.PointStatWrapper.create_c_dict(), and ensemble_stat_wrapper.EnsembleStatWrapper.create_c_dict().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/command_builder.py