METplus: produtil.datastore.Task Class Reference
produtil.datastore.Task Class Reference
Represents a process or actor that makes a Product.
Detailed Description
Represents a process or actor that makes a Product.
A Task represents some work that needs to be done to produce Products. A task has a state (stored in the "available" metadata attribute), a location, whose meaning is up to the implementer to decide, and a logger.Logger. As with all Datum subclasses, a Task also has arbitrary metadata.
Definition at line 1080 of file datastore.py.
Public Member Functions
def __init__ (self, dstore, taskname, logger=None, kwargs)
Task constructor.
def jlogfile (self)
returns the jlogfile logger.
def postmsg (self, message, args, kwargs)
same as produtil.log.jlogger.info()
def setstate (self, val)
Sets the state of this job.
def getstate (self)
Returns the job state.
def strstate (self)
A string representation of the job state.
def gettaskname (self)
Returns the task name part of the database ID, which is the same as the prodname.
def products (self, args, kwargs)
Iterate over the products this task produces.
def log (self)
Returns the logger object for this task.
def clean (self)
Cleans up any unneeded data used by this task.
def unrun (self)
Undoes the effect of run().
def run (self)
Performs the work this Task should do and generates all products.
def is_completed (self)
Is this task complete?
def completed (self)
Read-only property: is this task completed? Same as is_completed()
def runpart (self)
Run some of this task's work, deliver some products.
Public Member Functions inherited from produtil.datastore.Datum
def __init__ (self, dstore, prodname, category, meta=None, cache=30, location=None, kwargs)
Datum constructor.
def __enter__ (self)
Acquires this object's thread lock.
def __exit__ (self, etype, evalue, traceback)
Releases this object's thread lock.
def validate (self)
Validates this object's Datastore, prodname and category.
def getid (self)
Returns the database ID of this datum.
def getdatastore (self)
Returns the datastore of this datum.
def transaction (self)
Creates, but does not lock, a Transaction for this datum's datastore.
def getprodtype (self)
Returns the product type of this Datum.
def getprodname (self)
Returns the product name part of the database ID.
def getcategory (self)
Returns the product category part of the database ID.
def getlocation (self)
Returns the "location" field of this Datum's database entry.
def setlocation (self, v)
Sets the "location" field of this Datum's database entry.
def __hash__ (self)
Integer hash function.
def __str__ (self)
Human-readable description of this Datum.
def __repr__ (self)
Python code-like description of this Datum.
def __lt__ (self, other)
Compares two Datums' prodnames and categories.
def __gt__ (self, other)
Compares two Datums' prodnames and categories.
def __eq__ (self, other)
Compares two Datums' prodnames and categories.
def __ne__ (self, other)
Compares two Datums' prodnames and categories.
def __ge__ (self, other)
Compares two Datums' prodnames and categories.
def __le__ (self, other)
Compares two Datums' prodnames and categories.
def set_loc_avail (self, loc, avail)
Sets the location and availability of this Datum in a single transaction.
def update (self)
Discards all cached metadata and refreshes it from the Datastore.
def __getitem__ (self, k)
Returns the value of the specified metadata key or raises KeyError.
def meta (self, k, default=None)
Return the value of a metadata key.
def get (self, k, default=None)
Alias for self.meta() Returns the value of the specified metadata key or returns default if it is unset.
def __setitem__ (self, k, v)
Sets the value of the specified metadata key.
def __delitem__ (self, k)
Deletes the specified metadata key, which must not be "available" or "location".
def __contains__ (self, k)
Determines if a metadata key is set.
def iteritems (self)
Alias for items() for backward compatibility.
def items (self)
Iterates over all metadata (key,value) pairs for this Datum, including "available" and "location".
Properties
state
Read-write property: the job state.
taskname
Read-only property: the name of this task.
Properties inherited from produtil.datastore.Datum
prodname = property(getprodname,None,None,)
Read-only property, an alias for getprodname(): the product name part of the database ID.
category = property(getcategory,None,None,)
Read-only property, an alias for getcategory(), the category name part of the database ID.
prodtype
Read-only property, an alias for getprodtype(), the product type.
did
Read-only property, an alias for getid().
dstore
Read-only property, an alias for getdatastore(), the Datastore in which this Datum resides.
location
Read-write property, an alias for getlocation() and setlocation().
Constructor & Destructor Documentation
__init__()
def produtil.datastore.Task.__init__ (self, dstore, taskname, logger = None, kwargs)
Task constructor.
Creates a new Task from the given dataset and with the given task name.
Parameters
dstore the Datastore where this Task will live
taskname the task name, passed to the Datum as prodname
logger a logging.Logger for this task to use for log messages
kwargs other keyword arguments are passed to Datum.__init__
Definition at line 1088 of file datastore.py.
Member Function Documentation
clean()
def produtil.datastore.Task.clean (self)
Cleans up any unneeded data used by this task.
Subclasses should override this function to clean up any unneeded temporary files or other unused resources consumed by the run() function. This default implementation does nothing.
Definition at line 1180 of file datastore.py.
completed()
def produtil.datastore.Task.completed (self)
Read-only property: is this task completed? Same as is_completed()
True if self.state==COMPLETED, False otherwise.
Definition at line 1217 of file datastore.py.
getstate()
def produtil.datastore.Task.getstate (self)
Returns the job state.
Returns the "available" attribute as an integer. This is used as the state of the Task. Typically, the return value should be one of: FAILED, UNSTARTED, RUNNING, PARTIAL, or COMPLETED.
Definition at line 1131 of file datastore.py.
gettaskname()
def produtil.datastore.Task.gettaskname (self)
Returns the task name part of the database ID, which is the same as the prodname.
Definition at line 1155 of file datastore.py.
is_completed()
def produtil.datastore.Task.is_completed (self)
Is this task complete?
Returns True if this task's state is COMPLETED, and False otherwise.
Definition at line 1208 of file datastore.py.
jlogfile()
def produtil.datastore.Task.jlogfile (self)
returns the jlogfile logger.
Returns a logging.Logger for the jlogfile. The jlogfile is intended to receive only major errors, and per-job start and completion information. This is equivalent to simply accessing produtil.log.jlogger.
Definition at line 1103 of file datastore.py.
log()
def produtil.datastore.Task.log (self)
Returns the logger object for this task.
Definition at line 1177 of file datastore.py.
postmsg()
def produtil.datastore.Task.postmsg (self, message, args, kwargs)
same as produtil.log.jlogger.info()
Sends a message to the multi-job shared log file at level INFO.
Parameters
message the message
args positional arguments for string replacement
kwargs keyword arguments for string replacement.
Definition at line 1112 of file datastore.py.
products()
def produtil.datastore.Task.products (self, args, kwargs)
Iterate over the products this task produces.
Iterates over some or all of the products produced by this task. The arguments are used to select subsets of the total set of products. Provide no arguments to get the full list of products. All subclasses should re-implement this method, and interpret the arguments in a way that makes sense to that class. The default implementation returns immediately without doing anything.
Parameters
args,kwargs Implementation-defined, used by subclasses.
Definition at line 1164 of file datastore.py.
run()
def produtil.datastore.Task.run (self)
Performs the work this Task should do and generates all products.
Performs the work that this task is supposed to do. All subclasses should re-implement this method, and should set the state to COMPLETED the end. This implementation simply calls self.setstate(COMPLETED)
Postcondition
self.state=COMPLETED
Definition at line 1199 of file datastore.py.
Referenced by produtil.testing.parsetree.EmbedBash.numeric_context(), and produtil.datastore.Task.runpart().
runpart()
def produtil.datastore.Task.runpart (self)
Run some of this task's work, deliver some products.
Performs a subset of the work that this task is supposed to do and returns. This is intended to be used for tasks that can be broken up into small pieces, such as post-processing all output files from a NWP simulation one by one. The default implementation simply calls self.run()
Definition at line 1221 of file datastore.py.
setstate()
def produtil.datastore.Task.setstate (self, val)
Sets the state of this job.
Sets the job stat to the specified value. This works by setting the "available" attribute to the specified integer. For compatibility with other scripts, this should be FAILED, UNSTARTED, RUNNING, PARTIAL or COMPLETED.
Parameters
val the new job state, an int
Definition at line 1122 of file datastore.py.
Referenced by produtil.datastore.Task.run().
strstate()
def produtil.datastore.Task.strstate (self)
A string representation of the job state.
Definition at line 1146 of file datastore.py.
unrun()
def produtil.datastore.Task.unrun (self)
Undoes the effect of run().
Cleans up this Task's work areas, "undelivers" all deliverables, and makes it look like the task has never been run. All subclasses should re-implement this method, and must also "unrun" everything their parent class runs. The default implementation simply calls self.clean() and sets the state to UNSTARTED.
Postcondition
self.state=UNSTARTED
Definition at line 1187 of file datastore.py.
Property Documentation
state
produtil.datastore.Task.state static
Initial value:
= property(getstate,setstate,None,
        )
Read-write property: the job state.
Can be FAILED, UNSTARTED, RUNNING, PARTIAL or COMPLETED.
Definition at line 1142 of file datastore.py.
Referenced by produtil.datastore.Task.completed(), and produtil.datastore.Task.is_completed().
taskname
produtil.datastore.Task.taskname static
Initial value:
= property(gettaskname,None,None,
        )
Read-only property: the name of this task.
Same as self.prodname.
Definition at line 1162 of file datastore.py.
Referenced by produtil.config.ProdTask.get_outdir(), produtil.config.ProdTask.get_workdir(), and produtil.config.ProdTask.log().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/produtil/datastore.py