METplus: produtil.prog.StreamReuser Class Reference
produtil.prog.StreamReuser Class Reference
Arranges for a stream-like object to be sent to the stdout, stderr or stdin of a Runner.
Detailed Description
Arranges for a stream-like object to be sent to the stdout, stderr or stdin of a Runner.
Definition at line 294 of file prog.py.
Public Member Functions
def __init__ (self, obj)
Creates a StreamReuser for the specified stream-like object.
def copy (self)
Returns a shallow copy of this object.
def to_shell (self)
Raises NotValidPosixSh to indicate that the stream cannot be represented as POSIX sh.
def repr_for_in (self)
Returns repr(obj) where obj is the given stream-like object.
def repr_for_out (self)
Returns repr(obj) where obj is the given stream-like object.
Public Member Functions inherited from produtil.prog.StreamGenerator
def for_input (self)
Has no effect.
def for_output (self)
Has no effect.
def repr_for_err (self)
Returns the stderr value.
Public Attributes
obj
the stream-like object to reuse.
Constructor & Destructor Documentation
__init__()
def produtil.prog.StreamReuser.__init__ (self, obj)
Creates a StreamReuser for the specified stream-like object.
Parameters
obj the stream-like object to reuse.
Definition at line 297 of file prog.py.
Member Function Documentation
copy()
def produtil.prog.StreamReuser.copy (self)
Returns a shallow copy of this object.
Note that means that the underlying stream object is not copied.
Definition at line 303 of file prog.py.
Referenced by produtil.prog.ImmutableRunner.runner(), and produtil.prog.Runner.to_shell().
repr_for_in()
def produtil.prog.StreamReuser.repr_for_in (self)
Returns repr(obj) where obj is the given stream-like object.
Definition at line 316 of file prog.py.
repr_for_out()
def produtil.prog.StreamReuser.repr_for_out (self)
Returns repr(obj) where obj is the given stream-like object.
Definition at line 320 of file prog.py.
Referenced by produtil.prog.StreamGenerator.repr_for_err().
to_shell()
def produtil.prog.StreamReuser.to_shell (self)
Raises NotValidPosixSh to indicate that the stream cannot be represented as POSIX sh.
Definition at line 307 of file prog.py.
Member Data Documentation
obj
produtil.prog.StreamReuser.obj
the stream-like object to reuse.
Definition at line 300 of file prog.py.
Referenced by produtil.prog.StreamReuser.copy(), produtil.prog.StreamReuser.repr_for_in(), produtil.prog.StreamReuser.repr_for_out(), and produtil.prog.StreamReuser.to_shell().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/produtil/prog.py