METplus: produtil.mpiprog.MPIRanksBase Class Reference
produtil.mpiprog.MPIRanksBase Class Reference
This is the abstract superclass of all classes that represent one or more MPI ranks, including MPI ranks that are actually serial programs.
Detailed Description
This is the abstract superclass of all classes that represent one or more MPI ranks, including MPI ranks that are actually serial programs.
Subclasses of MPIRanksBase allow an MPI program to be represented as a tree of MPIRanksBase objects, in such a way that they can be easily converted to a produtil.prog.Runner object for execution. The actual conversion to a Runner is done in the produtil.mpi_impl package (see produtil/mpi_impl/__init__.py)
Definition at line 89 of file mpiprog.py.
Public Member Functions
def to_arglist (self, to_shell=False, expand=False, shell_validate=None, pre=[], before=[], between=[], after=[], post=[], extra={}, include_localopts=False)
This is the underlying implementation of most of the mpi_impl modules, and hence make_runner as well.
def haslocalopts (self)
Returns True if setlocalopts(), addlocalopts() or addlocalopt() was called to add localopt values.
def setlocalopts (self, localopts)
Sets MPI options that are only meaningful to the currently used MPI configuration.
def addlocalopts (self, localopts)
Adds MPI options that are only meaningful to the currently used MPI configuration.
def addlocalopt (self, localopts)
Adds one MPI option to the local option list.
def localoptiter (self)
Iterates over local MPI configuration options for this rank or group of ranks.
def mixedlocalopts (self)
Do the MPI ranks within this group contain mixed values for local options?
def samelocalopts (self, other)
def getturbomode (self)
Do we want turbo mode to be enabled for this set of ranks?
def setturbomode (self, tm)
Sets the turbo mode setting: on (True) or off (False).
def delturbomode (self, tm)
Removes the request for turbo mode to be on or off.
def turbo (self, flag=True)
def rpn (self, count=0)
def env (self, kwargs)
Sets environment variables in the individual MPI ranks.
def make_runners_immutable (self)
Returns a copy of this object where all child produtil.prog.Runner objects have been replaced with produtil.prog.ImmutableRunner objects.
def get_logger (self)
Returns a logger.Logger object for this MPIRanksBase or one from its child MPIRanksBase objects (if it has any).
def check_serial (self)
Returns a tuple (s,p) where s=True if there are serial ranks in this part of the MPI program, and p=True if there are parallel ranks.
def getranks_per_node (self)
Returns the number of MPI ranks per node requsted by this MPI rank, or 0 if unspecified.
def setranks_per_node (self, rpn)
Sets the number of MPI ranks per node requsted by this MPI rank.
def delranks_per_node (self)
Unsets the requested number of ranks per node.
def nranks (self)
Returns the number of ranks in this part of the MPI program.
def ranks (self)
Iterates over all MPIRank objects in this part of the MPI program.
def ngroups (self)
Returns the number of groups of repeated MPI ranks in the MPI program.
def groups (self, threads=False)
Iterates over all groups of repeating MPI ranks in the MPI program returning tuples (r,c) containing a rank r and the count (number) of that rank c.
def getthreads (self)
Returns the number of threads requested by this MPI rank, or by each MPI rank in this group of MPI ranks.
def nonzero_threads (self)
The number of threads requested, or 1 if no threads are requested.
def setthreads (self, nthreads)
Sets the number of threads requested by each MPI rank within this group of MPI ranks.
def delthreads (self)
Removes the request for threads.
def __mul__ (self, factor)
Returns a new set of MPI ranks that consist of this group of ranks repeated "factor" times.
def __rmul__ (self, other)
Returns a new set of MPI ranks that consist of this group of ranks repeated "factor" times.
def __add__ (self, other)
Returns a new set of MPI ranks that consist of this set of ranks with the "other" set appended.
def __radd__ (self, other)
Returns a new set of MPI ranks that consist of the "other" set of ranks with this set appended.
def isplainexe (self)
Determines if this set of MPI ranks can be represented by a single serial executable with a single set of arguments run without MPI.
def to_shell (self)
Returns a POSIX sh command that will execute the serial program, if possible, or raise a subclass of NotValidPosixSh otherwise.
def expand_iter (self, expand, threads=False)
This is a wrapper around ranks() and groups() which will call self.groups() if expand=False.
def __repr__ (self)
Returns a string representation of this object intended for debugging.
def __eq__ (self, other)
Static Public Attributes
turbomode
ranks_per_node
The number of MPI ranks per node or 0 if no specific request is made.
threads
Member Function Documentation
__add__()
def produtil.mpiprog.MPIRanksBase.__add__ (self, other)
Returns a new set of MPI ranks that consist of this set of ranks with the "other" set appended.
Parameters
other the data to append
Definition at line 394 of file mpiprog.py.
__mul__()
def produtil.mpiprog.MPIRanksBase.__mul__ (self, factor)
Returns a new set of MPI ranks that consist of this group of ranks repeated "factor" times.
Parameters
factor how many times to duplicate
Definition at line 384 of file mpiprog.py.
__radd__()
def produtil.mpiprog.MPIRanksBase.__radd__ (self, other)
Returns a new set of MPI ranks that consist of the "other" set of ranks with this set appended.
Parameters
other the data to prepend
Definition at line 399 of file mpiprog.py.
__repr__()
def produtil.mpiprog.MPIRanksBase.__repr__ (self)
Returns a string representation of this object intended for debugging.
Definition at line 437 of file mpiprog.py.
Referenced by produtil.prog.Runner.__str__().
__rmul__()
def produtil.mpiprog.MPIRanksBase.__rmul__ (self, other)
Returns a new set of MPI ranks that consist of this group of ranks repeated "factor" times.
Parameters
other how many times to duplicate
Definition at line 389 of file mpiprog.py.
addlocalopt()
def produtil.mpiprog.MPIRanksBase.addlocalopt (self, localopts)
Adds one MPI option to the local option list.
This is an option that is only meaningful to the currently used MPI configuration.
This function lets the ush-level scripts pass platform-specific information to the produtil.mpi_impl package, in order to make platform-specific changes to the way in which MPI programs are launched. These local options are a list of options that are sent for groups of MPI ranks. If the setlocalopts is called in a high-level group of ranks, such as MPIRanksMPMD, then it will apply to all ranks within.
Parameters
localopts Options to set. These will append the given options to the end of the list of local options. Use addlocalopts() to add a list to the end, or setlocalopts() to replace the entire list.
Returns
self
Definition at line 223 of file mpiprog.py.
addlocalopts()
def produtil.mpiprog.MPIRanksBase.addlocalopts (self, localopts)
Adds MPI options that are only meaningful to the currently used MPI configuration.
This function lets the ush-level scripts pass platform-specific information to the produtil.mpi_impl package, in order to make platform-specific changes to the way in which MPI programs are launched. These local options are a list of options that are sent for groups of MPI ranks. If the setlocalopts is called in a high-level group of ranks, such as MPIRanksMPMD, then it will apply to all ranks within.
Parameters
localopts Iterable of options to set. These will extend the list of local options, adding the iterable of specified options to the end. Use addlocalopt() to add one option, or setlocalopt() to replace the entire list.
Returns
self
Definition at line 204 of file mpiprog.py.
check_serial()
def produtil.mpiprog.MPIRanksBase.check_serial (self)
Returns a tuple (s,p) where s=True if there are serial ranks in this part of the MPI program, and p=True if there are parallel ranks.
Note that it is possible that both could be True, which is an error. It is also possible that neither are True if there are zero ranks.
Definition at line 299 of file mpiprog.py.
delranks_per_node()
def produtil.mpiprog.MPIRanksBase.delranks_per_node (self)
Unsets the requested number of ranks per node.
Definition at line 320 of file mpiprog.py.
delthreads()
def produtil.mpiprog.MPIRanksBase.delthreads (self)
Removes the request for threads.
Definition at line 378 of file mpiprog.py.
delturbomode()
def produtil.mpiprog.MPIRanksBase.delturbomode (self, tm)
Removes the request for turbo mode to be on or off.
Definition at line 272 of file mpiprog.py.
expand_iter()
def produtil.mpiprog.MPIRanksBase.expand_iter (self, expand, threads = False)
This is a wrapper around ranks() and groups() which will call self.groups() if expand=False.
If expand=True, this will call ranks() returning a tuple (rank,1) for each rank.
Parameters
expand If True, expand groups of identical ranks into one rank of each member
threads If True, then a third element will be in each tuple: the number of requested threads per MPI rank.
Definition at line 416 of file mpiprog.py.
Referenced by produtil.mpiprog.MPIRanksBase.__repr__(), and produtil.mpiprog.MPIRanksBase.to_arglist().
get_logger()
def produtil.mpiprog.MPIRanksBase.get_logger (self)
Returns a logger.Logger object for this MPIRanksBase or one from its child MPIRanksBase objects (if it has any).
If no logger is found, None is returned.
Definition at line 294 of file mpiprog.py.
getranks_per_node()
def produtil.mpiprog.MPIRanksBase.getranks_per_node (self)
Returns the number of MPI ranks per node requsted by this MPI rank, or 0 if unspecified.
Definition at line 307 of file mpiprog.py.
getthreads()
def produtil.mpiprog.MPIRanksBase.getthreads (self)
Returns the number of threads requested by this MPI rank, or by each MPI rank in this group of MPI ranks.
If different ranks have different numbers of threads, returns the maximum requested. Returns None if no threads are requested.
Definition at line 351 of file mpiprog.py.
Referenced by produtil.mpiprog.MPIRanksBase.nonzero_threads().
getturbomode()
def produtil.mpiprog.MPIRanksBase.getturbomode (self)
Do we want turbo mode to be enabled for this set of ranks?
Returns
None if unknown, True if turbo mode is explicitly enabled and False if turbo mode is explicitly disabled.
Definition at line 260 of file mpiprog.py.
groups()
def produtil.mpiprog.MPIRanksBase.groups (self, threads = False)
Iterates over all groups of repeating MPI ranks in the MPI program returning tuples (r,c) containing a rank r and the count (number) of that rank c.
Parameters
threads If True, then a three-element tuple is iterated, (r,c,t) where the third element is the number of threads.
Definition at line 342 of file mpiprog.py.
Referenced by produtil.mpiprog.MPIRanksBase.delthreads(), produtil.mpiprog.MPIRanksBase.expand_iter(), and produtil.mpiprog.MPIRanksBase.setthreads().
haslocalopts()
def produtil.mpiprog.MPIRanksBase.haslocalopts (self)
Returns True if setlocalopts(), addlocalopts() or addlocalopt() was called to add localopt values.
Definition at line 182 of file mpiprog.py.
Referenced by produtil.mpiprog.MPIRank.__repr__().
isplainexe()
def produtil.mpiprog.MPIRanksBase.isplainexe (self)
Determines if this set of MPI ranks can be represented by a single serial executable with a single set of arguments run without MPI.
Returns false by default: this function can only return true for MPISerial.
Definition at line 404 of file mpiprog.py.
localoptiter()
def produtil.mpiprog.MPIRanksBase.localoptiter (self)
Iterates over local MPI configuration options for this rank or group of ranks.
Definition at line 243 of file mpiprog.py.
make_runners_immutable()
def produtil.mpiprog.MPIRanksBase.make_runners_immutable (self)
Returns a copy of this object where all child produtil.prog.Runner objects have been replaced with produtil.prog.ImmutableRunner objects.
Definition at line 290 of file mpiprog.py.
ngroups()
def produtil.mpiprog.MPIRanksBase.ngroups (self)
Returns the number of groups of repeated MPI ranks in the MPI program.
Definition at line 338 of file mpiprog.py.
nonzero_threads()
def produtil.mpiprog.MPIRanksBase.nonzero_threads (self)
The number of threads requested, or 1 if no threads are requested.
This is a simple wrapper around getthreads
Definition at line 364 of file mpiprog.py.
nranks()
def produtil.mpiprog.MPIRanksBase.nranks (self)
Returns the number of ranks in this part of the MPI program.
Definition at line 330 of file mpiprog.py.
Referenced by produtil.mpiprog.MPIRanksSPMD.__add__(), produtil.mpiprog.MPISerial.__add__(), and produtil.mpiprog.MPIRanksBase.to_arglist().
ranks()
def produtil.mpiprog.MPIRanksBase.ranks (self)
Iterates over all MPIRank objects in this part of the MPI program.
Definition at line 334 of file mpiprog.py.
Referenced by produtil.mpiprog.MPIRanksBase.expand_iter().
setlocalopts()
def produtil.mpiprog.MPIRanksBase.setlocalopts (self, localopts)
Sets MPI options that are only meaningful to the currently used MPI configuration.
This function lets the ush-level scripts pass platform-specific information to the produtil.mpi_impl package, in order to make platform-specific changes to the way in which MPI programs are launched. These local options are a list of options that are sent for groups of MPI ranks. If the setlocalopts is called in a high-level group of ranks, such as MPIRanksMPMD, then it will apply to all ranks within.
Parameters
localopts Options to set. These will replace any options already set. Use addlocalopts to append the end instead.
Returns
self
Definition at line 186 of file mpiprog.py.
setranks_per_node()
def produtil.mpiprog.MPIRanksBase.setranks_per_node (self, rpn)
Sets the number of MPI ranks per node requsted by this MPI rank.
Definition at line 312 of file mpiprog.py.
setthreads()
def produtil.mpiprog.MPIRanksBase.setthreads (self, nthreads)
Sets the number of threads requested by each MPI rank within this group of MPI ranks.
Definition at line 371 of file mpiprog.py.
setturbomode()
def produtil.mpiprog.MPIRanksBase.setturbomode (self, tm)
Sets the turbo mode setting: on (True) or off (False).
Definition at line 265 of file mpiprog.py.
to_arglist()
def produtil.mpiprog.MPIRanksBase.to_arglist (self, to_shell = False, expand = False, shell_validate = None, pre = [], before = [], between = [], after = [], post = [], extra = {}, include_localopts = False)
This is the underlying implementation of most of the mpi_impl modules, and hence make_runner as well.
It converts this group of MPI ranks into a set of arguments suitable for sending to a Runner object or for writing to a command file. This is done by iterating over either all ranks (if expand=True) or groups of repeated ranks (if expand=False), converting their arguments to a list. It prepends an executable, and can insert other arguments in specified locations (given in the pre, before, between, after, and post arguments). It can also use the to_shell argument to convert programs to POSIX sh commands, and it performs simple string interpolation via the "extra" hash.
If to_shell=False then the executable and arguments are inserted directly to the output list. Otherwise (when to_shell=True) the to_shell subroutine is called on the MPIRank object to produce a single argument that contains a shell command. That single argument is then used in place of the executable and arguments. Note that may raise NotValidPosixSh (or a subclass thereof) if the command cannot be expressed as a shell command. In addition, if shell_validate is not None, then it is called on each post-conversion shell argument, and the return value is used instead.
You can specify additional argument lists to be inserted in certain locations. Each argument in those lists will be processed through the % operator, specifying "extra" as the keyword list with two new keywords added: nworld is the number of ranks in the MPI program, and "n" is the number in the current group of repeated ranks if expand=False (n=1 if expand=True). Those argument lists are: pre, before, between, after and post.
Parameters
to_shell If True, convert executable and arguments to a POSIX sh command instead of inserting them directly.
expand If True, groups of repeated ranks are expanded.
shell_validate A function to convert each argument to some "shell-acceptable" version.
pre Inserted before everything else. This is where you would put the "mpiexec" and any global settings.
before Inserted before each rank (if expand=True) or group (if expand=False)
between Inserted between each rank (if expand=True) or group (if expand=False)
after Inserted after each rank (if expand=True) or group (if expand=False)
post Appended at the end of the list of arguments.
extra used for string expansion
include_localopts If True, then self._localopts is appended between the "before" argument and the command.
Definition at line 100 of file mpiprog.py.
to_shell()
def produtil.mpiprog.MPIRanksBase.to_shell (self)
Returns a POSIX sh command that will execute the serial program, if possible, or raise a subclass of NotValidPosixSh otherwise.
Works only on single MPI ranks that are actually MPI wrappers around a serial program (ie.: from mpiserial).
Definition at line 410 of file mpiprog.py.
Member Data Documentation
ranks_per_node
produtil.mpiprog.MPIRanksBase.ranks_per_node static
The number of MPI ranks per node or 0 if no specific request is made.
Definition at line 324 of file mpiprog.py.
Referenced by produtil.mpiprog.MPIRanksSPMD.__add__(), and produtil.mpiprog.MPIRanksBase.delturbomode().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/produtil/mpiprog.py