METplus: produtil.numerics.TimeContainer Class Reference
produtil.numerics.TimeContainer Class Reference
Abstract base class that maps from time to objects.
Detailed Description
Abstract base class that maps from time to objects.
This is the abstract base class of any class that represents a mapping from a set of times to a set of data. It provides the underlying implementation of TimeArray and TimeMapping. This is not exported by "from produtil.numerics import *" to prevent accidental use.
Definition at line 525 of file numerics.py.
Public Member Functions
def __init__ (self, times, init=None)
TimeContainer constructor.
def at_index (self, index)
Returns the data at the given index, or raises KeyError if no data exists.
def index_of (self, when)
This virtual function should be implemented in a subclass.
def lasttime (self)
Returns the last time in the array or list of times, even if it has no data.
def firsttime (self)
Returns the first time in the array or list of times, even if it has no data.
def __getitem__ (self, when)
Returns the item at the latest time that is not later than "when".
def neartime (self, when, epsilon=None)
Returns a tuple containing the time nearest to "when" without going over, and the index of that time.
def get (self, when, default)
Returns the item at the latest time that is not later than "when.".
def __setitem__ (self, when, val)
Finds the latest time that is not later than "when" in self._times.
def __iter__ (self)
Iterates over all data.
def itervalues (self)
Iterates over data for all known times that have data.
def iterkeys (self)
Iterates over all times that have data.
def iteritems (self)
Alias for items() for backward compatibility.
def items (self)
Iterates over all known times that have data, returning a tuple containing the time and the data at that time.
def __reversed__ (self)
Iterates over all known times that have data, in reverse order.
def __delitem__ (self, when)
Finds the latest time that is not later than "when" and removes the data it is mapped to.
def __contains__ (self, when)
Finds the latest time that is not later than "when" in self._times.
def __len__ (self)
Returns the number of times that have data.
def times (self)
Iterates over all times in this TimeContainer.
def datatimes (self)
Iterates over all times in this TimeContainer that map to data.
def __str__ (self)
Returns a string representation of this object.
def datatimes_reversed (self)
Iterates in reverse order over all times in this TimeContainer that map to data.
Constructor & Destructor Documentation
__init__()
def produtil.numerics.TimeContainer.__init__ (self, times, init = None)
TimeContainer constructor.
Initializes the internal arrays for the given list of times, which must not be empty. Note that strange, potentially bad things will happen if there are duplicate times.
Implementation notes:
self._times[N]: a list of times
self._data[N]: the data for each time
self._assigned[N]: True if there is data for this time,
  False otherwise
where N is the length of the input times array. The _data will be filled with init() and _assigned filled with True if init is present and not None, otherwise _assigned will be False.
Parameters
times the times to map from
init a constructor or function that creates initial values for all uninitialized array elements
Definition at line 534 of file numerics.py.
Member Function Documentation
__contains__()
def produtil.numerics.TimeContainer.__contains__ (self, when)
Finds the latest time that is not later than "when" in self._times.
Returns True if there is data mapped to that time and False otherwise.
Parameters
when the time of interest
Definition at line 681 of file numerics.py.
__delitem__()
def produtil.numerics.TimeContainer.__delitem__ (self, when)
Finds the latest time that is not later than "when" and removes the data it is mapped to.
Later calls to getitem, get, iter and so on, will not return any data for this time.
Parameters
when the time of disinterest
Definition at line 672 of file numerics.py.
__getitem__()
def produtil.numerics.TimeContainer.__getitem__ (self, when)
Returns the item at the latest time that is not later than "when".
If there is no data assigned at that time, then KeyError is raised.
Parameters
when the time of interest
Definition at line 589 of file numerics.py.
__iter__()
def produtil.numerics.TimeContainer.__iter__ (self)
Iterates over all data.
Definition at line 639 of file numerics.py.
__len__()
def produtil.numerics.TimeContainer.__len__ (self)
Returns the number of times that have data.
Definition at line 691 of file numerics.py.
__reversed__()
def produtil.numerics.TimeContainer.__reversed__ (self)
Iterates over all known times that have data, in reverse order.
Definition at line 664 of file numerics.py.
__setitem__()
def produtil.numerics.TimeContainer.__setitem__ (self, when, val)
Finds the latest time that is not later than "when" in self._times.
Assigns "val" to that time.
Parameters
when the time of interest
val the value to assign to that time
Definition at line 629 of file numerics.py.
__str__()
def produtil.numerics.TimeContainer.__str__ (self)
Returns a string representation of this object.
Definition at line 703 of file numerics.py.
at_index()
def produtil.numerics.TimeContainer.at_index (self, index)
Returns the data at the given index, or raises KeyError if no data exists.
Parameters
index the desired index
Definition at line 566 of file numerics.py.
datatimes()
def produtil.numerics.TimeContainer.datatimes (self)
Iterates over all times in this TimeContainer that map to data.
Definition at line 698 of file numerics.py.
datatimes_reversed()
def produtil.numerics.TimeContainer.datatimes_reversed (self)
Iterates in reverse order over all times in this TimeContainer that map to data.
Definition at line 714 of file numerics.py.
firsttime()
def produtil.numerics.TimeContainer.firsttime (self)
Returns the first time in the array or list of times, even if it has no data.
Definition at line 585 of file numerics.py.
get()
def produtil.numerics.TimeContainer.get (self, when, default)
Returns the item at the latest time that is not later than "when.".
Parameters
when the time of interest
default If there is no data assigned at that time then the given default is returned.
Definition at line 618 of file numerics.py.
index_of()
def produtil.numerics.TimeContainer.index_of (self, when)
This virtual function should be implemented in a subclass.
It should return the index of the time to use for the given time.
Parameters
when the time of interest
Definition at line 572 of file numerics.py.
Referenced by produtil.numerics.TimeContainer.__contains__(), produtil.numerics.TimeContainer.__delitem__(), produtil.numerics.TimeContainer.__getitem__(), produtil.numerics.TimeContainer.__setitem__(), produtil.numerics.TimeContainer.get(), and produtil.numerics.TimeContainer.neartime().
items()
def produtil.numerics.TimeContainer.items (self)
Iterates over all known times that have data, returning a tuple containing the time and the data at that time.
Definition at line 658 of file numerics.py.
Referenced by produtil.numerics.TimeContainer.iteritems().
iterkeys()
def produtil.numerics.TimeContainer.iterkeys (self)
Iterates over all times that have data.
Definition at line 649 of file numerics.py.
itervalues()
def produtil.numerics.TimeContainer.itervalues (self)
Iterates over data for all known times that have data.
Definition at line 644 of file numerics.py.
lasttime()
def produtil.numerics.TimeContainer.lasttime (self)
Returns the last time in the array or list of times, even if it has no data.
Definition at line 580 of file numerics.py.
neartime()
def produtil.numerics.TimeContainer.neartime (self, when, epsilon = None)
Returns a tuple containing the time nearest to "when" without going over, and the index of that time.
Parameters
epsilon If specified, raise hwrf.exceptions.NoNearbyValues if no times are near that value.
when the time of interest
Definition at line 598 of file numerics.py.
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/produtil/numerics.py