METplus: produtil.pipeline.Pipeline Class Reference
produtil.pipeline.Pipeline Class Reference
This class is a wrapper around launch and manage.
Detailed Description
This class is a wrapper around launch and manage.
It converts Runner objects to calls to "launch", and runs "manage" on the resulting processes.
Definition at line 577 of file pipeline.py.
Public Member Functions
def __init__ (self, runner, capture=False, logger=None, debug=False, binary=False)
Pipeline constructor.
def __repr__ (self)
Return a debug string representation of this Pipeline.
def send_signal (self, sig)
Sends a signal to all children.
def terminate (self)
Sends SIGTERM to all children.
def kill (self)
Sends SIGKILL to all children.
def communicate (self, sleeptime=None)
Writes to input, reads from output, waits for child processes, etc.
def poll (self)
Returns the exit status of the last element of the pipeline.
def to_string (self)
Calls self.communicate(), and returns the stdout from the pipeline (self.outbytes).
def out (self)
The stdout from the pipeline.
Constructor & Destructor Documentation
__init__()
def produtil.pipeline.Pipeline.__init__ (self, runner, capture = False, logger = None, debug = False, binary = False)
Pipeline constructor.
Parameters
runner the produtil.prog.Runner to convert
capture if True, capture the stdout of the runner
logger a logging.Logger for messages
debug if True, send debug messages
binary use binary streams for input and output
Definition at line 582 of file pipeline.py.
Member Function Documentation
__repr__()
def produtil.pipeline.Pipeline.__repr__ (self)
Return a debug string representation of this Pipeline.
Definition at line 605 of file pipeline.py.
Referenced by produtil.prog.Runner.__str__().
communicate()
def produtil.pipeline.Pipeline.communicate (self, sleeptime = None)
Writes to input, reads from output, waits for child processes, etc.
This is just a wrapper around the manage() function. It will return immediately if self.communicate has already completed earlier.
Parameters
sleeptime the sleep time in seconds between checks
Definition at line 670 of file pipeline.py.
Referenced by produtil.pipeline.Pipeline.to_string().
kill()
def produtil.pipeline.Pipeline.kill (self)
Sends SIGKILL to all children.
Definition at line 661 of file pipeline.py.
out()
def produtil.pipeline.Pipeline.out (self)
The stdout from the pipeline.
Will be Null if the pipeline was redirected to a file, or if the constructor's capture option was not True.
Definition at line 713 of file pipeline.py.
Referenced by produtil.prog.Runner.__gt__(), produtil.prog.Runner.__rshift__(), and produtil.pipeline.Pipeline.to_string().
poll()
def produtil.pipeline.Pipeline.poll (self)
Returns the exit status of the last element of the pipeline.
If the process died due to a signal, returns a negative number.
Definition at line 687 of file pipeline.py.
send_signal()
def produtil.pipeline.Pipeline.send_signal (self, sig)
Sends a signal to all children.
Parameters
sig the signal
Definition at line 650 of file pipeline.py.
Referenced by produtil.pipeline.Pipeline.kill(), and produtil.pipeline.Pipeline.terminate().
terminate()
def produtil.pipeline.Pipeline.terminate (self)
Sends SIGTERM to all children.
Definition at line 658 of file pipeline.py.
to_string()
def produtil.pipeline.Pipeline.to_string (self)
Calls self.communicate(), and returns the stdout from the pipeline (self.outbytes).
The return value will be Null if the pipeline was redirected to a file or if the constructor's capture option was not True.
Definition at line 701 of file pipeline.py.
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/produtil/pipeline.py