METplus: produtil.datastore.Datum Class Reference
produtil.datastore.Datum Class Reference
Superclass of anything that can be stored in a Datastore.
Detailed Description
Superclass of anything that can be stored in a Datastore.
This is the superclass of anything that can be placed in a datastore. It has a category, a product name (prodname for short), a location, availability (an int) and arbitrary metadata (key,value) pairs. It caches database metadata in self._meta, which is directly accessed by the Datastore class. Cache data will be discarded once its age is older than self._cacheage.
Definition at line 425 of file datastore.py.
Public Member Functions
def __init__ (self, dstore, prodname, category, meta=None, cache=30, location=None, kwargs)
Datum constructor.
def __enter__ (self)
Acquires this object's thread lock.
def __exit__ (self, etype, evalue, traceback)
Releases this object's thread lock.
def validate (self)
Validates this object's Datastore, prodname and category.
def getid (self)
Returns the database ID of this datum.
def getdatastore (self)
Returns the datastore of this datum.
def transaction (self)
Creates, but does not lock, a Transaction for this datum's datastore.
def getprodtype (self)
Returns the product type of this Datum.
def getprodname (self)
Returns the product name part of the database ID.
def getcategory (self)
Returns the product category part of the database ID.
def getlocation (self)
Returns the "location" field of this Datum's database entry.
def setlocation (self, v)
Sets the "location" field of this Datum's database entry.
def __hash__ (self)
Integer hash function.
def __str__ (self)
Human-readable description of this Datum.
def __repr__ (self)
Python code-like description of this Datum.
def __lt__ (self, other)
Compares two Datums' prodnames and categories.
def __gt__ (self, other)
Compares two Datums' prodnames and categories.
def __eq__ (self, other)
Compares two Datums' prodnames and categories.
def __ne__ (self, other)
Compares two Datums' prodnames and categories.
def __ge__ (self, other)
Compares two Datums' prodnames and categories.
def __le__ (self, other)
Compares two Datums' prodnames and categories.
def set_loc_avail (self, loc, avail)
Sets the location and availability of this Datum in a single transaction.
def update (self)
Discards all cached metadata and refreshes it from the Datastore.
def __getitem__ (self, k)
Returns the value of the specified metadata key or raises KeyError.
def meta (self, k, default=None)
Return the value of a metadata key.
def get (self, k, default=None)
Alias for self.meta() Returns the value of the specified metadata key or returns default if it is unset.
def __setitem__ (self, k, v)
Sets the value of the specified metadata key.
def __delitem__ (self, k)
Deletes the specified metadata key, which must not be "available" or "location".
def __contains__ (self, k)
Determines if a metadata key is set.
def iteritems (self)
Alias for items() for backward compatibility.
def items (self)
Iterates over all metadata (key,value) pairs for this Datum, including "available" and "location".
Properties
prodname = property(getprodname,None,None,)
Read-only property, an alias for getprodname(): the product name part of the database ID.
category = property(getcategory,None,None,)
Read-only property, an alias for getcategory(), the category name part of the database ID.
prodtype
Read-only property, an alias for getprodtype(), the product type.
did
Read-only property, an alias for getid().
dstore
Read-only property, an alias for getdatastore(), the Datastore in which this Datum resides.
location
Read-write property, an alias for getlocation() and setlocation().
Constructor & Destructor Documentation
__init__()
def produtil.datastore.Datum.__init__ (self, dstore, prodname, category, meta = None, cache = 30, location = None, kwargs)
Datum constructor.
Creates a Datum in the given Datastore dstore, under the specified category and product name prodname. The datastore id used is "category::prodname". The value for "cache" is the number of seconds to retain cached metadata before going back to disk to reread it. That only applies to data "get" operations: setting a data or metadata value will cause an immediate write to the database. Also, contains ("var" in self) will force a fetch from the database if the requested metadata variable is not in the cached copy of the database.
Values for location and meta are only the DEFAULT values, and will be ignored if other values are already set in the database. The location is only used if the product is not already in the database: its location will be set to the provided values upon entry. Similarly, the metadata is only set in this call if there isn't already metadata for the product with the given metadata keys.
Parameters
dstore The Datastore for this Datum.
prodname The product name portion of the Datum ID
category The category part of the Datum ID
meta A dict of metadata values.
cache Metadata cache lifetime in seconds.
location The initial value for location, if it is not set already in the database.
kwargs Ignored.
Definition at line 434 of file datastore.py.
Member Function Documentation
__contains__()
def produtil.datastore.Datum.__contains__ (self, k)
Determines if a metadata key is set.
Returns
True if the specified metadata key is set, and False otherwise. Immediately returns True for 'available' and 'location' without checking the metadata cache.
Parameters
k the key of interest
Definition at line 691 of file datastore.py.
__delitem__()
def produtil.datastore.Datum.__delitem__ (self, k)
Deletes the specified metadata key, which must not be "available" or "location".
Parameters
k the key to delete
Definition at line 681 of file datastore.py.
__enter__()
def produtil.datastore.Datum.__enter__ (self)
Acquires this object's thread lock.
This is used to manage cached data.
Definition at line 483 of file datastore.py.
__eq__()
def produtil.datastore.Datum.__eq__ (self, other)
Compares two Datums' prodnames and categories.
Parameters
other the other datum to compare against
Definition at line 591 of file datastore.py.
__exit__()
def produtil.datastore.Datum.__exit__ (self, etype, evalue, traceback)
Releases this object's thread lock.
This is used to manage cached data.
Parameters
etype,evalue,traceback Exception information.
Definition at line 487 of file datastore.py.
__ge__()
def produtil.datastore.Datum.__ge__ (self, other)
Compares two Datums' prodnames and categories.
Parameters
other the other datum to compare against
Definition at line 599 of file datastore.py.
__getitem__()
def produtil.datastore.Datum.__getitem__ (self, k)
Returns the value of the specified metadata key or raises KeyError.
Forces a cache update if k is not in the cache.
Definition at line 643 of file datastore.py.
__gt__()
def produtil.datastore.Datum.__gt__ (self, other)
Compares two Datums' prodnames and categories.
Parameters
other the other datum to compare against
Definition at line 583 of file datastore.py.
__hash__()
def produtil.datastore.Datum.__hash__ (self)
Integer hash function.
Definition at line 565 of file datastore.py.
__le__()
def produtil.datastore.Datum.__le__ (self, other)
Compares two Datums' prodnames and categories.
Parameters
other the other datum to compare against
Definition at line 603 of file datastore.py.
__lt__()
def produtil.datastore.Datum.__lt__ (self, other)
Compares two Datums' prodnames and categories.
Parameters
other the other datum to compare against
Definition at line 575 of file datastore.py.
__ne__()
def produtil.datastore.Datum.__ne__ (self, other)
Compares two Datums' prodnames and categories.
Parameters
other the other datum to compare against
Definition at line 595 of file datastore.py.
__repr__()
def produtil.datastore.Datum.__repr__ (self)
Python code-like description of this Datum.
Definition at line 571 of file datastore.py.
Referenced by produtil.prog.Runner.__str__().
__setitem__()
def produtil.datastore.Datum.__setitem__ (self, k, v)
Sets the value of the specified metadata key.
Parameters
k the key
v the value
Definition at line 673 of file datastore.py.
__str__()
def produtil.datastore.Datum.__str__ (self)
Human-readable description of this Datum.
Definition at line 568 of file datastore.py.
get()
def produtil.datastore.Datum.get (self, k, default = None)
Alias for self.meta() Returns the value of the specified metadata key or returns default if it is unset.
Does NOT force a cache update if k is missing from the cache. To force a cache update, use getitem instead.
Parameters
k The key of interest.
default The value to return if no value is seen.
Returns
The metadata value or the default.
Definition at line 661 of file datastore.py.
Referenced by produtil.datastore.UpstreamFile.check(), produtil.config.ProdTask.confget(), produtil.config.ProdTask.getdir(), produtil.config.ProdTask.getexe(), and produtil.datastore.Datum.meta().
getcategory()
def produtil.datastore.Datum.getcategory (self)
Returns the product category part of the database ID.
Definition at line 519 of file datastore.py.
getdatastore()
def produtil.datastore.Datum.getdatastore (self)
Returns the datastore of this datum.
Definition at line 503 of file datastore.py.
getid()
def produtil.datastore.Datum.getid (self)
Returns the database ID of this datum.
Definition at line 500 of file datastore.py.
getlocation()
def produtil.datastore.Datum.getlocation (self)
Returns the "location" field of this Datum's database entry.
Definition at line 523 of file datastore.py.
getprodname()
def produtil.datastore.Datum.getprodname (self)
Returns the product name part of the database ID.
Definition at line 516 of file datastore.py.
getprodtype()
def produtil.datastore.Datum.getprodtype (self)
Returns the product type of this Datum.
Returns the product type of this Datum. This is generally the name of the Python class that created the entry in the database.
Definition at line 509 of file datastore.py.
items()
def produtil.datastore.Datum.items (self)
Iterates over all metadata (key,value) pairs for this Datum, including "available" and "location".
Definition at line 705 of file datastore.py.
Referenced by produtil.config.ProdTask.confitems(), produtil.numerics.TimeContainer.iteritems(), and produtil.datastore.Datum.iteritems().
meta()
def produtil.datastore.Datum.meta (self, k, default = None)
Return the value of a metadata key.
Returns the value of the specified metadata key or returns default if it is unset. Does NOT force a cache update if k is missing from the cache. To force a cache update, use getitem instead.
Parameters
k The key of interest.
default The value to return if no value is seen.
Returns
The metadata value or the default.
Definition at line 649 of file datastore.py.
Referenced by produtil.config.ProdTask.__init__(), produtil.config.ProdTask.get_outdir(), and produtil.config.ProdTask.get_workdir().
set_loc_avail()
def produtil.datastore.Datum.set_loc_avail (self, loc, avail)
Sets the location and availability of this Datum in a single transaction.
Parameters
loc the new location, a string
avail the new availability, an int
Definition at line 607 of file datastore.py.
Referenced by produtil.datastore.UpstreamFile.check(), and produtil.datastore.FileProduct.deliver().
setlocation()
def produtil.datastore.Datum.setlocation (self, v)
Sets the "location" field of this Datum's database entry.
Parameters
v the new location
Definition at line 526 of file datastore.py.
transaction()
def produtil.datastore.Datum.transaction (self)
Creates, but does not lock, a Transaction for this datum's datastore.
Definition at line 506 of file datastore.py.
Referenced by produtil.datastore.Datum.__delitem__(), produtil.datastore.Datum.__init__(), produtil.datastore.Datum.__setitem__(), and produtil.datastore.Datum.set_loc_avail().
update()
def produtil.datastore.Datum.update (self)
Discards all cached metadata and refreshes it from the Datastore.
Definition at line 638 of file datastore.py.
Referenced by produtil.datastore.Product.check().
validate()
def produtil.datastore.Datum.validate (self)
Validates this object's Datastore, prodname and category.
Definition at line 492 of file datastore.py.
Referenced by produtil.datastore.Datum.__init__(), and produtil.mpiprog.MPIRank.__init__().
Property Documentation
category
produtil.datastore.Datum.category = property(getcategory,None,None,) static
Read-only property, an alias for getcategory(), the category name part of the database ID.
Definition at line 539 of file datastore.py.
did
produtil.datastore.Datum.did static
Initial value:
= property(getid,None,None,
                 )
Read-only property, an alias for getid().
The full database ID.
Definition at line 550 of file datastore.py.
Referenced by produtil.datastore.Datum.__str__(), produtil.datastore.Product.call_callbacks(), produtil.datastore.FileProduct.deliver(), and produtil.datastore.Datum.set_loc_avail().
dstore
produtil.datastore.Datum.dstore static
Initial value:
= property(getdatastore,None,None,
                    )
Read-only property, an alias for getdatastore(), the Datastore in which this Datum resides.
Definition at line 556 of file datastore.py.
Referenced by produtil.datastore.Datum.__repr__(), and produtil.datastore.Datum.set_loc_avail().
location
produtil.datastore.Datum.location static
Initial value:
= property(getlocation,setlocation,None,
                      )
Read-write property, an alias for getlocation() and setlocation().
The location on disk of this Datum.
Definition at line 562 of file datastore.py.
Referenced by produtil.datastore.UpstreamFile.check(), produtil.datastore.FileProduct.deliver(), and produtil.datastore.FileProduct.undeliver().
prodname
produtil.datastore.Datum.prodname = property(getprodname,None,None,) static
Read-only property, an alias for getprodname(): the product name part of the database ID.
Definition at line 534 of file datastore.py.
prodtype
produtil.datastore.Datum.prodtype static
Initial value:
= property(getprodtype,None,None,
                      )
Read-only property, an alias for getprodtype(), the product type.
This is generally the name of the Python class that created the entry in the database.
Definition at line 545 of file datastore.py.
Referenced by produtil.datastore.Datum.__repr__(), and produtil.datastore.Datum.__str__().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/produtil/datastore.py