METplus: produtil.config.ProdTask Class Reference
produtil.config.ProdTask Class Reference
A subclass of produtil.datastore.Task that provides a variety of convenience functions related to unix conf files and logging.
Detailed Description
A subclass of produtil.datastore.Task that provides a variety of convenience functions related to unix conf files and logging.
Definition at line 1349 of file config.py.
Public Member Functions
def __init__ (self, dstore, conf, section, taskname=None, workdir=None, outdir=None, taskvars=UNSPECIFIED, kwargs)
Creates an ProdTask.
def get_workdir (self)
Returns the directory the class should work in, as set by the "workdir" metadata value.
def set_workdir (self, val)
Sets the directory the class should work in.
def get_outdir (self)
Gets the directory that should receive output data.
def set_outdir (self, val)
Sets the directory that should receive output data.
def tvset (self, opt, val)
Sets a taskvar option's value.
def tvdel (self, opt)
Deletes an object-local value set by tvset.
def tvget (self, opt)
Gets a taskvar's value.
def tvhave (self, opt=UNSPECIFIED)
Is a taskvar set?
def taskvars (self)
The dict of object-local values used for string substitution.
def confint (self, opt, default=None, badtypeok=False, section=None, morevars=None)
Alias for self.conf.getint for section self.section.
def confstr (self, opt, default=None, badtypeok=False, section=None, morevars=None)
Alias for self.conf.getstr for section self.section.
def conffloat (self, opt, default=None, badtypeok=False, section=None, morevars=None)
Alias for self.conf.getfloat for section self.section.
def confbool (self, opt, default=None, badtypeok=False, section=None, morevars=None)
Alias for self.conf.getbool for section self.section.
def confget (self, opt, default=None, badtypeok=False, section=None, morevars=None)
Alias for self.conf.get for section self.section.
def confitems (self, section=None, morevars=None)
Alias for self.conf.items for section self.section.
def confstrinterp (self, string, section=None, kwargs)
Alias for self.icstr for backward compatibility.
def conftimestrinterp (self, string, ftime, atime=None, section=None, kwargs)
Alias for self.timestr for backward comaptibility.
def confraw (self, opt, default=None, section=None)
Get a raw configuration value before string expansion.
def icstr (self, string, section=None, kwargs)
Expands a string in the given conf section.
def timestr (self, string, ftime=None, atime=None, section=None, kwargs)
Expands a string in the given conf section, including time vars.
def getdir (self, opt, default=None, morevars=None)
Alias for produtil.config.ProdConfig.get() for the "dir" section.
def getexe (self, opt, default=None, morevars=None)
Alias for produtil.config.ProdConfig.get() for the "exe" section.
def getconf (self)
Returns this ProdTask's produtil.config.ProdConfig object.
def getsection (self)
Returns this ProdTask's section name in the ProdConfig.
def log (self, subdom=None)
Obtain a logging domain.
Public Member Functions inherited from produtil.datastore.Task
def __init__ (self, dstore, taskname, logger=None, kwargs)
Task constructor.
def jlogfile (self)
returns the jlogfile logger.
def postmsg (self, message, args, kwargs)
same as produtil.log.jlogger.info()
def setstate (self, val)
Sets the state of this job.
def getstate (self)
Returns the job state.
def strstate (self)
A string representation of the job state.
def gettaskname (self)
Returns the task name part of the database ID, which is the same as the prodname.
def products (self, args, kwargs)
Iterate over the products this task produces.
def log (self)
Returns the logger object for this task.
def clean (self)
Cleans up any unneeded data used by this task.
def unrun (self)
Undoes the effect of run().
def run (self)
Performs the work this Task should do and generates all products.
def is_completed (self)
Is this task complete?
def completed (self)
Read-only property: is this task completed? Same as is_completed()
def runpart (self)
Run some of this task's work, deliver some products.
Public Member Functions inherited from produtil.datastore.Datum
def __init__ (self, dstore, prodname, category, meta=None, cache=30, location=None, kwargs)
Datum constructor.
def __enter__ (self)
Acquires this object's thread lock.
def __exit__ (self, etype, evalue, traceback)
Releases this object's thread lock.
def validate (self)
Validates this object's Datastore, prodname and category.
def getid (self)
Returns the database ID of this datum.
def getdatastore (self)
Returns the datastore of this datum.
def transaction (self)
Creates, but does not lock, a Transaction for this datum's datastore.
def getprodtype (self)
Returns the product type of this Datum.
def getprodname (self)
Returns the product name part of the database ID.
def getcategory (self)
Returns the product category part of the database ID.
def getlocation (self)
Returns the "location" field of this Datum's database entry.
def setlocation (self, v)
Sets the "location" field of this Datum's database entry.
def __hash__ (self)
Integer hash function.
def __str__ (self)
Human-readable description of this Datum.
def __repr__ (self)
Python code-like description of this Datum.
def __lt__ (self, other)
Compares two Datums' prodnames and categories.
def __gt__ (self, other)
Compares two Datums' prodnames and categories.
def __eq__ (self, other)
Compares two Datums' prodnames and categories.
def __ne__ (self, other)
Compares two Datums' prodnames and categories.
def __ge__ (self, other)
Compares two Datums' prodnames and categories.
def __le__ (self, other)
Compares two Datums' prodnames and categories.
def set_loc_avail (self, loc, avail)
Sets the location and availability of this Datum in a single transaction.
def update (self)
Discards all cached metadata and refreshes it from the Datastore.
def __getitem__ (self, k)
Returns the value of the specified metadata key or raises KeyError.
def meta (self, k, default=None)
Return the value of a metadata key.
def get (self, k, default=None)
Alias for self.meta() Returns the value of the specified metadata key or returns default if it is unset.
def __setitem__ (self, k, v)
Sets the value of the specified metadata key.
def __delitem__ (self, k)
Deletes the specified metadata key, which must not be "available" or "location".
def __contains__ (self, k)
Determines if a metadata key is set.
def iteritems (self)
Alias for items() for backward compatibility.
def items (self)
Iterates over all metadata (key,value) pairs for this Datum, including "available" and "location".
Properties
workdir
The directory in which this task should be run.
outdir
The directory in which this task should deliver its final output.
conf
This ProdTask's produtil.config.ProdConfig object.
section
The confsection in self.section for this ProdTask (read-only)
Properties inherited from produtil.datastore.Task
state
Read-write property: the job state.
taskname
Read-only property: the name of this task.
Properties inherited from produtil.datastore.Datum
prodname = property(getprodname,None,None,)
Read-only property, an alias for getprodname(): the product name part of the database ID.
category = property(getcategory,None,None,)
Read-only property, an alias for getcategory(), the category name part of the database ID.
prodtype
Read-only property, an alias for getprodtype(), the product type.
did
Read-only property, an alias for getid().
dstore
Read-only property, an alias for getdatastore(), the Datastore in which this Datum resides.
location
Read-write property, an alias for getlocation() and setlocation().
Constructor & Destructor Documentation
__init__()
def produtil.config.ProdTask.__init__ (self, dstore, conf, section, taskname = None, workdir = None, outdir = None, taskvars = UNSPECIFIED, kwargs)
Creates an ProdTask.
Parameters
dstore passed to Datum: the Datastore object for this Task
conf the conf object for this task
section the conf section for this task
taskname Optional: the taskname in the datastore. Default: the section name
workdir directory in which this task should run. Any value set in the database will override this value.
outdir directory where output should be copied. This argument must not be changed throughout the lifetime of the datstore database file.
taskvars additonal variables for string expansion, sent to the taskvars arguments of produtil.config.ProdConfig member functions.
kwargs passed to the parent class constructor.
Definition at line 1356 of file config.py.
Member Function Documentation
confbool()
def produtil.config.ProdTask.confbool (self, opt, default = None, badtypeok = False, section = None, morevars = None)
Alias for self.conf.getbool for section self.section.
Parameters
opt the option name
section Optional: the section. Default: self.section
default if specified and not None, then the default is returned if an option has no value or the section does not exist
badtypeok is True, and the conversion fails, and a default is specified, the default will be returned.
morevars dict of more variables for string expansion
Definition at line 1534 of file config.py.
Referenced by produtil.config.ProdTask.conffloat().
conffloat()
def produtil.config.ProdTask.conffloat (self, opt, default = None, badtypeok = False, section = None, morevars = None)
Alias for self.conf.getfloat for section self.section.
Parameters
opt the option name
section Optional: the section. Default: self.section
default if specified and not None, then the default is returned if an option has no value or the section does not exist
badtypeok is True, and the conversion fails, and a default is specified, the default will be returned.
morevars dict of more variables for string expansion
Definition at line 1521 of file config.py.
Referenced by produtil.config.ProdTask.confstr().
confget()
def produtil.config.ProdTask.confget (self, opt, default = None, badtypeok = False, section = None, morevars = None)
Alias for self.conf.get for section self.section.
Parameters
opt the option name
section Optional: the section. Default: self.section
default if specified and not None, then the default is returned if an option has no value or the section does not exist
badtypeok is True, and the conversion fails, and a default is specified, the default will be returned.
morevars dict of more variables for string expansion
Definition at line 1547 of file config.py.
Referenced by produtil.config.ProdTask.confbool().
confint()
def produtil.config.ProdTask.confint (self, opt, default = None, badtypeok = False, section = None, morevars = None)
Alias for self.conf.getint for section self.section.
Parameters
opt the option name
section Optional: the section. Default: self.section.
default if specified and not None, then the default is returned if an option has no value or the section does not exist
badtypeok is True, and the conversion fails, and a default is specified, the default will be returned.
morevars dict of more variables for string expansion
Definition at line 1495 of file config.py.
Referenced by produtil.config.ProdTask.taskvars().
confitems()
def produtil.config.ProdTask.confitems (self, section = None, morevars = None)
Alias for self.conf.items for section self.section.
Parameters
section Optional: the section. Default: self.section.
morevars variables for string substitution
Definition at line 1559 of file config.py.
confraw()
def produtil.config.ProdTask.confraw (self, opt, default = None, section = None)
Get a raw configuration value before string expansion.
Returns the raw, uninterpolated value for the specified option, raising an exception if that option is unset. Will not search other sections, and will not search the taskvars, unlike other conf accessors.
Parameters
opt the option of interest
section Optional: the section. Default: self.section
default Optional: value to return if nothing is found.
Definition at line 1585 of file config.py.
confstr()
def produtil.config.ProdTask.confstr (self, opt, default = None, badtypeok = False, section = None, morevars = None)
Alias for self.conf.getstr for section self.section.
Parameters
opt the option name
section Optional: the section. Default: self.section
default if specified and not None, then the default is returned if an option has no value or the section does not exist
badtypeok is True, and the conversion fails, and a default is specified, the default will be returned.
morevars dict of more variables for string expansion
Definition at line 1508 of file config.py.
Referenced by produtil.config.ProdTask.__init__(), and produtil.config.ProdTask.confint().
confstrinterp()
def produtil.config.ProdTask.confstrinterp (self, string, section = None, kwargs)
Alias for self.icstr for backward compatibility.
Parameters
string the string to expand
section Optional: the section in which to expand it. Default: self.section.
kwargs more arguments for string substitution
Definition at line 1566 of file config.py.
conftimestrinterp()
def produtil.config.ProdTask.conftimestrinterp (self, string, ftime, atime = None, section = None, kwargs)
Alias for self.timestr for backward comaptibility.
Parameters
string the string to expand
ftime the forecast time
atime Optional: the analysis time. Default: self.conf.cycle
section Optional: the section in which to expand it. Default: self.section.
kwargs more arguments for string substitution
Definition at line 1575 of file config.py.
Referenced by produtil.config.ProdTask.confstrinterp().
get_outdir()
def produtil.config.ProdTask.get_outdir (self)
Gets the directory that should receive output data.
This is in the "outdir" metadata value.
Definition at line 1426 of file config.py.
get_workdir()
def produtil.config.ProdTask.get_workdir (self)
Returns the directory the class should work in, as set by the "workdir" metadata value.
Definition at line 1408 of file config.py.
getconf()
def produtil.config.ProdTask.getconf (self)
Returns this ProdTask's produtil.config.ProdConfig object.
Definition at line 1657 of file config.py.
getdir()
def produtil.config.ProdTask.getdir (self, opt, default = None, morevars = None)
Alias for produtil.config.ProdConfig.get() for the "dir" section.
Parameters
opt the option name
default Optional: default value if nothing is found.
morevars Optional: more variables for string substitution
Definition at line 1643 of file config.py.
Referenced by produtil.config.ProdTask.__init__(), produtil.config.ProdTask.get_outdir(), and produtil.config.ProdTask.get_workdir().
getexe()
def produtil.config.ProdTask.getexe (self, opt, default = None, morevars = None)
Alias for produtil.config.ProdConfig.get() for the "exe" section.
Parameters
opt the option name
default Optional: default value if nothing is found.
morevars Optional: more variables for string substitution
Definition at line 1650 of file config.py.
getsection()
def produtil.config.ProdTask.getsection (self)
Returns this ProdTask's section name in the ProdConfig.
Definition at line 1665 of file config.py.
icstr()
def produtil.config.ProdTask.icstr (self, string, section = None, kwargs)
Expands a string in the given conf section.
Given a string, expand it as if it was a value in the specified conf section. Makes this objects tcvitals, if any, available via the "vit" variable while interpolating strings.
Parameters
string the string to expand
section Optional: the section in which to expand it. Default: self.section.
kwargs more arguments for string substitution
Definition at line 1598 of file config.py.
Referenced by produtil.config.ProdTask.confstrinterp().
log()
def produtil.config.ProdTask.log (self, subdom = None)
Obtain a logging domain.
Creates or returns a logging.Logger. If subdom is None or unspecified, returns a cached logger for this task's logging domain. Otherwise, returns a logger for the specified subdomain of this task's logging domain.
Parameters
subdom Optional: the desired logging domain
Definition at line 1673 of file config.py.
set_outdir()
def produtil.config.ProdTask.set_outdir (self, val)
Sets the directory that should receive output data.
Sets the "outdir" metadata value.
Parameters
val the new output directory
Definition at line 1434 of file config.py.
set_workdir()
def produtil.config.ProdTask.set_workdir (self, val)
Sets the directory the class should work in.
This sets the "workdir" metadata value.
Parameters
val the new work directory
Definition at line 1416 of file config.py.
taskvars()
def produtil.config.ProdTask.taskvars (self)
The dict of object-local values used for string substitution.
Definition at line 1489 of file config.py.
timestr()
def produtil.config.ProdTask.timestr (self, string, ftime = None, atime = None, section = None, kwargs)
Expands a string in the given conf section, including time vars.
Expands a string in the given conf section (default: self.section), and includes forecast and analysis time (default: conf.cycle) information in the variables that can be expanded. The mandatory ftime argument is the forecast time which will be used to expand values such as fHH, fYMDH, etc. The optional atime will be used to expand aHH, aYMDH, etc., and the two will be used together for forecast minus analysis fields like fahr. See produtil.config.timestrinterp for details
As with self.icstr, this class's vitals are available via the "vit" variable while interpolating strings.
Parameters
string the string to expand
ftime the forecast time
atime Optional: the analysis time. Default: self.conf.cycle
section Optional: the section in which to expand it. Default: self.section.
kwargs more arguments for string substitution
Definition at line 1614 of file config.py.
Referenced by produtil.config.ProdTask.conftimestrinterp().
tvdel()
def produtil.config.ProdTask.tvdel (self, opt)
Deletes an object-local value set by tvset.
Parameters
opt the name of the taskvar to delete
Definition at line 1461 of file config.py.
tvget()
def produtil.config.ProdTask.tvget (self, opt)
Gets a taskvar's value.
Returns the value of an object-local (taskvar) option set by tvset.
Parameters
opt the taskvar whose value should be returned
Definition at line 1467 of file config.py.
tvhave()
def produtil.config.ProdTask.tvhave (self, opt = UNSPECIFIED)
Is a taskvar set?
If an option is specified, determines if the given option has an object-local (taskvar) value. If no option is specified, returns True if ANY object-local values (taskvars) exist for any options.
Parameters
opt Optional: the name of the taskvar being checked.
Definition at line 1475 of file config.py.
tvset()
def produtil.config.ProdTask.tvset (self, opt, val)
Sets a taskvar option's value.
Sets an object-local (taskvar) value for option "opt" to value "val". This will override config settings from the ProdConfig object. These are sent into the taskvars= parameter to the various ProdConfig member functions (hence the "tv" in "tvset").
Parameters
opt the name of the taskvar
val the string value of the option
Definition at line 1446 of file config.py.
Referenced by produtil.config.ProdTask.__init__().
Property Documentation
conf
produtil.config.ProdTask.conf static
Initial value:
= property(getconf,None,None,
                  )
This ProdTask's produtil.config.ProdConfig object.
Definition at line 1663 of file config.py.
outdir
produtil.config.ProdTask.outdir static
Initial value:
= property(get_outdir,set_outdir,None,
        )
The directory in which this task should deliver its final output.
Note that changing this will NOT update products already in the database.
Definition at line 1443 of file config.py.
section
produtil.config.ProdTask.section static
Initial value:
= property(getsection,None,None,
        )
The confsection in self.section for this ProdTask (read-only)
Definition at line 1670 of file config.py.
Referenced by produtil.config.ProdTask.confraw().
workdir
produtil.config.ProdTask.workdir static
Initial value:
= property(get_workdir,set_workdir,None,
        )
The directory in which this task should be run.
Definition at line 1423 of file config.py.
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/produtil/config.py