METplus: produtil.locking.LockFile Class Reference
produtil.locking.LockFile Class Reference
Automates locking of a lockfile.
Detailed Description
Automates locking of a lockfile.
with LockFile("/path/to/lock.file"):
    ... do things while file is locked ...
...file is no longer locked.
Definition at line 66 of file locking.py.
Public Member Functions
def __hash__ (self)
Return a hash of this object.
def __eq__ (self, other)
Is this lock the same as that lock?
def __init__ (self, filename, until=None, logger=None, max_tries=10, sleep_time=3, first_warn=0, giveup_quiet=False)
Creates an object that will lock the specified file.
def acquire_impl (self)
Internal implementation function; do not call directly.
def release_impl (self)
Internal implementation function; do not call directly.
def acquire (self)
Acquire the lock.
def release (self)
Release the lock.
def __enter__ (self)
Calls self.acquire() to acquire the lock.
def __exit__ (self, etype, evalue, etraceback)
Calls self.release() to release the lock.
Constructor & Destructor Documentation
__init__()
def produtil.locking.LockFile.__init__ (self, filename, until = None, logger = None, max_tries = 10, sleep_time = 3, first_warn = 0, giveup_quiet = False)
Creates an object that will lock the specified file.
Parameters
filename the file to lock
until Unused.
logger Optional: a logging.Logger to log messages
max_tries Optional: maximum tries before giving up on locking
sleep_time Optional: approximate sleep time between locking attempts.
first_warn Optional: first locking failure at which to write warnings to the logger
giveup_quiet Optional: if True, do not log the final failure to lock
Definition at line 80 of file locking.py.
Member Function Documentation
__enter__()
def produtil.locking.LockFile.__enter__ (self)
Calls self.acquire() to acquire the lock.
Definition at line 149 of file locking.py.
__exit__()
def produtil.locking.LockFile.__exit__ (self, etype, evalue, etraceback)
Calls self.release() to release the lock.
Parameters
etype,evalue,etraceback Exception information.
Definition at line 153 of file locking.py.
__hash__()
def produtil.locking.LockFile.__hash__ (self)
Return a hash of this object.
Definition at line 74 of file locking.py.
acquire()
def produtil.locking.LockFile.acquire (self)
Acquire the lock.
Will try for a while, and will raise LockHeld when giving up.
Definition at line 131 of file locking.py.
Referenced by produtil.locking.LockFile.__enter__().
acquire_impl()
def produtil.locking.LockFile.acquire_impl (self)
Internal implementation function; do not call directly.
Does the actual work of acquiring the lock, without retries, logging or sleeping. Will raise LockHeld if it cannot acquire the lock.
Definition at line 103 of file locking.py.
Referenced by produtil.locking.LockFile.acquire().
release()
def produtil.locking.LockFile.release (self)
Release the lock.
May raise exceptions on unexpected failures.
Definition at line 138 of file locking.py.
Referenced by produtil.locking.LockFile.__exit__().
release_impl()
def produtil.locking.LockFile.release_impl (self)
Internal implementation function; do not call directly.
Does the actual work of releasing the lock, without retries, logging or sleeping.
Definition at line 123 of file locking.py.
Referenced by produtil.locking.LockFile.release().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/produtil/locking.py