METplus: extract_tiles_wrapper.ExtractTilesWrapper Class Reference
extract_tiles_wrapper.ExtractTilesWrapper Class Reference
Takes tc-pairs data and regrids paired data to an n x m grid as specified in the config file.
Detailed Description
Takes tc-pairs data and regrids paired data to an n x m grid as specified in the config file.
Definition at line 33 of file extract_tiles_wrapper.py.
Public Member Functions
def __init__ (self, config, logger)
def run_at_time (self, input_dict)
Loops over loop strings and calls run_at_time_loop_string() to process data Args: input_dict: Time dictionary Returns: None.
def run_at_time_loop_string (self, input_dict)
Get TC-paris data then regrid tiles centered on the storm.
def tc_files_exist (self)
def do_filtering (self, cur_init, filter_name)
def create_results_files (self, sorted_storm_ids, cur_init, filter_name, tmp_dir)
Public Member Functions inherited from command_builder.CommandBuilder
def __init__ (self, config, logger)
def create_c_dict (self)
def clear (self)
Unset class variables to prepare for next run time.
def log_error (self, error_string)
def set_user_environment (self, time_info=None)
Set environment variables defined in [user_env_vars] section of config.
def add_common_envs (self, time_info=None)
def print_all_envs (self)
def handle_window_once (self, c_dict, dtype, edge, app_name)
Check and set window dictionary variables like OBS_WINDOW_BEG or FCST_FILE_WINDW_END Args:
def handle_window_variables (self, c_dict, app_name, dtypes=['FCST', OBS)
Handle all window config variables like [FCST/OBS]_<app_name>_WINDOW_[BEGIN/END] and [FCST/OBS]_<app_name>_FILE_WINDOW_[BEGIN/END] Args:
def set_output_path (self, outpath)
Split path into directory and filename then save both.
def get_output_path (self)
Combine output directory and filename then return result.
def add_env_var (self, key, name)
Sets an environment variable so that the MET application can reference it in the parameter file or the application itself.
def print_env (self)
Print all environment variables set for this application.
def print_env_copy (self, var_list=None)
def get_env_copy (self, var_list=None)
Print list of environment variables that can be easily copied into terminal.
def print_env_item (self, item)
Print single environment variable in the log file.
def print_user_env_items (self)
Prints user environment variables in the log file.
def handle_fcst_and_obs_field (self, gen_name, fcst_name, obs_name, default=None, sec='config')
Handles config variables that have fcst/obs versions or a generic variable to handle both, i.e.
def find_model (self, time_info, var_info, mandatory=True, return_list=False)
Finds the model file to compare Args:
def find_obs (self, time_info, var_info, mandatory=True, return_list=False)
Finds the observation file to compare Args:
def find_data (self, time_info, var_info, data_type, mandatory=True, return_list=False)
Finds the data file to compare Args:
def find_exact_file (self, level, data_type, time_info, mandatory=True, return_list=False)
def find_file_in_window (self, level, data_type, time_info, mandatory=True, return_list=False)
def write_list_file (self, filename, file_list)
Writes a file containing a list of filenames to the staging dir.
def find_and_check_output_file (self, time_info)
Look for expected output file.
def format_list_string (self, list_string)
Add quotation marks around each comma separated item in the string.
def check_for_externals (self)
def check_for_gempak (self)
def check_gempaktocf (self, gempaktocf_jar)
def get_output_prefix (self, time_info)
def check_for_python_embedding (self, input_type, var_info)
Check if field name of given input type is a python script.
def get_command (self)
Builds the command to run the MET application string.
def build_and_run_command (self)
def build (self)
Build and run command.
def run_at_time (self, input_dict)
Used to output error and exit if wrapper is attemped to be run with LOOP_ORDER = times and the run_at_time method is not implemented.
def run_all_times (self)
Loop over time range specified in conf file and call METplus wrapper for each time.
Public Attributes
app_name
tc_pairs_dir
overwrite_flag
addl_filter_opts
filtered_out_dir
tc_stat_exe
Public Attributes inherited from command_builder.CommandBuilder
isOK
errors
logger
config
env_list
debug
args
input_dir
infiles
outdir
outfile
param
env
c_dict
cmdrunner
Member Function Documentation
create_results_files()
def extract_tiles_wrapper.ExtractTilesWrapper.create_results_files (self, sorted_storm_ids, cur_init, filter_name, tmp_dir)
Create the tmp files that contain filtered results- one tmp file per storm, then
    invoke retrieve_and_regrid to create the final output as netCDF forecast and analysis (obs)
    files.
    Args:
@param sorted_storm_ids:
@param cur_init: The current init time of interest
@param filter_name: The full file name of the filter file generated by tc stat
@param tmp_dir: The location of the tmp directory where these tmp files will be saved
    Return:
     0 if successful in creating the tmp files (one per storm) in the tmp_dir
Definition at line 190 of file extract_tiles_wrapper.py.
Referenced by extract_tiles_wrapper.ExtractTilesWrapper.run_at_time_loop_string().
do_filtering()
def extract_tiles_wrapper.ExtractTilesWrapper.do_filtering (self, cur_init, filter_name)
run TC_STAT because the filter output file hasn't yet been created
    by the MET tc stat tool.
    Args:
@param cur_init:  The current init time of interest
@param filter_name: The full filename of the file that will contain filtered results generated
                    by the MET tool tc stat.
    Return:
0 if MET tc stat tool completed successfully (which will
create a filter_name file (which was defined/created in run_at_time()
in the output directory).
Definition at line 159 of file extract_tiles_wrapper.py.
Referenced by extract_tiles_wrapper.ExtractTilesWrapper.run_at_time_loop_string().
run_at_time_loop_string()
def extract_tiles_wrapper.ExtractTilesWrapper.run_at_time_loop_string (self, input_dict)
Get TC-paris data then regrid tiles centered on the storm.
Get TC-pairs track data and GFS model data, do any necessary processing then regrid the forecast and analysis files to a 30 x 30 degree tile centered on the storm. Args: input_dict: Time dictionary Returns:
None: invokes regrid_data_plane to create a netCDF file from two
extratropical storm track files.
Definition at line 72 of file extract_tiles_wrapper.py.
Referenced by extract_tiles_wrapper.ExtractTilesWrapper.run_at_time(), mtd_wrapper.MTDWrapper.run_at_time(), and tc_pairs_wrapper.TCPairsWrapper.run_at_time().
tc_files_exist()
def extract_tiles_wrapper.ExtractTilesWrapper.tc_files_exist (self)
Check that there are tc_pairs data files (.tcst) which are needed as input
    to the extract tiles wrapper
    Args:
    Return:
True if .tcst files exist, False otherwise
Definition at line 141 of file extract_tiles_wrapper.py.
Referenced by extract_tiles_wrapper.ExtractTilesWrapper.run_at_time_loop_string().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/extract_tiles_wrapper.py