METplus: ascii2nc_wrapper.ASCII2NCWrapper Class Reference
ascii2nc_wrapper.ASCII2NCWrapper Class Reference
Detailed Description
Definition at line 29 of file ascii2nc_wrapper.py.
Public Member Functions
def __init__ (self, config, logger)
def create_c_dict (self)
def set_environment_variables (self, time_info)
Set environment variables that will be read by the MET config file.
def get_command (self)
def run_at_time (self, input_dict)
Runs the MET application for a given run time.
def run_at_time_once (self, time_info)
Process runtime and try to build command to run ascii2nc Args:
def find_input_files (self, time_info)
def set_command_line_arguments (self, time_info)
Public Member Functions inherited from command_builder.CommandBuilder
def __init__ (self, config, logger)
def create_c_dict (self)
def clear (self)
Unset class variables to prepare for next run time.
def log_error (self, error_string)
def set_user_environment (self, time_info=None)
Set environment variables defined in [user_env_vars] section of config.
def add_common_envs (self, time_info=None)
def print_all_envs (self)
def handle_window_once (self, c_dict, dtype, edge, app_name)
Check and set window dictionary variables like OBS_WINDOW_BEG or FCST_FILE_WINDW_END Args:
def handle_window_variables (self, c_dict, app_name, dtypes=['FCST', OBS)
Handle all window config variables like [FCST/OBS]_<app_name>_WINDOW_[BEGIN/END] and [FCST/OBS]_<app_name>_FILE_WINDOW_[BEGIN/END] Args:
def set_output_path (self, outpath)
Split path into directory and filename then save both.
def get_output_path (self)
Combine output directory and filename then return result.
def add_env_var (self, key, name)
Sets an environment variable so that the MET application can reference it in the parameter file or the application itself.
def print_env (self)
Print all environment variables set for this application.
def print_env_copy (self, var_list=None)
def get_env_copy (self, var_list=None)
Print list of environment variables that can be easily copied into terminal.
def print_env_item (self, item)
Print single environment variable in the log file.
def print_user_env_items (self)
Prints user environment variables in the log file.
def handle_fcst_and_obs_field (self, gen_name, fcst_name, obs_name, default=None, sec='config')
Handles config variables that have fcst/obs versions or a generic variable to handle both, i.e.
def find_model (self, time_info, var_info, mandatory=True, return_list=False)
Finds the model file to compare Args:
def find_obs (self, time_info, var_info, mandatory=True, return_list=False)
Finds the observation file to compare Args:
def find_data (self, time_info, var_info, data_type, mandatory=True, return_list=False)
Finds the data file to compare Args:
def find_exact_file (self, level, data_type, time_info, mandatory=True, return_list=False)
def find_file_in_window (self, level, data_type, time_info, mandatory=True, return_list=False)
def write_list_file (self, filename, file_list)
Writes a file containing a list of filenames to the staging dir.
def find_and_check_output_file (self, time_info)
Look for expected output file.
def format_list_string (self, list_string)
Add quotation marks around each comma separated item in the string.
def check_for_externals (self)
def check_for_gempak (self)
def check_gempaktocf (self, gempaktocf_jar)
def get_output_prefix (self, time_info)
def check_for_python_embedding (self, input_type, var_info)
Check if field name of given input type is a python script.
def get_command (self)
Builds the command to run the MET application string.
def build_and_run_command (self)
def build (self)
Build and run command.
def run_at_time (self, input_dict)
Used to output error and exit if wrapper is attemped to be run with LOOP_ORDER = times and the run_at_time method is not implemented.
def run_all_times (self)
Loop over time range specified in conf file and call METplus wrapper for each time.
Public Attributes
app_name
app_path
outfile
Public Attributes inherited from command_builder.CommandBuilder
isOK
errors
logger
config
env_list
debug
args
input_dir
infiles
outdir
outfile
param
env
c_dict
cmdrunner
Member Function Documentation
run_at_time()
def ascii2nc_wrapper.ASCII2NCWrapper.run_at_time (self, input_dict)
Runs the MET application for a given run time.
This function loops over the list of forecast leads and runs the application for each. Args:
Parameters
input_dict dictionary containing timing information
Definition at line 174 of file ascii2nc_wrapper.py.
Referenced by tc_pairs_wrapper.TCPairsWrapper.run_all_times(), and series_analysis_wrapper.SeriesAnalysisWrapper.run_all_times().
run_at_time_once()
def ascii2nc_wrapper.ASCII2NCWrapper.run_at_time_once (self, time_info)
Process runtime and try to build command to run ascii2nc Args:
Parameters
time_info dictionary containing timing information
Definition at line 195 of file ascii2nc_wrapper.py.
Referenced by reformat_gridded_wrapper.ReformatGriddedWrapper.run_at_time(), gempak_to_cf_wrapper.GempakToCFWrapper.run_at_time(), compare_gridded_wrapper.CompareGriddedWrapper.run_at_time(), ascii2nc_wrapper.ASCII2NCWrapper.run_at_time(), and pb2nc_wrapper.PB2NCWrapper.run_at_time().
set_environment_variables()
def ascii2nc_wrapper.ASCII2NCWrapper.set_environment_variables (self, time_info)
Set environment variables that will be read by the MET config file.
Reformat as needed. Print list of variables that were set and their values. Args:
Parameters
time_info dictionary containing timing info from current run
Definition at line 103 of file ascii2nc_wrapper.py.
Referenced by ensemble_stat_wrapper.EnsembleStatWrapper.process_fields(), compare_gridded_wrapper.CompareGriddedWrapper.process_fields(), mode_wrapper.MODEWrapper.process_fields_one_thresh(), mtd_wrapper.MTDWrapper.process_fields_one_thresh(), tc_pairs_wrapper.TCPairsWrapper.run_all_times(), series_analysis_wrapper.SeriesAnalysisWrapper.run_at_time(), tc_pairs_wrapper.TCPairsWrapper.run_at_time_loop_string(), ascii2nc_wrapper.ASCII2NCWrapper.run_at_time_once(), and pb2nc_wrapper.PB2NCWrapper.run_at_time_once().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/ascii2nc_wrapper.py