METplus: confdoc.override Class Reference
confdoc.override Class Reference
Subclass of docbase for documenting files that override the base configuration.
Detailed Description
Subclass of docbase for documenting files that override the base configuration.
Definition at line 355 of file confdoc.py.
Public Member Functions
def __init__ (self, basename, parent, filepart=None, replace=False)
Class override constructor.
def secanch (self, section, where=None)
Returns the anchor for the specified section.
def optanch (self, section, option, where=None)
Returns the anchor for a specified section and option.
def section_inc (self, section, inc)
Sets the @inc list for a conf section.
def file_block (self, basename, brief, detail)
Adds a documentation block that is not associated with any section or option.
def add_section (self, section, brief, detail, replace=True)
Adds documentation for a conf section.
def add_option (self, section, option, ivalue, brief, detail, basename=None, replace=True)
Adds documentation for an option in a conf section.
def find_optbrief (self, section, option)
Finds the brief documentation for a section.
def find_secbrief (self, section)
Finds the brief documentation for a section.
def find_secdoc (self, section, detail)
Finds the brief and detailed documentation for a section.
def print_subdoc (self, s)
Prints the documentation to the specified stream.
def print_sec_opt (self, s)
Prints the section and option part of the documentation to the given stream.
Public Member Functions inherited from confdoc.docbase
def __init__ (self)
docbase constructor
def set_subdoc (self, basename, doc)
Sets the documentation object that will contain file-specific information for the given file.
def fileanch (self, basename)
Returns the anchor for a configuration file.
def secanch (self, section, where='sec')
Returns the anchor for a specified section.
def optanch (self, section, option, where='sec')
Returns the anchor for a specified option.
def make_brief (self, detail)
Given a detailed description for something that has no brief description, return the brief description.
def add_section (self, section, brief, detail, replace=None)
Adds documentation for a conf section.
def section_inc (self, section, inc)
Sets the @inc list for a conf section.
def file_block (self, basename, brief, detail)
Adds a documentation block that is not associated with any section or option.
def add_option (self, section, option, ivalue, brief, detail, basename=None, replace=None)
Adds documentation for an option in a conf section.
def print_doc (self, s)
Writes Doxygen documentation to the stream "s" which is assumed to be a io.StringIO.
Protected Member Functions
def _secsec (self, section, brief, detail)
Generates the contents of the documentation section that documents the specified conf section.
Additional Inherited Members
Public Attributes inherited from confdoc.docbase
sections
Mapping of section name to description.
secref
Mapping from section name to anchor name.
secrefset
secfile
Mapping from doxified filename to list of sections in that file.
secinc
Mapping from section name to the list of sections that are @inc included by that section.
seclist
List of section names, in the order they were first seen.
options
Mapping from option anchor name to the description of the option.
optbrief
Mapping from option anchor to the option's brief description.
secbrief
Mapping from section name to the section's brief description.
fileset
filelist
blocks
Mapping from file basename to the list of documentation blocks in that file that were not associated with any section or option.
Constructor & Destructor Documentation
__init__()
def confdoc.override.__init__ (self, basename, parent, filepart = None, replace = False)
Class override constructor.
Parameters
basename The file basename
parent The parent docbase object that documents this group of conf files, or all conf options.
filepart The modified filename for anchors. This should be the basename with "." replaced by "_".
replace If True, replace existing documentation when new values are found, otherwise ignore new docs
Definition at line 358 of file confdoc.py.
Member Function Documentation
_secsec()
def confdoc.override._secsec (self, section, brief, detail) protected
Generates the contents of the documentation section that documents the specified conf section.
Parameters
section the conf section name
brief the brief documentation
detail the detailed documentation
Returns
the section text
Definition at line 398 of file confdoc.py.
add_option()
def confdoc.override.add_option (self, section, option, ivalue, brief, detail, basename = None, replace = True)
Adds documentation for an option in a conf section.
Parameters
section The conf section name
option The name of the option in that section
ivalue A shortened form of the option value
brief The brief documentation
detail The detailed documentation
basename The file basename
replace If True, any existing documentation is replaced. Otherwise, it is ignored.
Definition at line 440 of file confdoc.py.
Referenced by confdoc.override.add_section().
add_section()
def confdoc.override.add_section (self, section, brief, detail, replace = True)
Adds documentation for a conf section.
Parameters
section The conf section name
brief The brief documentation
detail The detailed documentation or None
replace If True, any existing documentation is replaced. Otherwise, it is ignored.
Definition at line 428 of file confdoc.py.
file_block()
def confdoc.override.file_block (self, basename, brief, detail)
Adds a documentation block that is not associated with any section or option.
Parameters
basename the file that contains the block
brief the brief documentation
detail the detailed documentation
Definition at line 419 of file confdoc.py.
find_optbrief()
def confdoc.override.find_optbrief (self, section, option)
Finds the brief documentation for a section.
Checks first this documentation object, and then the parent, searching for something that has documentation for the option.
Parameters
section The conf section name
option The name of the option in that section
Definition at line 456 of file confdoc.py.
Referenced by confdoc.override.print_sec_opt().
find_secbrief()
def confdoc.override.find_secbrief (self, section)
Finds the brief documentation for a section.
Checks first this documentation object, and then the parent, searching for something that has documentation for a section.
Parameters
section The conf section name
Definition at line 471 of file confdoc.py.
Referenced by confdoc.override.print_sec_opt().
find_secdoc()
def confdoc.override.find_secdoc (self, section, detail)
Finds the brief and detailed documentation for a section.
Checks first this documentation object, and then the parent, searching for something that has documentation for a section.
Parameters
section The conf section name
detail detailed documentation, if available, and None otherwise
Returns
A tuple (brief,detail) containing any documentation found.
Definition at line 486 of file confdoc.py.
Referenced by confdoc.override._secsec().
optanch()
def confdoc.override.optanch (self, section, option, where = None)
Returns the anchor for a specified section and option.
Parameters
option the option of interest
section the section that contains the option
Optional the conf file basename
Definition at line 387 of file confdoc.py.
Referenced by confdoc.override.find_optbrief().
print_sec_opt()
def confdoc.override.print_sec_opt (self, s)
Prints the section and option part of the documentation to the given stream.
Parameters
s The stream, ideally a io.StringIO.
Definition at line 514 of file confdoc.py.
Referenced by confdoc.override.print_subdoc(), and confdoc.coredoc.print_subdoc().
print_subdoc()
def confdoc.override.print_subdoc (self, s)
Prints the documentation to the specified stream.
Parameters
s The stream, ideally a io.StringIO.
Definition at line 508 of file confdoc.py.
secanch()
def confdoc.override.secanch (self, section, where = None)
Returns the anchor for the specified section.
Parameters
section The conf section name
where Optional: the conf file basename.
Definition at line 378 of file confdoc.py.
section_inc()
def confdoc.override.section_inc (self, section, inc)
Sets the @inc list for a conf section.
Parameters
section The conf section name
inc The contents of the @inc= option
Definition at line 411 of file confdoc.py.
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/confdoc.py