METplus: series_by_lead_wrapper.SeriesByLeadWrapper Class Reference
series_by_lead_wrapper.SeriesByLeadWrapper Class Reference
SeriesByLeadWrapper performs series analysis of paired data based on lead time and generates plots for each requested variable and statistic, as specified in a configuration/parameter file.
Detailed Description
SeriesByLeadWrapper performs series analysis of paired data based on lead time and generates plots for each requested variable and statistic, as specified in a configuration/parameter file.
Definition at line 38 of file series_by_lead_wrapper.py.
Public Member Functions
def __init__ (self, config, logger)
def create_c_dict (self)
def get_lead_sequences (self)
def run_all_times (self)
Perform a series analysis of extra tropical cyclone paired data based on lead time (forecast hour) This requires invoking the MET run_series_analysis binary, followed by generating graphics that are recognized by the MET viewer using the plot_data_plane and converting to postscript.
def filter_with_tc_stat (self, tile_dir, init_times)
Perform optional filtering using MET tc_stat.
def perform_series_for_fhr_groups (self, tile_dir)
Series analysis for groups based on forecast hours.
def perform_series_for_all_fhrs (self, tile_dir)
Performs a series analysis by lead time, based on a range and increment of forecast hours.
def get_nseries (self, do_fhr_by_range, nc_var_file)
Determine the number of series for this lead time and its associated variable via calculating the max series_cnt_TOTAL value, maximum.
def get_netcdf_min_max (self, do_fhr_by_range, nc_var_files, cur_stat)
Determine the min and max for all lead times for each statistic and variable pairing.
def retrieve_nc_files (self, do_fhr_by_range)
Retrieve all the netCDF files created by MET series_analysis.
def retrieve_fhr_tiles (self, tile_list, type_regex)
Retrieves only the gridded tile files that correspond to the type.
def find_matching_tile (self, fcst_file, anly_tiles)
Find the corresponding ANLY 30x30 tile file to the fcst tile file.
def generate_plots (self, do_fhr_by_range)
Generate the plots and animation GIFs for the series analysis results.
def create_animated_gifs (self, do_fhr_by_range)
Creates the animated GIF files from the .png files created in generate_plots().
def apply_series_filters (self, tile_dir, init_times, series_output_dir, filter_opts, staging_dir)
Apply filter options, as specified in the param/config file.
Public Member Functions inherited from command_builder.CommandBuilder
def __init__ (self, config, logger)
def create_c_dict (self)
def clear (self)
Unset class variables to prepare for next run time.
def log_error (self, error_string)
def set_user_environment (self, time_info=None)
Set environment variables defined in [user_env_vars] section of config.
def add_common_envs (self, time_info=None)
def print_all_envs (self)
def handle_window_once (self, c_dict, dtype, edge, app_name)
Check and set window dictionary variables like OBS_WINDOW_BEG or FCST_FILE_WINDW_END Args:
def handle_window_variables (self, c_dict, app_name, dtypes=['FCST', OBS)
Handle all window config variables like [FCST/OBS]_<app_name>_WINDOW_[BEGIN/END] and [FCST/OBS]_<app_name>_FILE_WINDOW_[BEGIN/END] Args:
def set_output_path (self, outpath)
Split path into directory and filename then save both.
def get_output_path (self)
Combine output directory and filename then return result.
def add_env_var (self, key, name)
Sets an environment variable so that the MET application can reference it in the parameter file or the application itself.
def print_env (self)
Print all environment variables set for this application.
def print_env_copy (self, var_list=None)
def get_env_copy (self, var_list=None)
Print list of environment variables that can be easily copied into terminal.
def print_env_item (self, item)
Print single environment variable in the log file.
def print_user_env_items (self)
Prints user environment variables in the log file.
def handle_fcst_and_obs_field (self, gen_name, fcst_name, obs_name, default=None, sec='config')
Handles config variables that have fcst/obs versions or a generic variable to handle both, i.e.
def find_model (self, time_info, var_info, mandatory=True, return_list=False)
Finds the model file to compare Args:
def find_obs (self, time_info, var_info, mandatory=True, return_list=False)
Finds the observation file to compare Args:
def find_data (self, time_info, var_info, data_type, mandatory=True, return_list=False)
Finds the data file to compare Args:
def find_exact_file (self, level, data_type, time_info, mandatory=True, return_list=False)
def find_file_in_window (self, level, data_type, time_info, mandatory=True, return_list=False)
def write_list_file (self, filename, file_list)
Writes a file containing a list of filenames to the staging dir.
def find_and_check_output_file (self, time_info)
Look for expected output file.
def format_list_string (self, list_string)
Add quotation marks around each comma separated item in the string.
def check_for_externals (self)
def check_for_gempak (self)
def check_gempaktocf (self, gempaktocf_jar)
def get_output_prefix (self, time_info)
def check_for_python_embedding (self, input_type, var_info)
Check if field name of given input type is a python script.
def get_command (self)
Builds the command to run the MET application string.
def build_and_run_command (self)
def build (self)
Build and run command.
def run_at_time (self, input_dict)
Used to output error and exit if wrapper is attemped to be run with LOOP_ORDER = times and the run_at_time method is not implemented.
def run_all_times (self)
Loop over time range specified in conf file and call METplus wrapper for each time.
Static Public Member Functions
def get_var_ncfiles (do_fhr_by_range, cur_var, nc_list)
Retrieve only the netCDF files corresponding to this statistic and variable pairing.
def get_anly_or_fcst_files (filedir, file_type, filename_regex, cur_fhr)
Get all the ANLY or FCST files by walking through the directories starting at filedir.
Public Attributes
app_name
do_fhr_by_group
fhr_group_labels
stat_list
plot_data_plane_exe
convert_exe
ncap2_exe
ncdump_exe
rm_exe
isOK
series_analysis_exe
input_dir
series_lead_filtered_out_dir
series_lead_out_dir
staging_dir
background_map
series_filter_opts
fcst_ascii_regex
anly_ascii_regex
series_anly_configuration_file
fcst_tile_regex
anly_tile_regex
Public Attributes inherited from command_builder.CommandBuilder
isOK
errors
logger
config
env_list
debug
args
input_dir
infiles
outdir
outfile
param
env
c_dict
cmdrunner
Member Function Documentation
apply_series_filters()
def series_by_lead_wrapper.SeriesByLeadWrapper.apply_series_filters (self, tile_dir, init_times, series_output_dir, filter_opts, staging_dir)
Apply filter options, as specified in the param/config file.
Args:
Parameters
tile_dir Directory where input data files reside. e.g. data which we will be applying our filter criteria.
init_times List of init times that define the input data.
series_output_dir The directory where the filter results will be stored.
filter_opts The filter options to apply
staging_dir The temporary directory where intermediate files are saved. Returns: None
Definition at line 1314 of file series_by_lead_wrapper.py.
Referenced by series_by_lead_wrapper.SeriesByLeadWrapper.create_animated_gifs(), and series_by_lead_wrapper.SeriesByLeadWrapper.filter_with_tc_stat().
create_animated_gifs()
def series_by_lead_wrapper.SeriesByLeadWrapper.create_animated_gifs (self, do_fhr_by_range)
Creates the animated GIF files from the .png files created in generate_plots().
Args:
Parameters
do_fhr_by_range The boolean flag indicating whether series analysis was performed on the entire range (True) or on groups of forecast hours (False). Returns:
Definition at line 1222 of file series_by_lead_wrapper.py.
Referenced by series_by_lead_wrapper.SeriesByLeadWrapper.run_all_times().
filter_with_tc_stat()
def series_by_lead_wrapper.SeriesByLeadWrapper.filter_with_tc_stat (self, tile_dir, init_times)
Perform optional filtering using MET tc_stat.
Args:
Parameters
tile_dir The directory where the input data resides.
init_times A list of init times under which series filters will be applied. Returns: filter_tile_dir: A directory of the resulting files from applying the filter criteria (as specified in the param/ config file).
Definition at line 218 of file series_by_lead_wrapper.py.
Referenced by series_by_lead_wrapper.SeriesByLeadWrapper.run_all_times().
find_matching_tile()
def series_by_lead_wrapper.SeriesByLeadWrapper.find_matching_tile (self, fcst_file, anly_tiles)
Find the corresponding ANLY 30x30 tile file to the fcst tile file.
Args:
Parameters
fcst_file : The fcst file (full path) that is used to derive the corresponding analysis file name.
anly_tiles : The list of all available 30x30 analysis tiles.
Returns: anly_from_fcst (string): The name of the analysis tile file that corresponds to the same lead time as the input fcst tile.
Definition at line 970 of file series_by_lead_wrapper.py.
generate_plots()
def series_by_lead_wrapper.SeriesByLeadWrapper.generate_plots (self, do_fhr_by_range)
Generate the plots and animation GIFs for the series analysis results.
Args:
Parameters
do_fhr_by_range The boolean flag which indicates whether series analysis is to be performed for the entire range of fhrs, (True), or by groups of fhrs (False).
Returns: None
Definition at line 1053 of file series_by_lead_wrapper.py.
Referenced by series_by_lead_wrapper.SeriesByLeadWrapper.run_all_times().
get_anly_or_fcst_files()
def series_by_lead_wrapper.SeriesByLeadWrapper.get_anly_or_fcst_files (filedir, file_type, filename_regex, cur_fhr) static
Get all the ANLY or FCST files by walking through the directories starting at filedir.
Args:
Parameters
filedir The topmost directory from which the search begins.
file_type FCST or ANLY
filename_regex The regular expression that defines the naming format of the files of interest.
cur_fhr The current forecast hour for which we need to find the corresponding file
Returns: file_paths (string): a list of filenames (with full filepath)
Definition at line 998 of file series_by_lead_wrapper.py.
Referenced by series_by_lead_wrapper.SeriesByLeadWrapper.find_matching_tile(), series_by_lead_wrapper.SeriesByLeadWrapper.perform_series_for_all_fhrs(), and series_by_lead_wrapper.SeriesByLeadWrapper.perform_series_for_fhr_groups().
get_netcdf_min_max()
def series_by_lead_wrapper.SeriesByLeadWrapper.get_netcdf_min_max (self, do_fhr_by_range, nc_var_files, cur_stat)
Determine the min and max for all lead times for each statistic and variable pairing.
Args:
Parameters
do_fhr_by_range Boolean value indicating whether series analysis was performed on a range of forecast hours (True) or on a grouping of forecast hours (False).
nc_var_files A list of the netCDF files generated by the MET series analysis tool that correspond to the variable of interest.
cur_stat The current statistic of interest: ie. RMSE, MAE, ODEV, FDEV, ME, or TOTAL.
Returns: tuple (vmin, vmax) vmin: The minimum vmax: The maximum
Definition at line 694 of file series_by_lead_wrapper.py.
Referenced by series_by_lead_wrapper.SeriesByLeadWrapper.generate_plots().
get_nseries()
def series_by_lead_wrapper.SeriesByLeadWrapper.get_nseries (self, do_fhr_by_range, nc_var_file)
Determine the number of series for this lead time and its associated variable via calculating the max series_cnt_TOTAL value, maximum.
Args:
Parameters
do_fhr_by_range Boolean value indicating whether series analysis was performed on a range of forecast hours (True) or on a "bucket" of forecast hours (False).
nc_var_file The netCDF file for a particular variable.
Returns: maximum (float): The maximum value of series_cnt_TOTAL of all the netCDF files for the variable cur_var. None: If no max value is found.
Definition at line 592 of file series_by_lead_wrapper.py.
Referenced by series_by_lead_wrapper.SeriesByLeadWrapper.generate_plots().
get_var_ncfiles()
def series_by_lead_wrapper.SeriesByLeadWrapper.get_var_ncfiles (do_fhr_by_range, cur_var, nc_list) static
Retrieve only the netCDF files corresponding to this statistic and variable pairing.
Args:
Parameters
do_fhr_by_range The boolean value indicating whether series analysis was performed on a range of forecast hours (True), or on a group of forecast hours (False)
cur_var The variable of interest.
nc_list The list of all netCDF files that were generated by the MET utility series_analysis.
Returns: var_ncfiles: A list of netCDF files that correspond to this variable.
Definition at line 852 of file series_by_lead_wrapper.py.
Referenced by series_by_lead_wrapper.SeriesByLeadWrapper.generate_plots().
perform_series_for_all_fhrs()
def series_by_lead_wrapper.SeriesByLeadWrapper.perform_series_for_all_fhrs (self, tile_dir)
Performs a series analysis by lead time, based on a range and increment of forecast hours.
Invokes the MET tool Series-analysis
Args:
Parameters
tile_dir The location of the input data (output from running ExtractTiles.py)
lead_seq List of forecast hours to process
Returns: None
Definition at line 442 of file series_by_lead_wrapper.py.
Referenced by series_by_lead_wrapper.SeriesByLeadWrapper.run_all_times().
perform_series_for_fhr_groups()
def series_by_lead_wrapper.SeriesByLeadWrapper.perform_series_for_fhr_groups (self, tile_dir)
Series analysis for groups based on forecast hours.
Args:
Parameters
tile_dir The location where input data resides. Returns: None
Definition at line 278 of file series_by_lead_wrapper.py.
Referenced by series_by_lead_wrapper.SeriesByLeadWrapper.run_all_times().
retrieve_fhr_tiles()
def series_by_lead_wrapper.SeriesByLeadWrapper.retrieve_fhr_tiles (self, tile_list, type_regex)
Retrieves only the gridded tile files that correspond to the type.
Args:
Parameters
tile_list List of tiles (full filepath).
type_regex The regex that corresponds to the tile filename for this type
Returns: fhr_tiles (string): A string of gridded tile names separated by newlines
Definition at line 937 of file series_by_lead_wrapper.py.
Referenced by series_by_lead_wrapper.SeriesByLeadWrapper.perform_series_for_all_fhrs().
retrieve_nc_files()
def series_by_lead_wrapper.SeriesByLeadWrapper.retrieve_nc_files (self, do_fhr_by_range)
Retrieve all the netCDF files created by MET series_analysis.
Args:
Parameters
do_fhr_by_range Boolean value, True if series analysis was performed on range. False otherwise. Returns: nc_list: A list of the netCDF files (full path) created when the MET series analysis binary was invoked.
Definition at line 891 of file series_by_lead_wrapper.py.
Referenced by series_by_lead_wrapper.SeriesByLeadWrapper.generate_plots().
run_all_times()
def series_by_lead_wrapper.SeriesByLeadWrapper.run_all_times (self)
Perform a series analysis of extra tropical cyclone paired data based on lead time (forecast hour) This requires invoking the MET run_series_analysis binary, followed by generating graphics that are recognized by the MET viewer using the plot_data_plane and converting to postscript.
A pre-requisite is the presence of the filter file and storm files (set to nxm degree tiles as indicated in the param/config file) the specified init and lead times.
Create the following command to satisfy MET series_analysis: series_analysis -fcst <FILTERED_OUT_DIR>/FCST_FILES_F<CUR_FHR> -obs <FILTERED_OUT_DIR>/ANLY_FILES_F<CUR_FHR> -out <OUT_DIR>/series_F<CURR_FHR_<NAME>_<LEVEL>.nc -config SeriesAnalysisConfig_by_lead Args:
Returns: None: Invokes MET series_analysis and any other MET tool to perform series analysis. Then plots are generated for the variables and statistics (as indicated in the param/config file) corresponding to each forecast lead time.
Definition at line 132 of file series_by_lead_wrapper.py.
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/series_by_lead_wrapper.py