METplus: pcp_combine_wrapper.PCPCombineWrapper Class Reference
pcp_combine_wrapper.PCPCombineWrapper Class Reference
Wraps the MET tool pcp_combine to combine or divide precipitation accumulations.
Detailed Description
Wraps the MET tool pcp_combine to combine or divide precipitation accumulations.
Definition at line 34 of file pcp_combine_wrapper.py.
Public Member Functions
def __init__ (self, config, logger)
def create_c_dict (self)
def set_fcst_or_obs_dict_items (self, d_type, c_dict)
def clear (self)
def add_input_file (self, filename, addon)
def get_dir_and_template (self, data_type, in_or_out)
def getLowestForecastFile (self, valid_time, dtype, template)
Find the lowest forecast hour that corresponds to the valid time Args:
def get_daily_file (self, time_info, accum, data_src, file_template)
Pull accumulation out of file that contains a full day of data Args:
def get_addon (self, accum_dict, search_accum, search_time)
def find_input_file (self, in_template, init_time, valid_time, search_accum, data_src)
def get_template_accum (self, accum_dict, search_time, lead, data_src)
def get_accumulation (self, time_info, accum, data_src)
Find files to combine to build the desired accumulation Args:
def get_command (self)
def run_at_time_once (self, time_info, var_info, data_src)
def setup_subtract_method (self, time_info, var_info, data_src)
Setup pcp_combine to subtract two files to build desired accumulation Args:
def setup_sum_method (self, time_info, var_info, data_src)
Setup pcp_combine to build desired accumulation based on init/valid times and accumulations Args:
def setup_add_method (self, time_info, var_info, data_src)
Setup pcp_combine to add files to build desired accumulation Args:
def setup_derive_method (self, time_info, var_info, data_src)
Setup pcp_combine to derive stats Args:
def setup_user_method (self, time_info, data_src)
Setup pcp_combine to call user defined command Args:
def build_input_accum_list (self, data_src, time_info)
Public Member Functions inherited from reformat_gridded_wrapper.ReformatGriddedWrapper
def __init__ (self, config, logger)
def run_at_time_once (self, time_info, var_info, to_run)
To be implemented by child class.
def run_at_time (self, input_dict)
Runs the MET application for a given run time.
Public Member Functions inherited from command_builder.CommandBuilder
def __init__ (self, config, logger)
def create_c_dict (self)
def clear (self)
Unset class variables to prepare for next run time.
def log_error (self, error_string)
def set_user_environment (self, time_info=None)
Set environment variables defined in [user_env_vars] section of config.
def add_common_envs (self, time_info=None)
def print_all_envs (self)
def handle_window_once (self, c_dict, dtype, edge, app_name)
Check and set window dictionary variables like OBS_WINDOW_BEG or FCST_FILE_WINDW_END Args:
def handle_window_variables (self, c_dict, app_name, dtypes=['FCST', OBS)
Handle all window config variables like [FCST/OBS]_<app_name>_WINDOW_[BEGIN/END] and [FCST/OBS]_<app_name>_FILE_WINDOW_[BEGIN/END] Args:
def set_output_path (self, outpath)
Split path into directory and filename then save both.
def get_output_path (self)
Combine output directory and filename then return result.
def add_env_var (self, key, name)
Sets an environment variable so that the MET application can reference it in the parameter file or the application itself.
def print_env (self)
Print all environment variables set for this application.
def print_env_copy (self, var_list=None)
def get_env_copy (self, var_list=None)
Print list of environment variables that can be easily copied into terminal.
def print_env_item (self, item)
Print single environment variable in the log file.
def print_user_env_items (self)
Prints user environment variables in the log file.
def handle_fcst_and_obs_field (self, gen_name, fcst_name, obs_name, default=None, sec='config')
Handles config variables that have fcst/obs versions or a generic variable to handle both, i.e.
def find_model (self, time_info, var_info, mandatory=True, return_list=False)
Finds the model file to compare Args:
def find_obs (self, time_info, var_info, mandatory=True, return_list=False)
Finds the observation file to compare Args:
def find_data (self, time_info, var_info, data_type, mandatory=True, return_list=False)
Finds the data file to compare Args:
def find_exact_file (self, level, data_type, time_info, mandatory=True, return_list=False)
def find_file_in_window (self, level, data_type, time_info, mandatory=True, return_list=False)
def write_list_file (self, filename, file_list)
Writes a file containing a list of filenames to the staging dir.
def find_and_check_output_file (self, time_info)
Look for expected output file.
def format_list_string (self, list_string)
Add quotation marks around each comma separated item in the string.
def check_for_externals (self)
def check_for_gempak (self)
def check_gempaktocf (self, gempaktocf_jar)
def get_output_prefix (self, time_info)
def check_for_python_embedding (self, input_type, var_info)
Check if field name of given input type is a python script.
def get_command (self)
Builds the command to run the MET application string.
def build_and_run_command (self)
def build (self)
Build and run command.
def run_at_time (self, input_dict)
Used to output error and exit if wrapper is attemped to be run with LOOP_ORDER = times and the run_at_time method is not implemented.
def run_all_times (self)
Loop over time range specified in conf file and call METplus wrapper for each time.
Public Attributes
app_name
app_path
inaddons
method
pcp_dir
pcp_regex
init_time
valid_time
in_accum
out_accum
field_name
field_level
output_name
name
compress
user_command
isOK
field_extra
outfile
outdir
input_dir
Public Attributes inherited from command_builder.CommandBuilder
isOK
errors
logger
config
env_list
debug
args
input_dir
infiles
outdir
outfile
param
env
c_dict
cmdrunner
Static Public Attributes
list valid_run_methods = ['ADD', 'SUM', 'SUBTRACT', 'DERIVE', 'USER_DEFINED']
Member Function Documentation
get_accumulation()
def pcp_combine_wrapper.PCPCombineWrapper.get_accumulation (self, time_info, accum, data_src)
Find files to combine to build the desired accumulation Args:
Parameters
time_info dictionary containing time information
accum desired accumulation to build
data_src type of data (FCST or OBS) bool
Returns
True if full set of files to build accumulation is found
Definition at line 408 of file pcp_combine_wrapper.py.
Referenced by pcp_combine_wrapper.PCPCombineWrapper.setup_add_method(), and pcp_combine_wrapper.PCPCombineWrapper.setup_derive_method().
get_daily_file()
def pcp_combine_wrapper.PCPCombineWrapper.get_daily_file (self, time_info, accum, data_src, file_template)
Pull accumulation out of file that contains a full day of data Args:
Parameters
time_info dictionary containing timing information
accum accumulation to extract from file
data_src type of data (FCST or OBS)
file_template filename template to search bool
Returns
True if file was added to output list, False if not
Definition at line 254 of file pcp_combine_wrapper.py.
Referenced by pcp_combine_wrapper.PCPCombineWrapper.get_accumulation().
getLowestForecastFile()
def pcp_combine_wrapper.PCPCombineWrapper.getLowestForecastFile (self, valid_time, dtype, template)
Find the lowest forecast hour that corresponds to the valid time Args:
Parameters
valid_time valid time to search
dtype data type (FCST or OBS) to get filename template string
Returns
Path to file with the lowest forecast hour
Definition at line 203 of file pcp_combine_wrapper.py.
Referenced by pcp_combine_wrapper.PCPCombineWrapper.get_daily_file().
setup_add_method()
def pcp_combine_wrapper.PCPCombineWrapper.setup_add_method (self, time_info, var_info, data_src)
Setup pcp_combine to add files to build desired accumulation Args:
Parameters
time_info dictionary containing timing information
var_info object containing variable information data_src data type (FCST or OBS) string
Returns
path to output file
Definition at line 835 of file pcp_combine_wrapper.py.
Referenced by pcp_combine_wrapper.PCPCombineWrapper.get_accumulation().
setup_derive_method()
def pcp_combine_wrapper.PCPCombineWrapper.setup_derive_method (self, time_info, var_info, data_src)
Setup pcp_combine to derive stats Args:
Parameters
time_info dictionary containing timing information
var_info object containing variable information data_src data type (FCST or OBS) string
Returns
path to output file
Definition at line 888 of file pcp_combine_wrapper.py.
Referenced by pcp_combine_wrapper.PCPCombineWrapper.get_accumulation().
setup_subtract_method()
def pcp_combine_wrapper.PCPCombineWrapper.setup_subtract_method (self, time_info, var_info, data_src)
Setup pcp_combine to subtract two files to build desired accumulation Args:
Parameters
time_info object containing timing information
var_info object containing variable information data_src data type (FCST or OBS) string
Returns
path to output file
Definition at line 647 of file pcp_combine_wrapper.py.
Referenced by pcp_combine_wrapper.PCPCombineWrapper.get_accumulation().
setup_sum_method()
def pcp_combine_wrapper.PCPCombineWrapper.setup_sum_method (self, time_info, var_info, data_src)
Setup pcp_combine to build desired accumulation based on init/valid times and accumulations Args:
Parameters
time_info object containing timing information
var_info object containing variable information data_src data type (FCST or OBS) string
Returns
path to output file
Definition at line 759 of file pcp_combine_wrapper.py.
Referenced by pcp_combine_wrapper.PCPCombineWrapper.get_accumulation().
setup_user_method()
def pcp_combine_wrapper.PCPCombineWrapper.setup_user_method (self, time_info, data_src)
Setup pcp_combine to call user defined command Args:
Parameters
time_info dictionary containing timing information
var_info object containing variable information data_src data type (FCST or OBS) string
Returns
path to output file
Definition at line 944 of file pcp_combine_wrapper.py.
Referenced by pcp_combine_wrapper.PCPCombineWrapper.get_accumulation().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/pcp_combine_wrapper.py