METplus: produtil.testing.rocoto.RocotoTask Class Reference
produtil.testing.rocoto.RocotoTask Class Reference
Represents one task in a Rocoto workflow document.
Detailed Description
Represents one task in a Rocoto workflow document.
Definition at line 27 of file rocoto.py.
Public Member Functions
def __init__ (self, name, obj, mode)
Constructor for RocotoTask.
def mode (self)
The run mode: produtil.testing.utilities.BASELINE or produtil.testing.utilities.EXECUTION.
def get_test_resources (self, con)
Get resource information for everything except cpus and time.
def get_walltime (self, con)
Gets walltime requirements from the "walltime" variable.
def get_cpu_resources (self, con)
Gets execution resources from the "execute" variable, resolving it in a rocoto_context.
def j_job_name (self, workflow, con)
Generates a path to the task's j-job.
def ex_script_name (self, workflow, con)
Generates a path to the task's ex-script.
def j_job_contents (self, workflow, con)
Generates the contents of the Task's j-job.
def ex_script_contents (self, workflow, con)
Generates the contents of the Task's ex-script.
def generate_xml (self, out, workflow, con)
Generates the Task's Rocoto XML element, writing it to a file-like stream.
Static Public Attributes
NODEFAULT = object()
Constructor & Destructor Documentation
__init__()
def produtil.testing.rocoto.RocotoTask.__init__ (self, name, obj, mode)
Constructor for RocotoTask.
Parameters
name the task name
obj a produtil.testing.parsetree.Task containing information about the task to run
mode the run mode: produtil.testing.utilities.BASELINE or produtil.testing.utilities.EXECUTION
Definition at line 29 of file rocoto.py.
Member Function Documentation
ex_script_contents()
def produtil.testing.rocoto.RocotoTask.ex_script_contents (self, workflow, con)
Generates the contents of the Task's ex-script.
Parameters
workflow the RocotoWorkflow from which to obtain the workflow name
con a produtil.testing.parsetree.Context to use when resolving variables.
Returns
the contents of the ex-script as a string
Definition at line 145 of file rocoto.py.
ex_script_name()
def produtil.testing.rocoto.RocotoTask.ex_script_name (self, workflow, con)
Generates a path to the task's ex-script.
Generates a path like "scripts/ex{workflow}_{taskname}" for the ex-script portion of the task.
Parameters
workflow the RocotoWorkflow from which to obtain the workflow name
con a produtil.testing.parsetree.Context to use when resolving variables.
Returns
the resulting path.
Definition at line 111 of file rocoto.py.
Referenced by produtil.testing.rocoto.RocotoTask.j_job_contents().
generate_xml()
def produtil.testing.rocoto.RocotoTask.generate_xml (self, out, workflow, con)
Generates the Task's Rocoto XML element, writing it to a file-like stream.
Parameters
workflow the RocotoWorkflow from which to obtain the workflow name
con a produtil.testing.parsetree.Context to use when resolving variables.
out a file-like stream in which to write
Returns
None
Definition at line 163 of file rocoto.py.
get_cpu_resources()
def produtil.testing.rocoto.RocotoTask.get_cpu_resources (self, con)
Gets execution resources from the "execute" variable, resolving it in a rocoto_context.
Parameters
con a produtil.testing.parsetree.Context to use when resolving variables.
Returns
the resulting Rocoto XML code
Definition at line 85 of file rocoto.py.
Referenced by produtil.testing.rocoto.RocotoTask.generate_xml().
get_test_resources()
def produtil.testing.rocoto.RocotoTask.get_test_resources (self, con)
Get resource information for everything except cpus and time.
Resolves the "test_size" variable to determine the test size. Then looks for "plat%rocoto%{test_size}_test_resources" for the resource information. This is expected to contain everything except cpus and runtime.
Parameters
con a produtil.testing.parsetree.Context to use when resolving variables.
Returns
the resulting Rocoto XML code
Definition at line 52 of file rocoto.py.
Referenced by produtil.testing.rocoto.RocotoTask.generate_xml().
get_walltime()
def produtil.testing.rocoto.RocotoTask.get_walltime (self, con)
Gets walltime requirements from the "walltime" variable.
Parameters
con a produtil.testing.parsetree.Context to use when resolving variables.
Returns
the resulting Rocoto XML code
Definition at line 70 of file rocoto.py.
Referenced by produtil.testing.rocoto.RocotoTask.generate_xml().
j_job_contents()
def produtil.testing.rocoto.RocotoTask.j_job_contents (self, workflow, con)
Generates the contents of the Task's j-job.
Parameters
workflow the RocotoWorkflow from which to obtain the workflow name
con a produtil.testing.parsetree.Context to use when resolving variables.
Returns
the contents of the j-job as a string
Definition at line 124 of file rocoto.py.
j_job_name()
def produtil.testing.rocoto.RocotoTask.j_job_name (self, workflow, con)
Generates a path to the task's j-job.
Generates a path like "jobs/J{WORKFLOW}_{TASKNAME}" for the j-job portion of the task.
Parameters
workflow the RocotoWorkflow from which to obtain the workflow name
con a produtil.testing.parsetree.Context to use when resolving variables.
Returns
the resulting path.
Definition at line 98 of file rocoto.py.
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/produtil/testing/rocoto.py