METplus: produtil.mpi_impl.no_mpi.Implementation Class Reference
produtil.mpi_impl.no_mpi.Implementation Class Reference
Detailed Description
Definition at line 14 of file no_mpi.py.
Public Member Functions
def __init__ (self, logger=None)
Public Member Functions inherited from produtil.mpi_impl.mpi_impl_base.ImplementationBase
def __init__ (self, logger=None)
def getmpiserial_path (self)
def setmpiserial_path (self, value)
def find_mpiserial (self, mpiserial_path, force)
def runsync (self, logger=None)
Runs the "sync" command as an exe().
def openmp (self, arg, threads)
Does nothing.
def mpirunner (self, arg, kwargs)
Raises an exception to indicate MPI is not supported.
def can_run_mpi (self)
Returns False to indicate MPI is not supported.
def make_bigexe (self, exe, kwargs)
Returns an ImmutableRunner that will run the specified program.
Static Public Member Functions
def name ()
def detect (logger=None, force=False, kwargs)
Returns a new instrance of this class to indicate that the "no MPI" implementation of MPI is always available.
Static Public Member Functions inherited from produtil.mpi_impl.mpi_impl_base.ImplementationBase
def synonyms ()
Iterates over alternative names for this MPI implementation, such as the names of other MPI implementations this class can handle.
Additional Inherited Members
Public Attributes inherited from produtil.mpi_impl.mpi_impl_base.ImplementationBase
logger
Properties inherited from produtil.mpi_impl.mpi_impl_base.ImplementationBase
mpiserial_path
Path to the mpiserial program.
Member Function Documentation
name()
def produtil.mpi_impl.no_mpi.Implementation.name () static
Returns the string "no_mpi" to indicate MPI is not available.
Definition at line 16 of file no_mpi.py.
Referenced by produtil.testing.parsetree.Build.new_empty(), produtil.testing.parsetree.Platform.new_empty(), and produtil.testing.parsetree.Test.new_empty().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/produtil/mpi_impl/no_mpi.py