METplus: stat_analysis_wrapper.StatAnalysisWrapper Class Reference
stat_analysis_wrapper.StatAnalysisWrapper Class Reference
Wrapper to the MET tool stat_analysis which is used to filter and summarize data from MET's point_stat, grid_stat, ensemble_stat, and wavelet_stat.
Detailed Description
Wrapper to the MET tool stat_analysis which is used to filter and summarize data from MET's point_stat, grid_stat, ensemble_stat, and wavelet_stat.
Definition at line 29 of file stat_analysis_wrapper.py.
Public Member Functions
def __init__ (self, config, logger)
def set_lookin_dir (self, lookindir)
def get_command (self)
def create_c_dict (self)
Create a data structure (dictionary) that contains all the values set in the configuration files that are common for stat_analysis_wrapper.py.
def list_to_str (self, list_of_values)
Turn a list of values into a single string so it can be set to an environment variable and read by the MET stat_analysis config file.
def set_lists_loop_or_group (self, config_lists_to_group_items, config_lists_to_loop_items, config_dict)
Determine whether the lists from the METplus config file should treat the items in that list as a group or items to be looped over based on user settings, the values in the list, and process being run.
def format_thresh (self, thresh)
Format thresholds for file naming.
def build_stringsub_dict (self, date_beg, date_end, date_type, lists_to_loop, lists_to_group, config_dict)
Build a dictionary with list names, dates, and commonly used identifiers to pass to string_template_substitution.
def get_output_filename (self, output_type, filename_template, filename_type, date_beg, date_end, date_type, lists_to_loop, lists_to_group, config_dict)
Create a file name for stat_analysis output.
def get_lookin_dir (self, dir_path, date_beg, date_end, date_type, lists_to_loop, lists_to_group, config_dict)
Fill in necessary information to get the path to the lookin directory to pass to stat_analysis.
def format_valid_init (self, date_beg, date_end, date_type, config_dict)
Format the valid and initialization dates and hours for the MET stat_analysis config file.
def parse_model_info (self)
Parse for model information.
def run_stat_analysis_job (self, date_beg, date_end, date_type)
This runs stat_analysis over a period of valid or initialization dates for a job defined by the user.
def filter_for_plotting (self)
Special case for running stat_analysis over a period of valid or initialization dates for a filter job, so MakePlots can be run correctly following StatAnalysis.
def run_all_times (self)
def run_at_time (self, input_dict)
Public Member Functions inherited from command_builder.CommandBuilder
def __init__ (self, config, logger)
def create_c_dict (self)
def clear (self)
Unset class variables to prepare for next run time.
def log_error (self, error_string)
def set_user_environment (self, time_info=None)
Set environment variables defined in [user_env_vars] section of config.
def add_common_envs (self, time_info=None)
def print_all_envs (self)
def handle_window_once (self, c_dict, dtype, edge, app_name)
Check and set window dictionary variables like OBS_WINDOW_BEG or FCST_FILE_WINDW_END Args:
def handle_window_variables (self, c_dict, app_name, dtypes=['FCST', OBS)
Handle all window config variables like [FCST/OBS]_<app_name>_WINDOW_[BEGIN/END] and [FCST/OBS]_<app_name>_FILE_WINDOW_[BEGIN/END] Args:
def set_output_path (self, outpath)
Split path into directory and filename then save both.
def get_output_path (self)
Combine output directory and filename then return result.
def add_env_var (self, key, name)
Sets an environment variable so that the MET application can reference it in the parameter file or the application itself.
def print_env (self)
Print all environment variables set for this application.
def print_env_copy (self, var_list=None)
def get_env_copy (self, var_list=None)
Print list of environment variables that can be easily copied into terminal.
def print_env_item (self, item)
Print single environment variable in the log file.
def print_user_env_items (self)
Prints user environment variables in the log file.
def handle_fcst_and_obs_field (self, gen_name, fcst_name, obs_name, default=None, sec='config')
Handles config variables that have fcst/obs versions or a generic variable to handle both, i.e.
def find_model (self, time_info, var_info, mandatory=True, return_list=False)
Finds the model file to compare Args:
def find_obs (self, time_info, var_info, mandatory=True, return_list=False)
Finds the observation file to compare Args:
def find_data (self, time_info, var_info, data_type, mandatory=True, return_list=False)
Finds the data file to compare Args:
def find_exact_file (self, level, data_type, time_info, mandatory=True, return_list=False)
def find_file_in_window (self, level, data_type, time_info, mandatory=True, return_list=False)
def write_list_file (self, filename, file_list)
Writes a file containing a list of filenames to the staging dir.
def find_and_check_output_file (self, time_info)
Look for expected output file.
def format_list_string (self, list_string)
Add quotation marks around each comma separated item in the string.
def check_for_externals (self)
def check_for_gempak (self)
def check_gempaktocf (self, gempaktocf_jar)
def get_output_prefix (self, time_info)
def check_for_python_embedding (self, input_type, var_info)
Check if field name of given input type is a python script.
def get_command (self)
Builds the command to run the MET application string.
def build_and_run_command (self)
def build (self)
Build and run command.
def run_at_time (self, input_dict)
Used to output error and exit if wrapper is attemped to be run with LOOP_ORDER = times and the run_at_time method is not implemented.
def run_all_times (self)
Loop over time range specified in conf file and call METplus wrapper for each time.
Public Attributes
app_path
app_name
lookindir
param
Public Attributes inherited from command_builder.CommandBuilder
isOK
errors
logger
config
env_list
debug
args
input_dir
infiles
outdir
outfile
param
env
c_dict
cmdrunner
Member Function Documentation
build_stringsub_dict()
def stat_analysis_wrapper.StatAnalysisWrapper.build_stringsub_dict (self, date_beg, date_end, date_type, lists_to_loop, lists_to_group, config_dict)
Build a dictionary with list names, dates, and commonly used identifiers to pass to string_template_substitution.
Args: date_beg - string of the beginning date in YYYYMMDD form date_end - string of the end date in YYYYMMDD form date_type - string of the date type, either VALID or INIT lists_to_loop - list of all the list names whose items are being grouped together lists_to group - list of all the list names whose items are being looped over config_dict - dictionary containing the configuration information
Returns: stringsub_dict - dictionary containing the formatted information to pass to the string_template_substitution
Definition at line 285 of file stat_analysis_wrapper.py.
Referenced by stat_analysis_wrapper.StatAnalysisWrapper.format_thresh(), stat_analysis_wrapper.StatAnalysisWrapper.get_lookin_dir(), and stat_analysis_wrapper.StatAnalysisWrapper.get_output_filename().
create_c_dict()
def stat_analysis_wrapper.StatAnalysisWrapper.create_c_dict (self)
Create a data structure (dictionary) that contains all the values set in the configuration files that are common for stat_analysis_wrapper.py.
Args:
Returns: c_dict - a dictionary containing the settings in the configuration files unique to the wrapper
Definition at line 63 of file stat_analysis_wrapper.py.
filter_for_plotting()
def stat_analysis_wrapper.StatAnalysisWrapper.filter_for_plotting (self)
Special case for running stat_analysis over a period of valid or initialization dates for a filter job, so MakePlots can be run correctly following StatAnalysis.
This method loops over MODEL_LIST, . Args:
Returns:
Definition at line 1399 of file stat_analysis_wrapper.py.
Referenced by stat_analysis_wrapper.StatAnalysisWrapper.filter_for_plotting().
format_thresh()
def stat_analysis_wrapper.StatAnalysisWrapper.format_thresh (self, thresh)
Format thresholds for file naming.
Args: thresh - string of the treshold(s)
Return:
thresh_symbol - string of the threshold(s) with symbols thresh_letters - string of the threshold(s) with letters
Definition at line 240 of file stat_analysis_wrapper.py.
Referenced by stat_analysis_wrapper.StatAnalysisWrapper.build_stringsub_dict().
format_valid_init()
def stat_analysis_wrapper.StatAnalysisWrapper.format_valid_init (self, date_beg, date_end, date_type, config_dict)
Format the valid and initialization dates and hours for the MET stat_analysis config file.
Args: date_beg - string of the beginning date in YYYYMMDD form date_end - string of the end date in YYYYMMDD form date_type - string of the date type, either VALID or INIT config_dict - dictionary containing the configuration information
Returns: config_dict - dictionary containing the edited configuration information for valid and initialization dates and hours
Definition at line 848 of file stat_analysis_wrapper.py.
Referenced by stat_analysis_wrapper.StatAnalysisWrapper.filter_for_plotting(), stat_analysis_wrapper.StatAnalysisWrapper.get_lookin_dir(), and stat_analysis_wrapper.StatAnalysisWrapper.run_stat_analysis_job().
get_lookin_dir()
def stat_analysis_wrapper.StatAnalysisWrapper.get_lookin_dir (self, dir_path, date_beg, date_end, date_type, lists_to_loop, lists_to_group, config_dict)
Fill in necessary information to get the path to the lookin directory to pass to stat_analysis.
Args: dir_path - string of the user provided directory path date_beg - string of the beginning date in YYYYMMDD form date_end - string of the end date in YYYYMMDD form date_type - string of the date type, either VALID or INIT lists_to_loop - list of all the list names whose items are being grouped together lists_to group - list of all the list names whose items are being looped over config_dict - dictionary containing the configuration information
Returns: lookin_dir - string of the filled directory from dir_path
Definition at line 798 of file stat_analysis_wrapper.py.
Referenced by stat_analysis_wrapper.StatAnalysisWrapper.filter_for_plotting(), stat_analysis_wrapper.StatAnalysisWrapper.get_output_filename(), and stat_analysis_wrapper.StatAnalysisWrapper.run_stat_analysis_job().
get_output_filename()
def stat_analysis_wrapper.StatAnalysisWrapper.get_output_filename (self, output_type, filename_template, filename_type, date_beg, date_end, date_type, lists_to_loop, lists_to_group, config_dict)
Create a file name for stat_analysis output.
Args: output_type - string for the type of stat_analysis output, either dump_row or out_stat filename_template - string of the template to be used to create the file name filename_type - string of the source of the template being used, either default or user date_beg - string of the beginning date in YYYYMMDD form date_end - string of the end date in YYYYMMDD form date_type - string of the date type, either VALID or INIT lists_to_loop - list of all the list names whose items are being grouped together lists_to group - list of all the list names whose items are being looped over config_dict - dictionary containing the configuration information
Returns: output_filename - string of the filled file name template
Definition at line 661 of file stat_analysis_wrapper.py.
Referenced by stat_analysis_wrapper.StatAnalysisWrapper.build_stringsub_dict(), stat_analysis_wrapper.StatAnalysisWrapper.filter_for_plotting(), and stat_analysis_wrapper.StatAnalysisWrapper.run_stat_analysis_job().
list_to_str()
def stat_analysis_wrapper.StatAnalysisWrapper.list_to_str (self, list_of_values)
Turn a list of values into a single string so it can be set to an environment variable and read by the MET stat_analysis config file.
Args: list_of_values - list of values
Returns:
list_as_str - string created from list_of_values with the values separated by commas
Definition at line 137 of file stat_analysis_wrapper.py.
Referenced by stat_analysis_wrapper.StatAnalysisWrapper.filter_for_plotting(), and stat_analysis_wrapper.StatAnalysisWrapper.run_stat_analysis_job().
parse_model_info()
def stat_analysis_wrapper.StatAnalysisWrapper.parse_model_info (self)
Parse for model information.
Args:
Returns: model_list - list of dictionaries containing model information
Definition at line 998 of file stat_analysis_wrapper.py.
Referenced by stat_analysis_wrapper.StatAnalysisWrapper.filter_for_plotting(), and stat_analysis_wrapper.StatAnalysisWrapper.run_stat_analysis_job().
run_stat_analysis_job()
def stat_analysis_wrapper.StatAnalysisWrapper.run_stat_analysis_job (self, date_beg, date_end, date_type)
This runs stat_analysis over a period of valid or initialization dates for a job defined by the user.
Args: date_beg - string of the beginning date in YYYYMMDD form date_end - string of the end date in YYYYMMDD form date_type - string of the date type, either VALID or INIT
Returns:
Definition at line 1116 of file stat_analysis_wrapper.py.
Referenced by stat_analysis_wrapper.StatAnalysisWrapper.filter_for_plotting().
set_lists_loop_or_group()
def stat_analysis_wrapper.StatAnalysisWrapper.set_lists_loop_or_group (self, config_lists_to_group_items, config_lists_to_loop_items, config_dict)
Determine whether the lists from the METplus config file should treat the items in that list as a group or items to be looped over based on user settings, the values in the list, and process being run.
Args: config_lists_to_group_items - list of the METplus config list names to group the list's items set by user config_lists_to_loop_items - list of the METplus config list names to loop over the list's items set by user config_dict - dictionary containing the configuration information
Returns: lists_to_group_items - list of all the list names whose items are being grouped together lists_to_loop_items - list of all the list names whose items are being looped over
Definition at line 159 of file stat_analysis_wrapper.py.
Referenced by stat_analysis_wrapper.StatAnalysisWrapper.filter_for_plotting(), stat_analysis_wrapper.StatAnalysisWrapper.list_to_str(), and stat_analysis_wrapper.StatAnalysisWrapper.run_stat_analysis_job().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/stat_analysis_wrapper.py