METplus: produtil.testing.parse.Parser Class Reference
produtil.testing.parse.Parser Class Reference
Parser for the produtil.testing suite.
Detailed Description
Parser for the produtil.testing suite.
Definition at line 99 of file parse.py.
Public Member Functions
def __init__ (self, run_mode=None, logger=None, verbose=True)
Constructor for the Parser.
def run_mode (self)
Returns the run mode: produtil.testing.utilities.EXECUTION or produtil.testing.utilities.BASELINE.
def verbose (self)
Verbosity flag.
def logger (self)
The logging.Logger to log messages.
def allset (self)
Returns the special "**all**" runset, which contains all runnables that had an explicit run statement.
def setarith (self, expr=None)
Executes the specified expression via the setarith module, returning the resulting runset as a ListableSet.
def iterrun (self, runset=' **all **')
Iterates over all runnables in the runset.
def itersets (self)
def con (self, token=None, scopes=None)
Returns a context for the given token and scope.
def add_run (self, runset, runme, con)
Adds another runnable object to execute in a given runset.
def resolve_deps (self)
Resolves dependencies in the runsets, replacing them with new runsets that contain all dependencies and have runnables listed in correct dependency order.
def parse (self, tokenizer, scope=None, unique_id=None, morevars=None)
Main entry point for the parser.
def parse_between_arguments (self, tokiter, ends=None)
Used inside an argument list "function(arg,arg2,...)".
def skip_eoln (self, tokiter)
Skips over end-of-line characters.
def parse_between_assignments (self, tokiter)
Skips over characters between assignments in a scope ,;.
def parse_embed_script (self, tokiter, scopes, ends, parse_between=None)
Parses an embedded script block.
def parse_set_list (self, tokiter, scopes)
Iterates over a list of set names, yielding each one.
def parse_deplist (self, tokiter, scopes, task, ends)
Parses and iterates over a list of dependencies.
def parse_op_list (self, tokiter, scopes, subscope)
Parses and iterates over list of "target .operator. source" expressions.
def parse_hash_define (self, tokiter, scopes, subscope, parse_between=None, allow_deps=False, hash_type='hash')
Parses a variable hash definition.
def parse_spawn_element (self, tokiter, scopes, spawn, ends)
Parses one element (block of MPI ranks) of a process spawning block.
def parse_spawn_block (self, tokiter, scopes, name, spawn, ends, parse_between)
Parses a subprocess spawning subblock.
def parse_spawn (self, tokiter, scopes, name, spawn)
Parses a subprocess spawning block.
def parse_autodetect (self, tokiter, scopes, taskname, task)
Parses an autodetect block.
def parse_load (self, tokiter, scope, seen_run)
Parses a "load" statement.
def parse_subscope (self, tokiter, scopes, ends, parse_between, allow_overwrite=True, allow_resolve=True, allow_run=False, allow_null=False, allow_use=False, scope_name='subscope', only_scalars=False, allow_load=False, seen_run=False)
def parse_subscope_impl (self, tokiter, scopes, ends, parse_between, allow_overwrite=True, allow_resolve=True, allow_run=False, allow_null=False, allow_use=False, scope_name='subscope', only_scalars=False, allow_load=False, seen_run=False)
General subscope parser, used for parsing most scopes.
def parse_rvalue (self, tokiter, scopes, ends, parse_between=None, only_scalars=False, use_references=False)
Parses an rvalue, which is anything that can be stored in to a storage location.
def action_autodetect (self, con, tokiter, scopes, taskname, task)
Executes an autodetect block.
def action_dependency (self, task, scopes, dep)
Adds the specified dependency to the specified task.
def action_call (self, varname, token, scopes, parameters)
Creates a scope that represents a function call.
def action_use (self, scopes, key_token, only_scalars=False)
Performs the action of a "use" block within a subscope.
def action_operator (self, scopes, token)
Creates an object that represents the operator ".oper." in the expression "a .oper. b".
def action_numeric (self, scopes, token)
Returns a Numeric object for the given token.
def action_string (self, scopes, token)
Returns a String object for the given token.
def action_reference (self, varname_token, scopes)
def action_resolve (self, varname_token, scopes)
Resolves a variable reference within a scope.
def action_null_param (self, varname, scope)
Defines a variable with no value in the given scope.
def action_assign_var (self, toscope, tovar, fromvar, fromscopes, allow_overwrite)
Assigns a value to a variable within a scope, from another variable in another scope.
def action_assign (self, scope, varname, value, allow_overwrite)
Assigns a value to a variable within a scope.
def action_run_in_set (self, setname, obj, con)
Requests that a specified object be available for running, within a specific runset.
def action_run_by_name (self, obj, con)
Requests that a specified object be available for running, without putting it in any runset.
def error (self, mode, token, reason=None)
Convenience function for error messages.
Public Attributes
run_mode
Returns the run mode: produtil.testing.utilities.EXECUTION or produtil.testing.utilities.BASELINE.
Constructor & Destructor Documentation
__init__()
def produtil.testing.parse.Parser.__init__ (self, run_mode = None, logger = None, verbose = True)
Constructor for the Parser.
Parameters
run_mode produtil.testing.utilities.EXECUTION to execute and verify results, or produtil.testing.utilities.BASELINE to generate a new baseline.
logger a logging.Logger for logging messages, such as syntax errors
verbose Increased verbosity flag: True = more verbose.
Definition at line 101 of file parse.py.
Member Function Documentation
action_assign()
def produtil.testing.parse.Parser.action_assign (self, scope, varname, value, allow_overwrite)
Assigns a value to a variable within a scope.
Parameters
scope The scope in which to assign.
varname The name of the variable within the scope, a string.
value The value of the variable, a BaseObject
allow_overwrite If True, replacing an existing variable's value is allowed.
Returns
None
Definition at line 1369 of file parse.py.
Referenced by produtil.testing.parse.Parser.action_assign_var().
action_assign_var()
def produtil.testing.parse.Parser.action_assign_var (self, toscope, tovar, fromvar, fromscopes, allow_overwrite)
Assigns a value to a variable within a scope, from another variable in another scope.
Parameters
toscope The scope in which a variable is being defined.
tovar The target variable name
fromvar The variable reference to the source variable
fromscopes The scopes, innermost first, in which to resolve the fromvar variable reference
allow_overwrite If True, redefining tovar within toscope is allowed.
Definition at line 1354 of file parse.py.
Referenced by produtil.testing.parse.Parser.action_null_param().
action_autodetect()
def produtil.testing.parse.Parser.action_autodetect (self, con, tokiter, scopes, taskname, task)
Executes an autodetect block.
Executes the "detect" function within each element of an autodetect block, choosing the block whose detect function returns True. It is an error for more or less than one platform to return True.
Definition at line 1190 of file parse.py.
Referenced by produtil.testing.parse.Parser.parse_subscope_impl().
action_call()
def produtil.testing.parse.Parser.action_call (self, varname, token, scopes, parameters)
Creates a scope that represents a function call.
Parameters
varname The function to call.
parameters The arguments to the function.
token the context from which the function call is requested.
scopes a list of nested scopes (outermost first) surrounding the call
Returns
a scope representing the given function call
Definition at line 1229 of file parse.py.
Referenced by produtil.testing.parse.Parser.parse_deplist(), and produtil.testing.parse.Parser.parse_rvalue().
action_dependency()
def produtil.testing.parse.Parser.action_dependency (self, task, scopes, dep)
Adds the specified dependency to the specified task.
Parameters
task The task for whom the dependency is to be added.
dep The dependency
scopes The surrounding scopes (presently unused)
Definition at line 1222 of file parse.py.
Referenced by produtil.testing.parse.Parser.parse_deplist().
action_null_param()
def produtil.testing.parse.Parser.action_null_param (self, varname, scope)
Defines a variable with no value in the given scope.
Parameters
varname the name of the variable, a string
scope the scope in which to define the variable
Returns
None
Definition at line 1343 of file parse.py.
action_numeric()
def produtil.testing.parse.Parser.action_numeric (self, scopes, token)
Returns a Numeric object for the given token.
Parameters
scopes a list of nested scopes (outermost first) surrounding the number
token The token containing the number
Returns
a Numeric object
Definition at line 1302 of file parse.py.
Referenced by produtil.testing.parse.Parser.parse_rvalue().
action_operator()
def produtil.testing.parse.Parser.action_operator (self, scopes, token)
Creates an object that represents the operator ".oper." in the expression "a .oper. b".
Parameters
scopes a list of nested scopes (outermost first) surrounding the expression
token the token containing the name of the operator
Returns
an object that represents the operator
Definition at line 1276 of file parse.py.
Referenced by produtil.testing.parse.Parser.parse_op_list().
action_resolve()
def produtil.testing.parse.Parser.action_resolve (self, varname_token, scopes)
Resolves a variable reference within a scope.
Parameters
varname_token The token containing the name of the variable reference.
scopes a list of nested scopes (outermost first) surrounding the reference
Returns
the value of the referenced variable PTKeyError if no such variable exists
Definition at line 1329 of file parse.py.
Referenced by produtil.testing.parse.Parser.parse_deplist(), produtil.testing.parse.Parser.parse_op_list(), produtil.testing.parse.Parser.parse_rvalue(), and produtil.testing.parse.Parser.parse_set_list().
action_run_by_name()
def produtil.testing.parse.Parser.action_run_by_name (self, obj, con)
Requests that a specified object be available for running, without putting it in any runset.
This is used to implement the part of the "run" statement before set lists.
Parameters
obj The object to run.
con The produtil.testing.parsetree.Context from which the run statement is made.
Definition at line 1402 of file parse.py.
Referenced by produtil.testing.parse.Parser.parse_subscope_impl().
action_run_in_set()
def produtil.testing.parse.Parser.action_run_in_set (self, setname, obj, con)
Requests that a specified object be available for running, within a specific runset.
This is used to implement the part list of runsets in the "run" statement.
Parameters
setname The name of the set in which to run.
obj The object to run.
con The produtil.testing.parsetree.Context from which the run statement is made.
Definition at line 1390 of file parse.py.
Referenced by produtil.testing.parse.Parser.parse_subscope_impl().
action_string()
def produtil.testing.parse.Parser.action_string (self, scopes, token)
Returns a String object for the given token.
Parameters
scopes a list of nested scopes (outermost first) surrounding the string
token The token containing the string
Returns
a String object
Definition at line 1310 of file parse.py.
Referenced by produtil.testing.parse.Parser.parse_embed_script(), produtil.testing.parse.Parser.parse_op_list(), produtil.testing.parse.Parser.parse_rvalue(), and produtil.testing.parse.Parser.parse_spawn_element().
action_use()
def produtil.testing.parse.Parser.action_use (self, scopes, key_token, only_scalars = False)
Performs the action of a "use" block within a subscope.
Adds variables to scope[0] from another scope. The scope is defined by key_token, a name that is resolved using scopes surrounding scope[0]
Parameters
scopes The relevant scopes: scope[0] is the scope that is "using," while the other scopes are those surrounding scope[0].
key_token The token containing the name of the scope that is to be used.
only_scalars If True, then it is an error to "use" a scope that contains variables with non-scalar values.
Returns
None
Definition at line 1243 of file parse.py.
Referenced by produtil.testing.parse.Parser.parse_subscope_impl().
add_run()
def produtil.testing.parse.Parser.add_run (self, runset, runme, con)
Adds another runnable object to execute in a given runset.
Updates the internal bookkeeping to indicate the given runnable object can be run. If a runset is provided, then the set with the given name is updated to indicate it can run the object. Regardless of runset, the special "**all**" set is updated to run the given runnable. If the set already contains runme, adding it again has no effect.
Parameters
runset The set of
Definition at line 211 of file parse.py.
Referenced by produtil.testing.parse.Parser.action_run_by_name(), and produtil.testing.parse.Parser.action_run_in_set().
allset()
produtil.testing.parse.Parser.allset (self)
Returns the special "**all**" runset, which contains all runnables that had an explicit run statement.
Definition at line 156 of file parse.py.
Referenced by produtil.testing.parse.Parser.setarith().
con()
def produtil.testing.parse.Parser.con (self, token = None, scopes = None)
Returns a context for the given token and scope.
Parameters
token Used to determine the file and line number. If the token is None, then a fileless context is used. This indicates the context is not from any file or line.
scope the list of Scopes. If none are given, then an empty list is used. This indicates the scope is from outside the parsed text entirely.
Returns
a produtil.testing.parsetree.Context for the given token and scope, or a fileless context if no token is provided.
Definition at line 191 of file parse.py.
Referenced by produtil.testing.parse.Parser.action_call(), produtil.testing.parse.Parser.parse_deplist(), produtil.testing.parse.Parser.parse_embed_script(), produtil.testing.parse.Parser.parse_op_list(), and produtil.testing.parse.Parser.parse_subscope_impl().
error()
def produtil.testing.parse.Parser.error (self, mode, token, reason = None)
Convenience function for error messages.
Raises an exception explaining that an input file contains an error. This is used for most syntax or semantic errors.
Parameters
mode The run mode, which can be anything that can be cast to a string via str()
token The token at which the error occurred, or None if the end of the file was reached.
reason
Returns
Never. Always raises an exception.
Definition at line 1411 of file parse.py.
Referenced by produtil.testing.parse.Parser.action_operator(), produtil.testing.parse.Parser.action_use(), produtil.testing.script.LSFRunner.mpirunner(), produtil.testing.parse.Parser.parse_autodetect(), produtil.testing.parse.Parser.parse_between_assignments(), produtil.testing.parse.Parser.parse_deplist(), produtil.testing.parse.Parser.parse_embed_script(), produtil.testing.parse.Parser.parse_hash_define(), produtil.testing.parse.Parser.parse_load(), produtil.testing.parse.Parser.parse_op_list(), produtil.testing.parse.Parser.parse_rvalue(), produtil.testing.parse.Parser.parse_set_list(), produtil.testing.parse.Parser.parse_spawn(), produtil.testing.parse.Parser.parse_spawn_block(), produtil.testing.parse.Parser.parse_spawn_element(), and produtil.testing.parse.Parser.parse_subscope_impl().
iterrun()
def produtil.testing.parse.Parser.iterrun (self, runset = '**all**')
Iterates over all runnables in the runset.
Parameters
runset The runset of interest. If no runset is specified then the special "**all**" runset is used, which contains all runnables that had a "run" command, plus dependencies.
Definition at line 175 of file parse.py.
itersets()
def produtil.testing.parse.Parser.itersets (self)
"!Iterates over all runset names in self, including the
special "**all**" set, which contains all runnables that had a
"run" command, plus dependencies.
Definition at line 185 of file parse.py.
parse()
def produtil.testing.parse.Parser.parse (self, tokenizer, scope = None, unique_id = None, morevars = None)
Main entry point for the parser.
Parses the stream of tokens returned by the tokenizer.
Parameters
tokenizer The produtil.testing.tokenize.Tokenizer that returns a stream of tokens from some file or string
scope The innermost produtil.testing.parsetree.Scope. If None, a new produtil.testing.parsetree.Scope is created.
unique_id The value for the special UNIQUE_ID global variable.
morevars A dict with additional variables to set in the global scope.
Definition at line 276 of file parse.py.
parse_autodetect()
def produtil.testing.parse.Parser.parse_autodetect (self, tokiter, scopes, taskname, task)
Parses an autodetect block.
Parses a block of this form:
autodetect plat (/ wcoss.phase1, theia /)
Places the resulting information in the task argument.
Parameters
tokiter a peekable iterator that yields tokens
scopes a list of nested scopes (innermost first) surrounding the autodetect block
taskname the name of the autodetect block
task the scope in which to store the information.
Definition at line 770 of file parse.py.
Referenced by produtil.testing.parse.Parser.parse_subscope_impl().
parse_between_arguments()
def produtil.testing.parse.Parser.parse_between_arguments (self, tokiter, ends = None)
Used inside an argument list "function(arg,arg2,...)".
Skips over the "," and whitespace between arguments.
Parameters
tokiter a peekable iterator that yields tokens
ends optional; the termination token for the argument list. Default: ")"
Returns
True if we are still inside the argument list, or False otherwise
Definition at line 322 of file parse.py.
Referenced by produtil.testing.parse.Parser.parse_autodetect(), produtil.testing.parse.Parser.parse_deplist(), produtil.testing.parse.Parser.parse_embed_script(), produtil.testing.parse.Parser.parse_rvalue(), and produtil.testing.parse.Parser.parse_spawn_element().
parse_between_assignments()
def produtil.testing.parse.Parser.parse_between_assignments (self, tokiter)
Skips over characters between assignments in a scope ,;.
Skips over , and ; between assignments. Checks to see if the assignment block ended by looking for end-of-line, end-of-text or }
Parameters
tokiter a peekable iterator that yields tokens
Returns
True if any , ; } end-of-line or end-of-text were seen
Definition at line 356 of file parse.py.
Referenced by produtil.testing.parse.Parser.parse_embed_script(), produtil.testing.parse.Parser.parse_hash_define(), produtil.testing.parse.Parser.parse_load(), produtil.testing.parse.Parser.parse_op_list(), produtil.testing.parse.Parser.parse_rvalue(), and produtil.testing.parse.Parser.parse_spawn().
parse_deplist()
def produtil.testing.parse.Parser.parse_deplist (self, tokiter, scopes, task, ends)
Parses and iterates over a list of dependencies.
Parameters
tokiter a peekable iterator that yields tokens
scopes a list of nested scopes (innermost first) surrounding the list of dependencies
task The task for which the dependencies are being declared
ends List of termination tokens for the dependency list
Definition at line 481 of file parse.py.
Referenced by produtil.testing.parse.Parser.parse_hash_define().
parse_embed_script()
def produtil.testing.parse.Parser.parse_embed_script (self, tokiter, scopes, ends, parse_between = None)
Parses an embedded script block.
Returns the resulting object.
Parameters
tokiter a peekable iterator that yields tokens
scopes a list of nested scopes (innermost first) surrounding the embedded script block
ends termination tokens of the containing scope
parse_between an optional function that is called after the embedded script block. This skips over tokens between the embedded script block and the next item in the scope
Returns
a tuple containing the token with the variable name, and the scope that represents the embedded script.
Definition at line 388 of file parse.py.
Referenced by produtil.testing.parse.Parser.parse_subscope_impl().
parse_hash_define()
def produtil.testing.parse.Parser.parse_hash_define (self, tokiter, scopes, subscope, parse_between = None, allow_deps = False, hash_type = 'hash')
Parses a variable hash definition.
Parses a definition of the syntax "{ varname = rvalue, varname=rvalue, ...}" where rvalue is any value that may be assigned to a variable (see parse_rvalue())
Parameters
tokiter a peekable iterator that yields tokens
scopes a list of nested scopes (innermost first) surrounding the variable hash
parse_between a function called between "varname=rvalue" assignments, to skip over such things as commas
allow_deps If True, then parse_deplist() is called first, to parse a dependency list before the assignment list.
hash_type The type of hash, such as "task," for error messages.
Returns
the resulting Scope
Definition at line 590 of file parse.py.
Referenced by produtil.testing.parse.Parser.parse_op_list(), and produtil.testing.parse.Parser.parse_subscope_impl().
parse_load()
def produtil.testing.parse.Parser.parse_load (self, tokiter, scope, seen_run)
Parses a "load" statement.
Parses a statement of this form:
load 'otherfile.input'
This uses the tokiter's child() function to create a new tokenizer that parses the specified file. The parser then parses the file using parse_subscope(). This acts as if the file was inserted in the location of the "load" statement.
Parameters
tokiter a peekable iterator that yields tokens. It must also have a child() function that can create a new tokenizer for the loaded file
scope the scope in which the "load" statement resides
seen_run True if a "run" statement was seen.
Returns
None
Definition at line 810 of file parse.py.
Referenced by produtil.testing.parse.Parser.parse_subscope_impl().
parse_op_list()
def produtil.testing.parse.Parser.parse_op_list (self, tokiter, scopes, subscope)
Parses and iterates over list of "target .operator. source" expressions.
Parameters
tokiter a peekable iterator that yields tokens
scopes a list of nested scopes (innermost first) surrounding the list
subscope the Task for whom the operator list is being declared
Returns
None; this is an iterator
Definition at line 526 of file parse.py.
Referenced by produtil.testing.parse.Parser.parse_subscope_impl().
parse_rvalue()
def produtil.testing.parse.Parser.parse_rvalue (self, tokiter, scopes, ends, parse_between = None, only_scalars = False, use_references = False)
Parses an rvalue, which is anything that can be stored in to a storage location.
Parses rvalues. Anything that can be stored in variables, arguments, or elsewhere is an rvalue. This includes variables, strings, numbers, and named subscopes.
Parameters
tokiter a peekable iterator that yields tokens
scopes a list of nested scopes (outermost first) surrounding the rvalue
ends the list of tokens that indicate the end of the surrounding scope.
parse_between if the surrounding scope is a list of expressions, arguments, or assignments, then this function is called to skip values after the rvalue
only_scalars If True, only strings and numbers are allowed.
Returns
the resulting rvalue
Definition at line 1120 of file parse.py.
Referenced by produtil.testing.parse.Parser.parse_autodetect(), produtil.testing.parse.Parser.parse_spawn_element(), and produtil.testing.parse.Parser.parse_subscope_impl().
parse_set_list()
def produtil.testing.parse.Parser.parse_set_list (self, tokiter, scopes)
Iterates over a list of set names, yielding each one.
Parses a comma-separated list of set names, yielding each set name as a token. Skips intervening commas or whitespace.
Parameters
tokiter a peekable iterator that yields tokens
scopes a list of nested scopes (innermost first) surrounding the set list
Returns
None (this is an iterator)
Definition at line 446 of file parse.py.
Referenced by produtil.testing.parse.Parser.parse_subscope_impl().
parse_spawn()
def produtil.testing.parse.Parser.parse_spawn (self, tokiter, scopes, name, spawn)
Parses a subprocess spawning block.
Parses a block of this form:
{
  {"program_name", ranks=32, threads=1}
  {"program_name", ranks=16, threads=1}
  {"another_program", ranks=80, threads=1}
}
The beginning and ending set braces are also consumed. Uses the parse_spawn_block() to parse the individual subblocks. Constructs a scope containing the resuling information.
Parameters
tokiter a peekable iterator that yields tokens
scopes a list of nested scopes (innermost first) surrounding the subprocess spawn block
name the name of the subprocess spawn block
spawn the scope in which to store the subprocess spawning block information.
Returns
spawn
Definition at line 737 of file parse.py.
Referenced by produtil.testing.parse.Parser.parse_subscope_impl().
parse_spawn_block()
def produtil.testing.parse.Parser.parse_spawn_block (self, tokiter, scopes, name, spawn, ends, parse_between)
Parses a subprocess spawning subblock.
Parses a block of this form:
{"program_name", ranks=32, threads=1}
The set braces are also parsed. The parse_spawn_element() function parses the individual, comma-separated, elements within that block. The results are sent to the spawn argument.
Parameters
tokiter a peekable iterator that yields tokens
scopes a list of nested scopes (innermost first) surrounding the subprocess spawning block
name the name of the subprocess spawning block
ends the list of tokens that terminate the surrounding block
pars_between if specified, a function to call between the individual subprocess spawn elements
Returns
None
See also
parse_spawn_element()
Definition at line 702 of file parse.py.
Referenced by produtil.testing.parse.Parser.parse_spawn().
parse_spawn_element()
def produtil.testing.parse.Parser.parse_spawn_element (self, tokiter, scopes, spawn, ends)
Parses one element (block of MPI ranks) of a process spawning block.
Parses the individual, comma-separated elements of a spawn block:
{"program_name", ranks=32, threads=1}
Combines the result into a single scope and array.
Returns
a tuple containing the array of arguments and the resulting Scope.
Definition at line 644 of file parse.py.
Referenced by produtil.testing.parse.Parser.parse_spawn_block().
parse_subscope_impl()
def produtil.testing.parse.Parser.parse_subscope_impl (self, tokiter, scopes, ends, parse_between, allow_overwrite = True, allow_resolve = True, allow_run = False, allow_null = False, allow_use = False, scope_name = 'subscope', only_scalars = False, allow_load = False, seen_run = False)
General subscope parser, used for parsing most scopes.
Parses a scope. This includes the innermost (global) scope, and anything within blocks like these:
(... declarations and arguments ...)
{ ... declarations ... }
(/ ... array elements ... /)
The various arguments control what is allowed within the scope.
Parameters
tokiter a peekable iterator that yields tokens
scopes a list of nested scopes (innermost first) surrounding the scope to parse. The scope being parsed is the first element in this array.
ends tokens that indicate the end of the scope
parse_between tokens that separate pieces of the scope, such as declarations, array elements, or arguments.
allow_overwrite are we allowed to replace values that are already set in the scope?
allow_resolve When a variable reference is encountered, are we allowed to resolve it within the scope that is being parsed?
allow_run Are "run" statements allowed in this scope?
allow_none If True, then lone variable names are allowed. This is intended for use in argument lists.
allow_use Are "use" statements allowed in this scope?
scope_name The name of this scope, used for error reporting.
only_scalars If True, then only strings and numbers are allowed to be assigned to variables. If False, anything can be assigned.
allow_load Do we allow "load" statements in this scope?
seen_run Have we already seen a "run" statement within this scope, before parse_subscope() was called? If so, it is an error to have declarations.
Definition at line 889 of file parse.py.
Referenced by produtil.testing.parse.Parser.parse_load().
resolve_deps()
def produtil.testing.parse.Parser.resolve_deps (self)
Resolves dependencies in the runsets, replacing them with new runsets that contain all dependencies and have runnables listed in correct dependency order.
Returns
None
Definition at line 262 of file parse.py.
setarith()
def produtil.testing.parse.Parser.setarith (self, expr = None)
Executes the specified expression via the setarith module, returning the resulting runset as a ListableSet.
Automatically resolves dependencies.
Definition at line 161 of file parse.py.
skip_eoln()
def produtil.testing.parse.Parser.skip_eoln (self, tokiter)
Skips over end-of-line characters.
Parameters
tokiter a peekable iterator that yields tokens
Returns
None
Definition at line 348 of file parse.py.
verbose()
produtil.testing.parse.Parser.verbose (self)
Verbosity flag.
Verbosity flag: True for verbose logging, False for quiet mode.
Definition at line 139 of file parse.py.
Referenced by produtil.testing.parse.Parser.action_autodetect(), and produtil.testing.parse.Parser.con().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/produtil/testing/parse.py