METplus: produtil.testing.parsetree.Scope Class Reference
produtil.testing.parsetree.Scope Class Reference
Represents a scope; the region of which a name binding can be evaluated.
Detailed Description
Represents a scope; the region of which a name binding can be evaluated.
This includes hashes, tests, argument lists, and anything else with variable names or named arguments.
Definition at line 409 of file parsetree.py.
Public Member Functions
def __init__ (self, defscopes=None)
def __eq__ (self, other)
Scopes are equal iff they are the same object.
def override_local (self, defscopes, key, val)
Overrides a variable already defined in this scope or its subscopes.
def validate_parameter (self, name)
Raises an exception if the given name is not an acceptable keyword for constants or parameters.
def new_empty (self)
Returns a new, empty scope that is within the same parent scope of this Scope (has the same defscopes).
def bash_context (self, con)
Raises an exception to indicate that a Scope cannot be expressed in bash code.
def string_context (self, con)
Evaluates the _as_string variable in this scope, in a string context, if it is defined.
def no_nulls (self)
Are there any local variables defined to have null values?
def numeric_context (self, con)
Evaluates this scope in a numeric context.
def logical_context (self, con)
Evaluates this scope in a logical context.
def get_type (self, key)
Returns the type of variable that the key represents.
def as_parameters (self, con)
Changes all variables to parameters.
def rescope (self, scopemap=None, prepend=None)
Changes the context of this Scope.
def has_parameters (self)
Does this Scope contain parameters (function call arguments)?
def has_constants (self)
Are there any constants defined in this scope?
def use_from (self, used_scope, only_scalars=False)
Implements a "use" statement; copies definitions from another Scope.
def apply_parameters (self, scope, con)
Implements a function call using this Scope as the parameter list.
def __str__ (self)
def __repr__ (self)
def subscope (self, key)
Returns a Scope within this Scope, with the given name.
def getlocal (self, key)
Return the value of a key local to this scope without searching other scopes.
def setlocal (self, key, value)
Sets the value of a key within this scope.
def haslocal (self, key)
Is there a variable with this name?
def iterlocal (self)
Iterates over all local variables in this order: parameters, constants, variables.
def resolve (self, key, scopes=None)
Given a path to a variable, return the variable.
def force_define (self, key, value, skip_constants=False)
Sets the value of a variable, replacing the value if a variable is already defined with that name.
def check_define (self, key, value)
Defines a local variable, raising an exception if a variable is already defined with the given name.
def expand_string (self, string, con, scopes=None)
Performs string expansion.
Public Member Functions inherited from produtil.testing.parsetree.BaseObject
def __init__ (self, defscopes, set_flags=True)
Constructor for BaseObject.
def bash_context (self, con)
Expresses this object in bash code.
def oldcmp (self, other)
def is_valid_rvalue (self, con)
Can this value be assigned to a variable?
def string_context (self, con)
Expresses this object as a printable string.
def logical_context (self, con)
Expresses this object as a printable string.
def numeric_context (self, con)
Expresses this object as a float.
def rescope (self, scopemap=None, prepend=None)
Modifies this object's scopes, and that of any subobjects.
def run (self, con)
Instructs this object to execute.
def iterdeps (self)
Iterates over all runnable objects that are dependencies of this object.
def __repr__ (self)
def __str__ (self)
Public Attributes
is_scope
can_be_used
Public Attributes inherited from produtil.testing.parsetree.BaseObject
defscopes
A list of Scope objects that represent the call stack at which this object is being called, or the stack to the context at which the object is being defined.
is_scope
If True, this object can be treated as a Scope.
is_filters
If True, this object can be treated as a set of filters.
is_criteria
If True, this object can be treated as a list of output validation criteria.
is_scalar
If True, this is a scalar, such as a number or string.
can_be_used
If True, this object is a valid target for a "use" statement.
is_test
If True, this object can be used as a Test.
Protected Member Functions
def _apply_rescope (self, scopemap=None, prepend=None)
Internal implementation of rescope()
Protected Member Functions inherited from produtil.testing.parsetree.BaseObject
def _apply_rescope (self, scopemap=None, prepend=None)
Replaces Scope objects in this object's defscopes variable.
Member Function Documentation
__eq__()
def produtil.testing.parsetree.Scope.__eq__ (self, other)
Scopes are equal iff they are the same object.
Parameters
the other Scope against which to compare
Definition at line 424 of file parsetree.py.
_apply_rescope()
def produtil.testing.parsetree.Scope._apply_rescope (self, scopemap = None, prepend = None) protected
Internal implementation of rescope()
Modifies the the context of this Scope and everything below it. This is done by replacing Scope objects in defscopes. Asks all variables and subscopes to do the same, recursively.
Parameters
scopemap a mapping from old Scope to new Scope; elements of defscopes are replaced based on this mapping
prepend a list of Scope objects to prepend to defscopes. The scopemap is not applied to the prepend list.
Returns
None
Definition at line 541 of file parsetree.py.
apply_parameters()
def produtil.testing.parsetree.Scope.apply_parameters (self, scope, con)
Implements a function call using this Scope as the parameter list.
Creates a new Scope where all parameters in this scope are converted to local variables and possibly overridden. Scope self's parameters are used for the default argument values. The "scope" argument to apply_parameters() contains values to override those. Hence, self is the function definition and scope is the values set in the function call.
A third Scope is created, containing the result of applying the function call and default values. That third Scope has no parameters; all parameters have been converted to local values. The returned Scope has the same defscopes as self. That means any unresolved variables within the function will be resolved in the defining context, NOT the calling context.
Parameters
scope The arguments provided to the function call.
con the Context at which this function is being called. The defining location is in defscopes.
Returns
a Scope representing the function call.
Definition at line 629 of file parsetree.py.
as_parameters()
def produtil.testing.parsetree.Scope.as_parameters (self, con)
Changes all variables to parameters.
Parameters
con the Context in which this object is being evaluated
Definition at line 532 of file parsetree.py.
bash_context()
def produtil.testing.parsetree.Scope.bash_context (self, con)
Raises an exception to indicate that a Scope cannot be expressed in bash code.
Parameters
con the Context in which this object is being evaluated
Definition at line 454 of file parsetree.py.
check_define()
def produtil.testing.parsetree.Scope.check_define (self, key, value)
Defines a local variable, raising an exception if a variable is already defined with the given name.
Parameters
key the local variable name (no "%")
value a BaseObject that is a valid rvalue (is_rvalue=True)
Returns
value
Definition at line 870 of file parsetree.py.
expand_string()
def produtil.testing.parsetree.Scope.expand_string (self, string, con, scopes = None)
Performs string expansion.
Expands escape characters and variable references in a string.
Parameters
string a python string to expand
con the Context in which this object is being evaluated
scopes sent to resolve(); these scopes will be searched instead of defscopes when a variable is not found in this scope.
Returns
the resulting python string
Definition at line 888 of file parsetree.py.
force_define()
def produtil.testing.parsetree.Scope.force_define (self, key, value, skip_constants = False)
Sets the value of a variable, replacing the value if a variable is already defined with that name.
Parameters
key the local variable name (must contain no "%")
value a valid rvalue (is_rvalue=True)
skip_constants if True, the variable is NOT overridden if it is already defined as a constant
Returns
the value, or None if no action was performed. That can happen if skip_constants is True, and the name corresponds to a constant.
Definition at line 847 of file parsetree.py.
Referenced by produtil.testing.parsetree.Scope.use_from().
get_type()
def produtil.testing.parsetree.Scope.get_type (self, key)
Returns the type of variable that the key represents.
Searches for a variable name in the parameter (function call argument) list, the constant variable list, and the local variable list, in that order. Returns the type of variable based on the first of those three lists that contains the variable name. Note that this only searches for variable names; it will not work for variable paths (names containing "%")
Parameters
key the variable to search for; must not contain "%"
Returns
the variable type: "parameter" "constant" "var" or None
Definition at line 511 of file parsetree.py.
getlocal()
def produtil.testing.parsetree.Scope.getlocal (self, key)
Return the value of a key local to this scope without searching other scopes.
Will raise ValueError if the key contains a "%"
Parameters
key a valid identifier within this scope
Returns
The value of the key from this scope. ValueError if the key is syntactically not a valid identifier such as one that contains a "%" KeyError if the key is a valid identifier but is not within this scope.
Definition at line 716 of file parsetree.py.
Referenced by produtil.testing.parsetree.EmbedBash.bash_context(), produtil.testing.parsetree.Task.bash_context(), produtil.testing.parsetree.Test.bash_context(), produtil.testing.parsetree.Task.is_valid_rvalue(), produtil.testing.parsetree.Test.is_valid_rvalue(), produtil.testing.parsetree.Task.logical_context(), produtil.testing.parsetree.Task.numeric_context(), produtil.testing.parsetree.Task.run(), produtil.testing.parsetree.Scope.string_context(), and produtil.testing.parsetree.Task.string_context().
has_constants()
def produtil.testing.parsetree.Scope.has_constants (self)
Are there any constants defined in this scope?
Returns
True if this scope contains constants, False otherwise
Definition at line 591 of file parsetree.py.
has_parameters()
def produtil.testing.parsetree.Scope.has_parameters (self)
Does this Scope contain parameters (function call arguments)?
Returns
True if any parameters (function call arguments) are present, False otherwise.
Definition at line 586 of file parsetree.py.
haslocal()
def produtil.testing.parsetree.Scope.haslocal (self, key)
Is there a variable with this name?
Searches the parameter list, variable list, and constants list for the given variable name. The name must be local; it can contain no "%"
Parameters
key a local variable name (contains no "%")
Returns
True if any variable is set with the given name.
Definition at line 773 of file parsetree.py.
Referenced by produtil.testing.parsetree.Task.bash_context(), produtil.testing.parsetree.Task.is_valid_rvalue(), produtil.testing.parsetree.Test.is_valid_rvalue(), and produtil.testing.parsetree.Scope.string_context().
logical_context()
def produtil.testing.parsetree.Scope.logical_context (self, con)
Evaluates this scope in a logical context.
Returns
True if any variables, parameters (function call arguments) or constants are defined in this Scope. Returns False otherwise.
Parameters
con the Context in which this object is being evaluated (unused)
Definition at line 504 of file parsetree.py.
new_empty()
def produtil.testing.parsetree.Scope.new_empty (self)
Returns a new, empty scope that is within the same parent scope of this Scope (has the same defscopes).
Definition at line 449 of file parsetree.py.
Referenced by produtil.testing.parsetree.Rank.__init__(), produtil.testing.parsetree.SpawnProcess.__init__(), produtil.testing.parsetree.Scope.apply_parameters(), and produtil.testing.parsetree.Scope.rescope().
no_nulls()
def produtil.testing.parsetree.Scope.no_nulls (self)
Are there any local variables defined to have null values?
Returns
False if any local variable has a null_value, or True if no variables have null values
Definition at line 471 of file parsetree.py.
Referenced by produtil.testing.parsetree.Copy.bash_context(), produtil.testing.parsetree.CopyDir.bash_context(), produtil.testing.parsetree.Link.bash_context(), produtil.testing.parsetree.Copy.run(), and produtil.testing.parsetree.Link.run().
numeric_context()
def produtil.testing.parsetree.Scope.numeric_context (self, con)
Evaluates this scope in a numeric context.
Returns
the number of variables, parameters (function call arguments) and constants defined in this Scope
Parameters
con the Context in which this object is being evaluated (unused)
Definition at line 496 of file parsetree.py.
override_local()
def produtil.testing.parsetree.Scope.override_local (self, defscopes, key, val)
Overrides a variable already defined in this scope or its subscopes.
Parameters
defscopes a list of Scope objects that represent scopes outside of this one for the purpose of variable overrides
key the path to the variable to override. This may include "%" but it is always relative to this scope.
val the valuate to assign. This is re-expressed as a String
Definition at line 429 of file parsetree.py.
rescope()
def produtil.testing.parsetree.Scope.rescope (self, scopemap = None, prepend = None)
Changes the context of this Scope.
Modifies the the context of this Scope and everything below it, including parameters, variables and constants. This is done by replacing Scope objects in defscopes. Asks all variables and subscopes to do the same, recursively. This recursion is done by calling the _apply_rescope() function in each object.
Parameters
scopemap a mapping from old Scope to new Scope; elements of defscopes are replaced based on this mapping
prepend a list of Scope objects to prepend to defscopes. The scopemap is not applied to the prepend list.
Returns
self
Definition at line 560 of file parsetree.py.
Referenced by produtil.testing.parsetree.Scope.apply_parameters().
resolve()
def produtil.testing.parsetree.Scope.resolve (self, key, scopes = None)
Given a path to a variable, return the variable.
Searches this scope and its containing scopes for the given variable. The variable can be a path to a variable (containing "%") or a local variable (no "%"). If the scopes parameter is given, then those scopes are treated as the containing scopes; otherwise defscopes is used.
Parameters
key a local variable (no "%") or a path to a variable (containing "%")
scopes Optional. Replaces defscopes as the containing scopes to search if the variable is not defined in this scope.
Returns
a BaseObject for the requested variable KeyError if no such variable is defined
Definition at line 796 of file parsetree.py.
Referenced by produtil.testing.parsetree.Copy.bash_context(), produtil.testing.parsetree.CopyDir.bash_context(), produtil.testing.parsetree.Link.bash_context(), produtil.testing.parsetree.AtParse.bash_context(), produtil.testing.parsetree.BitCmp.bash_context(), produtil.testing.parsetree.NccmpVars.bash_context(), produtil.testing.parsetree.Md5Cmp.bash_context(), produtil.testing.parsetree.Test.bash_context(), produtil.testing.parsetree.Scope.expand_string(), produtil.testing.parsetree.Builtin.run(), produtil.testing.parsetree.Copy.run(), produtil.testing.parsetree.Link.run(), and produtil.testing.parsetree.BitCmp.run().
setlocal()
def produtil.testing.parsetree.Scope.setlocal (self, key, value)
Sets the value of a key within this scope.
Parameters
key a valid identifier to set within this scope
valuel the value of the identifier ValueError if the key is not a valid identifier, such as one that contains a "%"
Definition at line 737 of file parsetree.py.
string_context()
def produtil.testing.parsetree.Scope.string_context (self, con)
Evaluates the _as_string variable in this scope, in a string context, if it is defined.
Otherwise, returns the Python id of this Scope (id(self)) as a string.
Parameters
con the Context in which this object is being evaluated
Definition at line 460 of file parsetree.py.
Referenced by produtil.testing.parsetree.Scope.expand_string().
subscope()
def produtil.testing.parsetree.Scope.subscope (self, key)
Returns a Scope within this Scope, with the given name.
Parameters
key a valid identifier within this scope
Returns
a Scope with the given name, within this Scope ValueError if the key contains a "%" TypeError if the key refers to something in this Scope that is not a Scope. This is detected through the is_scope attribute or property.
Definition at line 691 of file parsetree.py.
use_from()
def produtil.testing.parsetree.Scope.use_from (self, used_scope, only_scalars = False)
Implements a "use" statement; copies definitions from another Scope.
Copies parameters, constants, and variables from another scope into this one. Copies are modified to have this scope in their definition or calling stack via the rescope() function.
Parameters
used_scope The scope whose data is being copied.
only_scalars If True, then only the objects with is_scalar=True are copied.
Returns
True if all variables seen were scalar, False if any non-scalar variables were seen. This includes variables that were found, but not "used," due to only_scalars=True
Definition at line 596 of file parsetree.py.
validate_parameter()
def produtil.testing.parsetree.Scope.validate_parameter (self, name)
Raises an exception if the given name is not an acceptable keyword for constants or parameters.
The default implementation does nothing.
Definition at line 443 of file parsetree.py.
Referenced by produtil.testing.parsetree.Scope.as_parameters(), and produtil.testing.parsetree.Scope.no_nulls().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/produtil/testing/parsetree.py