METplus: produtil.prog.StringInput Class Reference
produtil.prog.StringInput Class Reference
Represents sending a string to a process's stdin.
Detailed Description
Represents sending a string to a process's stdin.
Definition at line 259 of file prog.py.
Public Member Functions
def __init__ (self, obj)
Creates a StringInput that sends the specified object to stdin.
def copy (self)
Returns a shallow copy of this object.
def __repr__ (self)
Returns a string representation of this object as valid Python code.
def to_shell (self)
Converts this object, if possible, to an echo command followed by a pipe ("|").
def repr_for_in (self)
Part of the implementation of Runner.__repr__.
Public Member Functions inherited from produtil.prog.StreamGenerator
def for_input (self)
Has no effect.
def for_output (self)
Has no effect.
def repr_for_err (self)
Returns the stderr value.
Public Attributes
obj
the object to send to stdin
Constructor & Destructor Documentation
__init__()
def produtil.prog.StringInput.__init__ (self, obj)
Creates a StringInput that sends the specified object to stdin.
Parameters
obj the object to send to stdin
Definition at line 261 of file prog.py.
Member Function Documentation
__repr__()
def produtil.prog.StringInput.__repr__ (self)
Returns a string representation of this object as valid Python code.
Definition at line 276 of file prog.py.
Referenced by produtil.prog.Runner.__str__().
copy()
def produtil.prog.StringInput.copy (self)
Returns a shallow copy of this object.
Definition at line 269 of file prog.py.
Referenced by produtil.prog.ImmutableRunner.runner(), and produtil.prog.Runner.to_shell().
repr_for_in()
def produtil.prog.StringInput.repr_for_in (self)
Part of the implementation of Runner.__repr__.
If possible, this creates valid Python code to represent specifying sending the given string to the stdin of a Runner. If the string is too long, it is abbreviated.
Definition at line 284 of file prog.py.
to_shell()
def produtil.prog.StringInput.to_shell (self)
Converts this object, if possible, to an echo command followed by a pipe ("|").
Definition at line 280 of file prog.py.
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/produtil/prog.py