METplus: make_plots_wrapper.MakePlotsWrapper Class Reference
make_plots_wrapper.MakePlotsWrapper Class Reference
Wrapper to used to filter make plots from MET data.
Detailed Description
Wrapper to used to filter make plots from MET data.
Definition at line 27 of file make_plots_wrapper.py.
Public Member Functions
def __init__ (self, config, logger)
def set_plotting_script (self, plotting_script_path)
def get_command (self)
def create_c_dict (self)
Create a data structure (dictionary) that contains all the values set in the configuration files that are common for make_plots_wrapper.py.
def list_to_str (self, list_of_values)
Turn a list of values into a single string so it can be set to an environment variable and read by the MET stat_analysis config file.
def set_lists_loop_or_group (self, config_lists_to_group_items, config_lists_to_loop_items, config_dict)
Determine whether the lists from the METplus config file should treat the items in that list as a group or items to be looped over based on user settings, the values in the list, and process being run.
def parse_model_info (self)
Parse for model information.
def create_plots_grid2grid_pres (self, runtime_settings_dict_list)
Create plots for the grid-to-grid verification for variables on pressure levels using partial sums.
def create_plots_grid2grid_anom (self, runtime_settings_dict_list)
Create plots for the grid-to-grid verification for variables on pressure levels using anomalous partial sums.
def create_plots_grid2grid_sfc (self, runtime_settings_dict_list)
Create plots for the grid-to-grid verification for variables on a single level using partial sums.
def create_plots_grid2obs_upper_air (self, runtime_settings_dict_list)
Create plots for the grid-to-obs verification for variables on a pressure levels using partial sums.
def create_plots_grid2obs_conus_sfc (self, runtime_settings_dict_list)
Create plots for the grid-to-obs verification for variables on a single level using partial sums.
def create_plots_precip (self, runtime_settings_dict_list)
Create plots for the precipitation verification using contingency table counts.
def create_plots_user (self, runtime_settings_dict_list, scripts_to_run)
Create plots from user specified list.
def create_plots (self, verif_case, verif_type)
Set up variables and general looping for creating verification plots.
def run_all_times (self)
Public Member Functions inherited from command_builder.CommandBuilder
def __init__ (self, config, logger)
def create_c_dict (self)
def clear (self)
Unset class variables to prepare for next run time.
def log_error (self, error_string)
def set_user_environment (self, time_info=None)
Set environment variables defined in [user_env_vars] section of config.
def add_common_envs (self, time_info=None)
def print_all_envs (self)
def handle_window_once (self, c_dict, dtype, edge, app_name)
Check and set window dictionary variables like OBS_WINDOW_BEG or FCST_FILE_WINDW_END Args:
def handle_window_variables (self, c_dict, app_name, dtypes=['FCST', OBS)
Handle all window config variables like [FCST/OBS]_<app_name>_WINDOW_[BEGIN/END] and [FCST/OBS]_<app_name>_FILE_WINDOW_[BEGIN/END] Args:
def set_output_path (self, outpath)
Split path into directory and filename then save both.
def get_output_path (self)
Combine output directory and filename then return result.
def add_env_var (self, key, name)
Sets an environment variable so that the MET application can reference it in the parameter file or the application itself.
def print_env (self)
Print all environment variables set for this application.
def print_env_copy (self, var_list=None)
def get_env_copy (self, var_list=None)
Print list of environment variables that can be easily copied into terminal.
def print_env_item (self, item)
Print single environment variable in the log file.
def print_user_env_items (self)
Prints user environment variables in the log file.
def handle_fcst_and_obs_field (self, gen_name, fcst_name, obs_name, default=None, sec='config')
Handles config variables that have fcst/obs versions or a generic variable to handle both, i.e.
def find_model (self, time_info, var_info, mandatory=True, return_list=False)
Finds the model file to compare Args:
def find_obs (self, time_info, var_info, mandatory=True, return_list=False)
Finds the observation file to compare Args:
def find_data (self, time_info, var_info, data_type, mandatory=True, return_list=False)
Finds the data file to compare Args:
def find_exact_file (self, level, data_type, time_info, mandatory=True, return_list=False)
def find_file_in_window (self, level, data_type, time_info, mandatory=True, return_list=False)
def write_list_file (self, filename, file_list)
Writes a file containing a list of filenames to the staging dir.
def find_and_check_output_file (self, time_info)
Look for expected output file.
def format_list_string (self, list_string)
Add quotation marks around each comma separated item in the string.
def check_for_externals (self)
def check_for_gempak (self)
def check_gempaktocf (self, gempaktocf_jar)
def get_output_prefix (self, time_info)
def check_for_python_embedding (self, input_type, var_info)
Check if field name of given input type is a python script.
def get_command (self)
Builds the command to run the MET application string.
def build_and_run_command (self)
def build (self)
Build and run command.
def run_at_time (self, input_dict)
Used to output error and exit if wrapper is attemped to be run with LOOP_ORDER = times and the run_at_time method is not implemented.
def run_all_times (self)
Loop over time range specified in conf file and call METplus wrapper for each time.
Public Attributes
app_path
app_name
plotting_script
Public Attributes inherited from command_builder.CommandBuilder
isOK
errors
logger
config
env_list
debug
args
input_dir
infiles
outdir
outfile
param
env
c_dict
cmdrunner
Member Function Documentation
create_c_dict()
def make_plots_wrapper.MakePlotsWrapper.create_c_dict (self)
Create a data structure (dictionary) that contains all the values set in the configuration files that are common for make_plots_wrapper.py.
Args:
Returns: c_dict - a dictionary containing the settings in the configuration files unique to the wrapper
Definition at line 49 of file make_plots_wrapper.py.
create_plots()
def make_plots_wrapper.MakePlotsWrapper.create_plots (self, verif_case, verif_type)
Set up variables and general looping for creating verification plots.
Args: verif_case - string of the verification case to make plots for verif_type - string of the verification type to make plots for
Returns:
Definition at line 542 of file make_plots_wrapper.py.
Referenced by make_plots_wrapper.MakePlotsWrapper.create_plots().
create_plots_grid2grid_anom()
def make_plots_wrapper.MakePlotsWrapper.create_plots_grid2grid_anom (self, runtime_settings_dict_list)
Create plots for the grid-to-grid verification for variables on pressure levels using anomalous partial sums.
Runs plotting scripts: plot_time_series.py, plot_lead_average.py, plot_lead_by_date.py
Args:
runtime_settings_dict_list - list of dictionaries containing the relevant information for running plotting scripts
Returns:
Definition at line 326 of file make_plots_wrapper.py.
Referenced by make_plots_wrapper.MakePlotsWrapper.create_plots().
create_plots_grid2grid_pres()
def make_plots_wrapper.MakePlotsWrapper.create_plots_grid2grid_pres (self, runtime_settings_dict_list)
Create plots for the grid-to-grid verification for variables on pressure levels using partial sums.
Runs plotting scripts: plot_time_series.py, plot_lead_average.py, plot_date_by_level.py, plot_lead_by_level.py
Args:
runtime_settings_dict_list - list of dictionaries containing the relevant information for running plotting scripts
Returns:
Definition at line 288 of file make_plots_wrapper.py.
Referenced by make_plots_wrapper.MakePlotsWrapper.create_plots().
create_plots_grid2grid_sfc()
def make_plots_wrapper.MakePlotsWrapper.create_plots_grid2grid_sfc (self, runtime_settings_dict_list)
Create plots for the grid-to-grid verification for variables on a single level using partial sums.
Runs plotting scripts: plot_time_series.py, plot_lead_average.py
Args:
runtime_settings_dict_list - list of dictionaries containing the relevant information for running plotting scripts
Returns:
Definition at line 363 of file make_plots_wrapper.py.
Referenced by make_plots_wrapper.MakePlotsWrapper.create_plots().
create_plots_grid2obs_conus_sfc()
def make_plots_wrapper.MakePlotsWrapper.create_plots_grid2obs_conus_sfc (self, runtime_settings_dict_list)
Create plots for the grid-to-obs verification for variables on a single level using partial sums.
Runs plotting scripts: plot_time_series.py, plot_lead_average.py
Args:
runtime_settings_dict_list - list of dictionaries containing the relevant information for running plotting scripts
Returns:
Definition at line 436 of file make_plots_wrapper.py.
Referenced by make_plots_wrapper.MakePlotsWrapper.create_plots().
create_plots_grid2obs_upper_air()
def make_plots_wrapper.MakePlotsWrapper.create_plots_grid2obs_upper_air (self, runtime_settings_dict_list)
Create plots for the grid-to-obs verification for variables on a pressure levels using partial sums.
Runs plotting scripts: plot_time_series.py, plot_lead_average.py, plot_stat_by_level.py, plot_lead_by_level.py
Args:
runtime_settings_dict_list - list of dictionaries containing the relevant information for running plotting scripts
Returns:
Definition at line 398 of file make_plots_wrapper.py.
Referenced by make_plots_wrapper.MakePlotsWrapper.create_plots().
create_plots_precip()
def make_plots_wrapper.MakePlotsWrapper.create_plots_precip (self, runtime_settings_dict_list)
Create plots for the precipitation verification using contingency table counts.
Runs plotting scripts: plot_time_series.py, plot_lead_average.py, plot_threshold_average.py, plot_threshold_by_lead.py
Args:
runtime_settings_dict_list - list of dictionaries containing the relevant information for running plotting scripts
Returns:
Definition at line 471 of file make_plots_wrapper.py.
Referenced by make_plots_wrapper.MakePlotsWrapper.create_plots().
create_plots_user()
def make_plots_wrapper.MakePlotsWrapper.create_plots_user (self, runtime_settings_dict_list, scripts_to_run)
Create plots from user specified list.
Args: runtime_settings_dict_list - list of dictionaries containing the relevant information for running plotting scripts scripts_to_run - list of script names to run
Returns:
Definition at line 510 of file make_plots_wrapper.py.
Referenced by make_plots_wrapper.MakePlotsWrapper.create_plots().
list_to_str()
def make_plots_wrapper.MakePlotsWrapper.list_to_str (self, list_of_values)
Turn a list of values into a single string so it can be set to an environment variable and read by the MET stat_analysis config file.
Args: list_of_values - list of values
Returns:
list_as_str - string created from list_of_values with the values separated by commas
Definition at line 149 of file make_plots_wrapper.py.
Referenced by make_plots_wrapper.MakePlotsWrapper.create_plots(), stat_analysis_wrapper.StatAnalysisWrapper.filter_for_plotting(), and stat_analysis_wrapper.StatAnalysisWrapper.run_stat_analysis_job().
parse_model_info()
def make_plots_wrapper.MakePlotsWrapper.parse_model_info (self)
Parse for model information.
Args:
Returns: model_list - list of dictionaries containing model information
Definition at line 250 of file make_plots_wrapper.py.
Referenced by make_plots_wrapper.MakePlotsWrapper.create_plots(), stat_analysis_wrapper.StatAnalysisWrapper.filter_for_plotting(), and stat_analysis_wrapper.StatAnalysisWrapper.run_stat_analysis_job().
set_lists_loop_or_group()
def make_plots_wrapper.MakePlotsWrapper.set_lists_loop_or_group (self, config_lists_to_group_items, config_lists_to_loop_items, config_dict)
Determine whether the lists from the METplus config file should treat the items in that list as a group or items to be looped over based on user settings, the values in the list, and process being run.
Args: config_lists_to_group_items - list of the METplus config list names to group the list's items set by user config_lists_to_loop_items - list of the METplus config list names to loop over the list's items set by user config_dict - dictionary containing the configuration information
Returns: lists_to_group_items - list of all the list names whose items are being grouped together lists_to_loop_items - list of all the list names whose items are being looped over
Definition at line 171 of file make_plots_wrapper.py.
Referenced by make_plots_wrapper.MakePlotsWrapper.create_plots(), stat_analysis_wrapper.StatAnalysisWrapper.filter_for_plotting(), make_plots_wrapper.MakePlotsWrapper.list_to_str(), and stat_analysis_wrapper.StatAnalysisWrapper.run_stat_analysis_job().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/make_plots_wrapper.py