METplus: produtil.config.ProdConfig Class Reference
produtil.config.ProdConfig Class Reference
a class that contains configuration information
Detailed Description
a class that contains configuration information
This class keeps track of configuration information for all tasks in a running model. It can be used in a read-only manner as if it was a ConfigParser object. All ProdTask objects require an ProdConfig object to keep track of registered task names via the register_task_name method, the current forecast cycle (cycle property) and the Datastore object (datastore property).
This class should never be instantiated directly. Instead, you should use the produtil.config.from_string or produtil.config.from_file to read configuration information from an in-memory string or a file.
Definition at line 503 of file config.py.
Public Member Functions
def __init__ (self, conf=None, quoted_literals=False, strict=False, inline_comment_prefixes=(';',))
ProdConfig constructor.
def quoted_literals (self)
def fallback (self, name, details)
Asks whether the specified fallback is allowed.
def add_fallback_callback (self, function)
Appends a function to the list of fallback callback functions called by fallback()
def readstr (self, source)
read config data and add it to this object
def from_args (self, args=None, allow_files=True, allow_options=True, rel_path=None, verbose=False)
Given a list of arguments, usually from sys.argv[1:], reads configuration files or sets option values.
def read (self, source)
reads and parses a config file
def readfp (self, source)
read config data from an open file
def readstr (self, string)
reads config data from an in-memory string
def set_options (self, section, kwargs)
set values of several options in a section
def realtime (self)
is this a real-time simulation?
def set (self, section, key, value)
set a config option
def __enter__ (self)
grab the thread lock
def __exit__ (self, a, b, c)
release the thread lock
def register_task (self, name)
add a ConfigurableTask to the database
def log (self, sublog=None)
returns a logging.Logger object
def getdatastore (self)
returns the Datastore
def getcycle (self)
get the analysis time
def setcycle (self, cycle)
set the analysis time
def set_time_vars (self)
internal function that sets time-related variables
def add_section (self, sec)
add a new config section
def has_section (self, sec)
does this section exist?
def has_option (self, sec, opt)
is this option set?
def getdir (self, name, default=None, morevars=None, taskvars=None)
query the "dir" section
def getloc (self, name, default=None, morevars=None, taskvars=None)
search the config, exe and dir sections in that order
def getexe (self, name, default=None, morevars=None, taskvars=None)
query the "exe" section
def __getitem__ (self, arg)
convenience function; replaces self.items and self.get
def makedirs (self, args)
calls produtil.fileop.makedirs() on directories in the [dir] section
def keys (self, sec)
get options in a section
def sections (self)
gets the list of all sections from a configuration object
def items (self, sec, morevars=None, taskvars=None)
get the list of (option,value) tuples for a section
def write (self, fileobject)
write the contents of this ProdConfig to a file
def getraw (self, sec, opt, default=None)
return the raw value of an option
def strinterp (self, sec, string, kwargs)
perform string expansion
def timestrinterp (self, sec, string, ftime=None, atime=None, kwargs)
performs string expansion, including time variables
def getint (self, sec, opt, default=None, badtypeok=False, morevars=None, taskvars=None)
get an integer value
def getfloat (self, sec, opt, default=None, badtypeok=False, morevars=None, taskvars=None)
get a float value
def getstr (self, sec, opt, default=None, badtypeok=False, morevars=None, taskvars=None)
get a string value
def get (self, sec, opt, default=None, badtypeok=False, morevars=None, taskvars=None)
get the value of an option from a section
def options (self, sec)
what options are in this section?
def getboolean (self, sec, opt, default=None, badtypeok=False, morevars=None, taskvars=None)
alias for getbool: get a bool value
def getbool (self, sec, opt, default=None, badtypeok=False, morevars=None, taskvars=None)
get a bool value
Properties
datastore
read-only property: the Datastore object for this simulation
cycle
the analysis cycle, a datetime.datetime object
Constructor & Destructor Documentation
__init__()
def produtil.config.ProdConfig.__init__ (self, conf = None, quoted_literals = False, strict = False, inline_comment_prefixes = (';',))
ProdConfig constructor.
Creates a new ProdConfig object.
Parameters
conf the underlying configparser.ConfigParser object that stores the actual config data. This was a SafeConfigParser in Python 2 but in Python 3 the SafeConfigParser is now ConfigParser.
quoted_literals if True, then {'...'} and {"..."} will be interpreted as quoting the contained ... text. Otherwise, those blocks will be considered errors.
strict set default to False so it will not raise DuplicateOptionError or DuplicateSectionError, This param was added when ported to Python 3.6, to maintain the previous python 2 behavior.
inline_comment_prefixes,defaults set to ;. This param was added when ported to Python 3.6, to maintain the previous python 2 behavior.
Note: In Python 2, conf was ConfigParser.SafeConfigParser. In Python 3.2, the old ConfigParser class was removed in favor of SafeConfigParser which has in turn been renamed to ConfigParser. Support for inline comments is now turned off by default and section or option duplicates are not allowed in a single configuration source.
Definition at line 517 of file config.py.
Member Function Documentation
__enter__()
def produtil.config.ProdConfig.__enter__ (self)
grab the thread lock
Grabs this ProdConfig's thread lock. This is only for future compatibility and is never used.
Definition at line 778 of file config.py.
__exit__()
def produtil.config.ProdConfig.__exit__ (self, a, b, c)
release the thread lock
Releases this ProdConfig's thread lock. This is only for future compatibility and is never used.
Parameters
a,b,c unused
Definition at line 784 of file config.py.
__getitem__()
def produtil.config.ProdConfig.__getitem__ (self, arg)
convenience function; replaces self.items and self.get
This is a convenience function that provides access to the self.items or self.get functions.
conf["section"] – returns a dict containing the results of self.items(arg)
conf[a,b,c] – returns self.get(a,b,c) (b and c are optional)
Parameters
arg the arguments: a list or string
Definition at line 974 of file config.py.
add_fallback_callback()
def produtil.config.ProdConfig.add_fallback_callback (self, function)
Appends a function to the list of fallback callback functions called by fallback()
Appends the given function to the list that fallback() searches while determining if a workflow emergency fallback option is allowed.
Parameters
function a function f(allow,name,details)
See also
fallbacks()
Definition at line 596 of file config.py.
add_section()
def produtil.config.ProdConfig.add_section (self, sec)
add a new config section
Adds a section to this ProdConfig. If the section did not already exist, it will be initialized empty. Otherwise, this function has no effect.
Parameters
sec the new section's name
Definition at line 896 of file config.py.
Referenced by produtil.config.ProdConfig.__init__().
fallback()
def produtil.config.ProdConfig.fallback (self, name, details)
Asks whether the specified fallback is allowed.
May perform other tasks, such as alerting the operator.
Calls the list of functions sent to add_fallback_callback. Each one receives the result of the last, and the final result at the end is returned. Note that ALL of the callbacks are called, even if one returns False; this is not a short-circuit operation. This is done to allow all reporting methods report to their operator and decide whether the fallback is allowed.
Each function called is f(allow,name,details) where:
allow = True or False, whether the callbacks called thus far have allowed the fallback.
name = The short name of the fallback.
details = A long, human-readable description. May be several lines long.
Parameters
name the name of the emergency situation
Warning
This function may take seconds or minutes to return. It could perform cpu- or time-intensive operations such as emailing an operator.
Definition at line 563 of file config.py.
from_args()
def produtil.config.ProdConfig.from_args (self, args = None, allow_files = True, allow_options = True, rel_path = None, verbose = False)
Given a list of arguments, usually from sys.argv[1:], reads configuration files or sets option values.
Reads list of strings of these formats:
/path/to/file.conf — A configuration file to read.
section.option=value — A configuration option to set in a specified section.
Will read files in the order listed, and then will override options in the order listed. Note that specified options override those read from files. Also, later files override earlier files.
Parameters
args Typically argv[1:] or some other list of arguments.
allow_files If True, filenames are allowed in args. Otherwise, they are ignored.
allow_options If True, specified options (section.name=value) are allowed. Otherwise they are detected and ignored.
rel_path Any filenames that are relative will be relative to this path. If None or unspecified, the current working directory as of the entry to this function is used.
Returns
self
Definition at line 621 of file config.py.
Referenced by produtil.config.ProdConfig.readstr().
get()
def produtil.config.ProdConfig.get (self, sec, opt, default = None, badtypeok = False, morevars = None, taskvars = None)
get the value of an option from a section
Gets option opt from section sec, expands it and converts to a string. If the option is not found and default is specified, returns default. If badtypeok, returns default if the option is found, but cannot be converted. The morevars is used during string expansion: if {abc} is in the value of the given option, and morevars contains a key abc, then {abc} will be expanded using that value. The morevars is a dict that allows the caller to override the list of variables for string extrapolation.
Parameters
sec,opt the section and option
default if specified and not None, then the default is returned if an option has no value or the section does not exist
badtypeok is True, and the conversion fails, and a default is specified, the default will be returned.
morevars,taskvars dicts of more variables for string expansion
Definition at line 1268 of file config.py.
Referenced by produtil.config.ProdConfig.__getitem__(), produtil.datastore.UpstreamFile.check(), produtil.config.ProdConfig.getcycle(), produtil.config.ProdConfig.getraw(), and produtil.config.ProdConfig.timestrinterp().
getbool()
def produtil.config.ProdConfig.getbool (self, sec, opt, default = None, badtypeok = False, morevars = None, taskvars = None)
get a bool value
Gets option opt from section sec and expands it; see "get" for details. Attempts to convert it to a bool
Parameters
sec,opt the section and option
default if specified and not None, then the default is returned if an option has no value or the section does not exist
badtypeok is True, and the conversion fails, and a default is specified, the default will be returned.
morevars,taskvars dicts of more variables for string expansion
Definition at line 1318 of file config.py.
Referenced by produtil.config.ProdConfig.fallback(), produtil.config.ProdConfig.getboolean(), and produtil.config.ProdConfig.realtime().
getboolean()
def produtil.config.ProdConfig.getboolean (self, sec, opt, default = None, badtypeok = False, morevars = None, taskvars = None)
alias for getbool: get a bool value
This is an alias for getbool for code expecting a ConfigParser. Gets option opt from section sec and expands it; see "get" for details. Attempts to convert it to a bool
Parameters
sec,opt the section and option
default if specified and not None, then the default is returned if an option has no value or the section does not exist
badtypeok is True, and the conversion fails, and a default is specified, the default will be returned.
morevars,taskvars dicts of more variables for string expansion
Definition at line 1302 of file config.py.
getcycle()
def produtil.config.ProdConfig.getcycle (self)
get the analysis time
Returns the analysis time of this workflow as a datetime.datetime.
Definition at line 838 of file config.py.
getdatastore()
def produtil.config.ProdConfig.getdatastore (self)
returns the Datastore
Returns the produtil.datastore.Datastore object for this ProdConfig.
Definition at line 816 of file config.py.
getdir()
def produtil.config.ProdConfig.getdir (self, name, default = None, morevars = None, taskvars = None)
query the "dir" section
Search the "dir" section.
Returns
the specified key (name) from the "dir" section. Other options are passed to self.getstr.
Parameters
default the default value if the option is unset
morevars more variables for string substitution
taskvars even more variables for string substitution
name the option name to search for
Definition at line 925 of file config.py.
Referenced by produtil.config.ProdTask.__init__(), produtil.config.ProdTask.get_outdir(), and produtil.config.ProdTask.get_workdir().
getexe()
def produtil.config.ProdConfig.getexe (self, name, default = None, morevars = None, taskvars = None)
query the "exe" section
Search the "exe" section.
Returns
the specified key (name) from the "exe" section. Other options are passed to self.getstr.
Parameters
default the default value if the option is unset
morevars more variables for string substitution
taskvars even more variables for string substitution
name the option name to search for
Definition at line 960 of file config.py.
getfloat()
def produtil.config.ProdConfig.getfloat (self, sec, opt, default = None, badtypeok = False, morevars = None, taskvars = None)
get a float value
Gets option opt from section sec and expands it; see "get" for details. Attempts to convert it to a float
Parameters
sec,opt the section and option
default if specified and not None, then the default is returned if an option has no value or the section does not exist
badtypeok is True, and the conversion fails, and a default is specified, the default will be returned.
morevars,taskvars dicts of more variables for string expansion
Definition at line 1238 of file config.py.
getint()
def produtil.config.ProdConfig.getint (self, sec, opt, default = None, badtypeok = False, morevars = None, taskvars = None)
get an integer value
Gets option opt from section sec and expands it; see "get" for details. Attempts to convert it to an int.
Parameters
sec,opt the section and option
default if specified and not None, then the default is returned if an option has no value or the section does not exist
badtypeok is True, and the conversion fails, and a default is specified, the default will be returned.
morevars,taskvars dicts of more variables for string expansion
Definition at line 1223 of file config.py.
getloc()
def produtil.config.ProdConfig.getloc (self, name, default = None, morevars = None, taskvars = None)
search the config, exe and dir sections in that order
Find the location of a file in the named option. Searches the [config], [exe] and [dir] sections in order for an option by that name, returning the first one found.
Parameters
default the default value if the option is unset
morevars more variables for string substitution
taskvars even more variables for string substitution
name the option name to search for
Returns
the resulting value
Definition at line 939 of file config.py.
getraw()
def produtil.config.ProdConfig.getraw (self, sec, opt, default = None)
return the raw value of an option
Returns the raw value for the specified section and option, without string interpolation. That is, any {...} will be returned unmodified. Raises an exception if no value is set. Will not search other sections, unlike other accessors.
Parameters
sec the section
opt the option name
default the value to return if the option is unset. If unspecified or None, NoOptionError is raised
Definition at line 1049 of file config.py.
getstr()
def produtil.config.ProdConfig.getstr (self, sec, opt, default = None, badtypeok = False, morevars = None, taskvars = None)
get a string value
Gets option opt from section sec and expands it; see "get" for details. Attempts to convert it to a str
Parameters
sec,opt the section and option
default if specified and not None, then the default is returned if an option has no value or the section does not exist
badtypeok is True, and the conversion fails, and a default is specified, the default will be returned.
morevars,taskvars dicts of more variables for string expansion
Definition at line 1253 of file config.py.
Referenced by produtil.config.ProdConfig.getdatastore(), produtil.config.ProdConfig.getdir(), produtil.config.ProdConfig.getexe(), produtil.config.ProdConfig.getloc(), and produtil.config.ProdConfig.makedirs().
has_option()
def produtil.config.ProdConfig.has_option (self, sec, opt)
is this option set?
Determines if an option is set in the specified section
Returns
True if this ProdConfig has the given option in the specified section, and False otherwise.
Parameters
sec the section
opt the name of the option in that section
Definition at line 915 of file config.py.
Referenced by config_launcher.METplusConfig.getbool(), config_launcher.METplusConfig.getdir(), config_launcher.METplusConfig.getexe(), config_launcher.METplusConfig.getfloat(), config_launcher.METplusConfig.getint(), produtil.config.ProdConfig.getloc(), config_launcher.METplusConfig.getraw(), config_launcher.METplusConfig.getseconds(), and config_launcher.METplusConfig.getstr().
has_section()
def produtil.config.ProdConfig.has_section (self, sec)
does this section exist?
Determines if a config section exists (even if it is empty)
Returns
True if this ProdConfig has the given section and False otherwise.
Parameters
sec the section to check for
Definition at line 906 of file config.py.
items()
def produtil.config.ProdConfig.items (self, sec, morevars = None, taskvars = None)
get the list of (option,value) tuples for a section
Returns a section's options as a list of two-element tuples. Each tuple contains a config option, and the value of the config option after string interpolation. Note that the special config section inclusion option "@inc" is also returned.
Parameters
sec the section
morevars variables for string substitution
taskvars yet more variables
Returns
a list of (option,value) tuples, where the value is after string expansion
Definition at line 1019 of file config.py.
Referenced by produtil.config.ProdConfig.__getitem__(), produtil.numerics.TimeContainer.iteritems(), and produtil.datastore.Datum.iteritems().
keys()
def produtil.config.ProdConfig.keys (self, sec)
get options in a section
Returns a list containing the config options in the given section.
Parameters
sec the string name of the section
Definition at line 1006 of file config.py.
log()
def produtil.config.ProdConfig.log (self, sublog = None)
returns a logging.Logger object
Returns a logging.Logger object. If the sublog argument is provided, then the logger will be under that subdomain of the "produtil" logging domain. Otherwise, this ProdConfig's logger is returned.
Parameters
sublog the logging subdomain, or None
Returns
a logging.Logger object
Definition at line 803 of file config.py.
Referenced by produtil.config.ProdConfig.from_args(), and produtil.config.ProdConfig.getdatastore().
makedirs()
def produtil.config.ProdConfig.makedirs (self, args)
calls produtil.fileop.makedirs() on directories in the [dir] section
This is a simple utility function that calls produtil.fileop.makedirs() on some of the directories in the [dir] section.
Parameters
args the keys in the [dir] section for the directories to make.
Definition at line 994 of file config.py.
options()
def produtil.config.ProdConfig.options (self, sec)
what options are in this section?
Returns a list of options in the given section
Parameters
sec the section
Definition at line 1294 of file config.py.
Referenced by produtil.config.ProdConfig.items(), and produtil.config.ProdConfig.keys().
read()
def produtil.config.ProdConfig.read (self, source)
reads and parses a config file
Opens the specified config file and reads it, adding its contents to the configuration. This is used to implement the from_file module-scope function. You can use it again on an ProdConfig object to read additional files.
Parameters
source the file to read
Returns
self
Definition at line 716 of file config.py.
Referenced by produtil.config.ProdConfig.from_args().
readfp()
def produtil.config.ProdConfig.readfp (self, source)
read config data from an open file
Reads a config file from the specified file-like object. This is used to implement the readstr.
Parameters
source the opened file to read
Returns
self
Definition at line 728 of file config.py.
Referenced by produtil.config.ProdConfig.readstr().
readstr() [1/2]
def produtil.config.ProdConfig.readstr (self, source)
read config data and add it to this object
Given a string with conf data in it, parses the data.
Parameters
source the data to parse
Returns
self
Definition at line 608 of file config.py.
Referenced by produtil.config.ProdConfig.readstr().
readstr() [2/2]
def produtil.config.ProdConfig.readstr (self, string)
reads config data from an in-memory string
Reads the given string as a config file. This is used to implement the from_string module-scope function. You can use it again to read more config data into an existing ProdConfig.
Parameters
string the string to parse
Returns
self
Definition at line 738 of file config.py.
realtime()
def produtil.config.ProdConfig.realtime (self)
is this a real-time simulation?
Is this configuration for a real-time simulation? Defaults to True if unknown. This is the same as doing getbool('config','realtime',True).
Definition at line 764 of file config.py.
register_task()
def produtil.config.ProdConfig.register_task (self, name)
add a ConfigurableTask to the database
Checks to ensure that there is no other task by this name, and records the fact that there is now a task. This is used by the ConfigurableTask to ensure only one task is made by any name.
Definition at line 791 of file config.py.
set()
def produtil.config.ProdConfig.set (self, section, key, value)
set a config option
Sets the specified config option (key) in the specified section, to the specified value. All three are converted to strings via str() before setting the value.
Definition at line 771 of file config.py.
Referenced by produtil.config.ProdConfig.__init__(), config_launcher.METplusConfig.check_default(), produtil.config.ProdConfig.from_args(), config_launcher.METplusConfig.getexe(), produtil.config.ProdConfig.set_options(), produtil.config.ProdConfig.set_time_vars(), produtil.config.ProdConfig.setcycle(), and produtil.config.ProdConfig.timestrinterp().
set_options()
def produtil.config.ProdConfig.set_options (self, section, kwargs)
set values of several options in a section
Sets the value of several options in one section. The keywords arguments are the names of the options to set and the keyword values are the option values.
Parameters
section the section being modified
kwargs additional keyword arguments are the option names and values
Definition at line 750 of file config.py.
set_time_vars()
def produtil.config.ProdConfig.set_time_vars (self)
internal function that sets time-related variables
Sets many config options in the [config] section based on this workflow's analysis time. This is called automatically when the cycle property is assigned. You never need to call this function directly.
YMDHM - 201409171200 = forecast time September 17, 2014 at 12:00 UTC YMDH - 2014091712 YMD - 20140917 year - 2014 YYYY - 2014 YY - 14 (year % 100) CC - 20 (century) cen - 20 month - 09 MM - 09 day - 17 DD - 17 hour - 12 cyc - 12 HH - 12 minute - 00 min - 00
Definition at line 863 of file config.py.
Referenced by produtil.config.ProdConfig.setcycle().
setcycle()
def produtil.config.ProdConfig.setcycle (self, cycle)
set the analysis time
Sets the analysis time of this workflow. Also sets the [config] section's "cycle" option. Accepts anything that produtil.numerics.to_datetime recognizes.
Definition at line 846 of file config.py.
strinterp()
def produtil.config.ProdConfig.strinterp (self, sec, string, kwargs)
perform string expansion
Performs this ProdConfig's string interpolation on the specified string, as if it was a value from the specified section.
Parameters
sec the section name
string the string to expand
kwargs more variables for string substitution
Definition at line 1066 of file config.py.
timestrinterp()
def produtil.config.ProdConfig.timestrinterp (self, sec, string, ftime = None, atime = None, kwargs)
performs string expansion, including time variables
Performs this ProdConfig's string interpolation on the specified string, as self.strinterp would, but adds in additional keys based on the given analysis and forecast times. The keys are the same as the keys added to [config] for the cycle, except with "a" prepended for the analysis time, or "f" for the forecast time. There are three more keys for the difference between the forecast an analysis time. The famin is the forecast time in minutes, rounded down. The fahr and fahrmin are the forecast hour, rounded down, and the remainder in minutes, rounded down to the next nearest minute.
If the analysis time is None or unspecified, then self.cycle is used. The atime can be anything understood by produtil.numerics.to_datetime and the ftime can be anything understood by produtil.numerics.to_datetime_rel, given the atime (or, absent atime, self.cycle) as the second argument.
This is implemented as a wrapper around the self._time_formatter object, which knows how to expand the a* and f* variables without having to generate all of them.
Parameters
sec the section name
string the string to expand
ftime the forecast time or None
atime the analysis time or None
kwargs more variables for string expansion
Definition at line 1081 of file config.py.
write()
def produtil.config.ProdConfig.write (self, fileobject)
write the contents of this ProdConfig to a file
Writes the contents of an ProdConfig to the specified file, without interpolating (expanding) any strings. The file will be suitable for reading in to a new ProdConfig object in a later job. This is used to create the initial config file.
Parameters
fileobject an opened file to write to
Definition at line 1038 of file config.py.
Property Documentation
cycle
produtil.config.ProdConfig.cycle static
Initial value:
= property(getcycle,setcycle,None,
        )
the analysis cycle, a datetime.datetime object
Definition at line 860 of file config.py.
Referenced by produtil.testing.rocoto.RocotoWorkflow.__init__(), and produtil.config.ProdConfig.timestrinterp().
datastore
produtil.config.ProdConfig.datastore static
Initial value:
= property(getdatastore,None,None, \
        )
read-only property: the Datastore object for this simulation
Definition at line 833 of file config.py.
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/produtil/config.py