METplus: tc_stat_wrapper.TCStatWrapper Class Reference
tc_stat_wrapper.TCStatWrapper Class Reference
Wrapper for the MET tool, tc_stat, which is used to filter tropical cyclone pair data.
Detailed Description
Wrapper for the MET tool, tc_stat, which is used to filter tropical cyclone pair data.
Definition at line 38 of file tc_stat_wrapper.py.
Public Member Functions
def __init__ (self, config, logger)
def create_c_dict (self)
Read in and store all the values from the config file.
def run_all_times (self)
Builds the call to the MET tool TC-STAT for all requested initialization times (init or valid).
def set_envs (self)
Set the env variables based on settings in the METplus config files.
def config_lists_ok (self)
Verify that the length of the name and val lists in the MET tc-stat config file are of equal length, if not, log an error message and exit.
def build_tc_stat (self, tc_stat_output_dir, cur_init, tc_input_list, filter_opts)
This is called from extract_tiles_wrapper and from any other wrapper to provide additional filtering WITHOUT the need for a tc_stat MET config file.
Public Member Functions inherited from command_builder.CommandBuilder
def __init__ (self, config, logger)
def create_c_dict (self)
def clear (self)
Unset class variables to prepare for next run time.
def log_error (self, error_string)
def set_user_environment (self, time_info=None)
Set environment variables defined in [user_env_vars] section of config.
def add_common_envs (self, time_info=None)
def print_all_envs (self)
def handle_window_once (self, c_dict, dtype, edge, app_name)
Check and set window dictionary variables like OBS_WINDOW_BEG or FCST_FILE_WINDW_END Args:
def handle_window_variables (self, c_dict, app_name, dtypes=['FCST', OBS)
Handle all window config variables like [FCST/OBS]_<app_name>_WINDOW_[BEGIN/END] and [FCST/OBS]_<app_name>_FILE_WINDOW_[BEGIN/END] Args:
def set_output_path (self, outpath)
Split path into directory and filename then save both.
def get_output_path (self)
Combine output directory and filename then return result.
def add_env_var (self, key, name)
Sets an environment variable so that the MET application can reference it in the parameter file or the application itself.
def print_env (self)
Print all environment variables set for this application.
def print_env_copy (self, var_list=None)
def get_env_copy (self, var_list=None)
Print list of environment variables that can be easily copied into terminal.
def print_env_item (self, item)
Print single environment variable in the log file.
def print_user_env_items (self)
Prints user environment variables in the log file.
def handle_fcst_and_obs_field (self, gen_name, fcst_name, obs_name, default=None, sec='config')
Handles config variables that have fcst/obs versions or a generic variable to handle both, i.e.
def find_model (self, time_info, var_info, mandatory=True, return_list=False)
Finds the model file to compare Args:
def find_obs (self, time_info, var_info, mandatory=True, return_list=False)
Finds the observation file to compare Args:
def find_data (self, time_info, var_info, data_type, mandatory=True, return_list=False)
Finds the data file to compare Args:
def find_exact_file (self, level, data_type, time_info, mandatory=True, return_list=False)
def find_file_in_window (self, level, data_type, time_info, mandatory=True, return_list=False)
def write_list_file (self, filename, file_list)
Writes a file containing a list of filenames to the staging dir.
def find_and_check_output_file (self, time_info)
Look for expected output file.
def format_list_string (self, list_string)
Add quotation marks around each comma separated item in the string.
def check_for_externals (self)
def check_for_gempak (self)
def check_gempaktocf (self, gempaktocf_jar)
def get_output_prefix (self, time_info)
def check_for_python_embedding (self, input_type, var_info)
Check if field name of given input type is a python script.
def get_command (self)
Builds the command to run the MET application string.
def build_and_run_command (self)
def build (self)
Build and run command.
def run_at_time (self, input_dict)
Used to output error and exit if wrapper is attemped to be run with LOOP_ORDER = times and the run_at_time method is not implemented.
def run_all_times (self)
Loop over time range specified in conf file and call METplus wrapper for each time.
Public Attributes
app_name
by_config
tc_exe
Public Attributes inherited from command_builder.CommandBuilder
isOK
errors
logger
config
env_list
debug
args
input_dir
infiles
outdir
outfile
param
env
c_dict
cmdrunner
Member Function Documentation
build_tc_stat()
def tc_stat_wrapper.TCStatWrapper.build_tc_stat (self, tc_stat_output_dir, cur_init, tc_input_list, filter_opts)
This is called from extract_tiles_wrapper and from any other wrapper to provide additional filtering WITHOUT the need for a tc_stat MET config file.
Creates the call to MET tool TC-STAT to subset tc-pairs output based on the criteria specified in the feature relative use case parameter/config file.
Args:
Parameters
tc_stat_output_dir The output directory where filtered results are saved.
cur_init The initialization time
tc_input_list The "list" of input data (the files containing the tc pair data to be filtered) in a string
filter_opts The list of filter options to apply
Returns: None: if no error, then invoke MET tool TC-STAT and subsets tc-pairs data, creating a filter.tcst file.
Raises CalledProcessError
Definition at line 766 of file tc_stat_wrapper.py.
Referenced by tc_stat_wrapper.TCStatWrapper.config_lists_ok().
config_lists_ok()
def tc_stat_wrapper.TCStatWrapper.config_lists_ok (self)
Verify that the length of the name and val lists in the MET tc-stat config file are of equal length, if not, log an error message and exit.
As soon as a length mismatch is encountered, return False.
Args:
Returns: True: if all corresponding <>_NAME and <>_VAL lists have the same length False: if any name/val list length mismatch is encountered
Definition at line 696 of file tc_stat_wrapper.py.
Referenced by tc_stat_wrapper.TCStatWrapper.run_all_times().
create_c_dict()
def tc_stat_wrapper.TCStatWrapper.create_c_dict (self)
Read in and store all the values from the config file.
This will make it easier to reassign values while unit testing and make it easier when retrieving these values, especially when they are needed multiple times by different methods.
Args:
Returns: tc_stat_dict - a dictionary of the key-value representation of options set in the config file.
Definition at line 55 of file tc_stat_wrapper.py.
run_all_times()
def tc_stat_wrapper.TCStatWrapper.run_all_times (self)
Builds the call to the MET tool TC-STAT for all requested initialization times (init or valid).
Called from master_metplus
Args:
Returns: 0 if successfully runs MET tc_stat tool. 1 otherwise
Definition at line 245 of file tc_stat_wrapper.py.
set_envs()
def tc_stat_wrapper.TCStatWrapper.set_envs (self)
Set the env variables based on settings in the METplus config files.
This is only necessary when running MET tc_stat via the config file.
Args:
Returns: 0 - if successfully sets env variable
Definition at line 317 of file tc_stat_wrapper.py.
Referenced by tc_stat_wrapper.TCStatWrapper.run_all_times().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/tc_stat_wrapper.py