METplus: produtil.prog.FileOpener Class Reference
produtil.prog.FileOpener Class Reference
This is part of the internal implementation of Runner, used to convert it to a produtil.pipeline.Pipeline for execution.
Detailed Description
This is part of the internal implementation of Runner, used to convert it to a produtil.pipeline.Pipeline for execution.
It represents stdin, stdout or stderr being connected to an open file. It instructs the Runner to open the file before starting the process.
Definition at line 188 of file prog.py.
Public Member Functions
def __init__ (self, filename, mode, err=False)
FileOpener constructor.
def copy (self)
Creates a shallow copy of this object.
def to_shell (self)
Creates a POSIX sh representation of the part of the command that requests redirection.
def intmode (self)
Returns an integer version of mode suitable for os.open.
def __repr__ (self)
Returns a string representation of this object as valid Python code.
def repr_for_in (self)
Part of the implementation of Runner.__repr__, this returns the filename and ",string=False".
def repr_for_out (self)
Part of the implementation of Runner.__repr__, this returns the filename and ",string=False".
def repr_for_err (self)
Same as repr_for_out.
Public Member Functions inherited from produtil.prog.StreamGenerator
def for_input (self)
Has no effect.
def for_output (self)
Has no effect.
def repr_for_err (self)
Returns the stderr value.
Public Attributes
filename
the name of the file being opened
mode
how the file is being opened
err
If True, this is for stderr.
Constructor & Destructor Documentation
__init__()
def produtil.prog.FileOpener.__init__ (self, filename, mode, err = False)
FileOpener constructor.
Parameters
filename the name of the file being opened
mode how it is being opened
err if True, this is for stderr
Definition at line 194 of file prog.py.
Member Function Documentation
__repr__()
def produtil.prog.FileOpener.__repr__ (self)
Returns a string representation of this object as valid Python code.
Definition at line 242 of file prog.py.
Referenced by produtil.prog.Runner.__str__().
copy()
def produtil.prog.FileOpener.copy (self)
Creates a shallow copy of this object.
Definition at line 211 of file prog.py.
Referenced by produtil.prog.ImmutableRunner.runner(), and produtil.prog.Runner.to_shell().
repr_for_err()
def produtil.prog.FileOpener.repr_for_err (self)
Same as repr_for_out.
Definition at line 255 of file prog.py.
repr_for_in()
def produtil.prog.FileOpener.repr_for_in (self)
Part of the implementation of Runner.__repr__, this returns the filename and ",string=False".
Definition at line 246 of file prog.py.
repr_for_out()
def produtil.prog.FileOpener.repr_for_out (self)
Part of the implementation of Runner.__repr__, this returns the filename and ",string=False".
It also appends ",append=X" where X is the true/false flag for appending to the file.
Definition at line 250 of file prog.py.
Referenced by produtil.prog.StreamGenerator.repr_for_err(), and produtil.prog.FileOpener.repr_for_err().
to_shell()
def produtil.prog.FileOpener.to_shell (self)
Creates a POSIX sh representation of the part of the command that requests redirection.
Definition at line 214 of file prog.py.
Member Data Documentation
err
produtil.prog.FileOpener.err
If True, this is for stderr.
Definition at line 201 of file prog.py.
Referenced by produtil.prog.Runner.__init__(), produtil.prog.FileOpener.copy(), and produtil.prog.FileOpener.to_shell().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/produtil/prog.py