METplus: confdoc.parsefile Class Reference
confdoc.parsefile Class Reference
Config file parser.
Detailed Description
Config file parser.
Parses comment blocks as described in the confdoc.
Definition at line 566 of file confdoc.py.
Public Member Functions
def __init__ (self, filename, doc, maxread=500000)
Opens the specified file, prepares to parse.
def eot (self)
Have we run out of lines to parse?
def match (self, pattern)
Calls re.match(pattern,...) on the current line, returning the result.
def parse (self)
Loops over all lines, parsing text and sending the result to global variables.
def readoption (self, name)
Reads later lines of a multi-line option=value assignment.
def readblock (self)
Reads the second and later lines of a multi-line comment block.
Public Attributes
doc
lines
iline
Current line number counting from 0.
basename
Basename of the current file.
doxified
The basename with "." replaced with "_".
brief
Brief portion of description that has not yet been assigned to an option or section.
detail
Detailed portion of description that has not yet been assigned to an option or section.
section
Section being parsed.
value
Constructor & Destructor Documentation
__init__()
def confdoc.parsefile.__init__ (self, filename, doc, maxread = 500000)
Opens the specified file, prepares to parse.
Only the first maxread bytes are read.
Parameters
filename the *.conf file to read
doc the docbase object to receive documentation
maxread maximum number of lines to read
Definition at line 569 of file confdoc.py.
Member Function Documentation
match()
def confdoc.parsefile.match (self, pattern)
Calls re.match(pattern,...) on the current line, returning the result.
Parameters
pattern argument to re.match: the pattern to match
Definition at line 608 of file confdoc.py.
Referenced by confdoc.parsefile.parse(), confdoc.parsefile.readblock(), and confdoc.parsefile.readoption().
parse()
def confdoc.parsefile.parse (self)
Loops over all lines, parsing text and sending the result to global variables.
Definition at line 616 of file confdoc.py.
readblock()
def confdoc.parsefile.readblock (self)
Reads the second and later lines of a multi-line comment block.
Assumes data is already in the self.brief variable.
Definition at line 736 of file confdoc.py.
Referenced by confdoc.parsefile.parse().
readoption()
def confdoc.parsefile.readoption (self, name)
Reads later lines of a multi-line option=value assignment.
Parameters
name the option name
Definition at line 720 of file confdoc.py.
Referenced by confdoc.parsefile.parse().
Member Data Documentation
brief
confdoc.parsefile.brief
Brief portion of description that has not yet been assigned to an option or section.
Definition at line 581 of file confdoc.py.
Referenced by confdoc.parsefile.parse(), confdoc.parsefile.readblock(), and confdoc.parsefile.readoption().
detail
confdoc.parsefile.detail
Detailed portion of description that has not yet been assigned to an option or section.
Definition at line 582 of file confdoc.py.
Referenced by confdoc.parsefile.parse(), confdoc.parsefile.readblock(), and confdoc.parsefile.readoption().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/confdoc.py