METplus: produtil.testing.parsetree.EmbedBash Class Reference
produtil.testing.parsetree.EmbedBash Class Reference
Represents an embedded bash script.
Detailed Description
Represents an embedded bash script.
This is the implementation of the "embed bash [[[code]]]" block.
Definition at line 1921 of file parsetree.py.
Public Member Functions
def __init__ (self, defscopes)
Constructor for EmbedBash.
def __bool__ (self)
def validate_parameter (self, name)
Does nothing; this is a placeholder for variable name validation.
def bash_context (self, con)
Raises an exception to indicate that the bash script cannot be represented as a bash string.
def rescope (self, scopemap=None, prepend=None)
Modifies this object's scopes, and that of any subobjects.
def __str__ (self)
def __repr__ (self)
def apply_parameters (self, scope, con)
Implements a function call using this Scope as the parameter list.
def is_valid_rvalue (self, con)
Can this EmbedBash object be assigned to a variable?
def string_context (self, con)
Evaluates this EmbedBash in a string context.
def settemplate (self, template)
Sets the scope used for string expansion of the embedded bash script.
def gettemplate (self)
Returns the template that should be used for string expansion of the embedded bash script.
def numeric_context (self, con)
Executes the bash script, returning the result as a numeric value.
def bash_context (self, con)
Generates and returns a bash code block to run the embedded script with the script variables set to the function arguments.
def run (self, con)
Runs the script generated by bash_context()
def logical_context (self, con)
Executes this EmbedBash, returning True if the script returns a 0 status, and False otherwise.
def new_empty (self)
Creates a new, empty EmbedBash object defined in the same location (defining stack of Scope objects) as self.
Public Member Functions inherited from produtil.testing.parsetree.Scope
def __init__ (self, defscopes=None)
def __eq__ (self, other)
Scopes are equal iff they are the same object.
def override_local (self, defscopes, key, val)
Overrides a variable already defined in this scope or its subscopes.
def validate_parameter (self, name)
Raises an exception if the given name is not an acceptable keyword for constants or parameters.
def new_empty (self)
Returns a new, empty scope that is within the same parent scope of this Scope (has the same defscopes).
def bash_context (self, con)
Raises an exception to indicate that a Scope cannot be expressed in bash code.
def string_context (self, con)
Evaluates the _as_string variable in this scope, in a string context, if it is defined.
def no_nulls (self)
Are there any local variables defined to have null values?
def numeric_context (self, con)
Evaluates this scope in a numeric context.
def logical_context (self, con)
Evaluates this scope in a logical context.
def get_type (self, key)
Returns the type of variable that the key represents.
def as_parameters (self, con)
Changes all variables to parameters.
def rescope (self, scopemap=None, prepend=None)
Changes the context of this Scope.
def has_parameters (self)
Does this Scope contain parameters (function call arguments)?
def has_constants (self)
Are there any constants defined in this scope?
def use_from (self, used_scope, only_scalars=False)
Implements a "use" statement; copies definitions from another Scope.
def apply_parameters (self, scope, con)
Implements a function call using this Scope as the parameter list.
def __str__ (self)
def __repr__ (self)
def subscope (self, key)
Returns a Scope within this Scope, with the given name.
def getlocal (self, key)
Return the value of a key local to this scope without searching other scopes.
def setlocal (self, key, value)
Sets the value of a key within this scope.
def haslocal (self, key)
Is there a variable with this name?
def iterlocal (self)
Iterates over all local variables in this order: parameters, constants, variables.
def resolve (self, key, scopes=None)
Given a path to a variable, return the variable.
def force_define (self, key, value, skip_constants=False)
Sets the value of a variable, replacing the value if a variable is already defined with that name.
def check_define (self, key, value)
Defines a local variable, raising an exception if a variable is already defined with the given name.
def expand_string (self, string, con, scopes=None)
Performs string expansion.
Public Member Functions inherited from produtil.testing.parsetree.BaseObject
def __init__ (self, defscopes, set_flags=True)
Constructor for BaseObject.
def bash_context (self, con)
Expresses this object in bash code.
def oldcmp (self, other)
def is_valid_rvalue (self, con)
Can this value be assigned to a variable?
def string_context (self, con)
Expresses this object as a printable string.
def logical_context (self, con)
Expresses this object as a printable string.
def numeric_context (self, con)
Expresses this object as a float.
def rescope (self, scopemap=None, prepend=None)
Modifies this object's scopes, and that of any subobjects.
def run (self, con)
Instructs this object to execute.
def iterdeps (self)
Iterates over all runnable objects that are dependencies of this object.
def __repr__ (self)
def __str__ (self)
Protected Member Functions
def _apply_rescope (self, scopemap=None, prepend=None)
Replaces Scope objects in this object's defscopes variable.
Protected Member Functions inherited from produtil.testing.parsetree.Scope
def _apply_rescope (self, scopemap=None, prepend=None)
Internal implementation of rescope()
Protected Member Functions inherited from produtil.testing.parsetree.BaseObject
def _apply_rescope (self, scopemap=None, prepend=None)
Replaces Scope objects in this object's defscopes variable.
Additional Inherited Members
Public Attributes inherited from produtil.testing.parsetree.Scope
is_scope
can_be_used
Public Attributes inherited from produtil.testing.parsetree.BaseObject
defscopes
A list of Scope objects that represent the call stack at which this object is being called, or the stack to the context at which the object is being defined.
is_scope
If True, this object can be treated as a Scope.
is_filters
If True, this object can be treated as a set of filters.
is_criteria
If True, this object can be treated as a list of output validation criteria.
is_scalar
If True, this is a scalar, such as a number or string.
can_be_used
If True, this object is a valid target for a "use" statement.
is_test
If True, this object can be used as a Test.
Constructor & Destructor Documentation
__init__()
def produtil.testing.parsetree.EmbedBash.__init__ (self, defscopes)
Constructor for EmbedBash.
Parameters
defscopes a stack of Scope objects to the point at which this EmbedBash was defined, innermost Scope first
Definition at line 1924 of file parsetree.py.
Member Function Documentation
_apply_rescope()
def produtil.testing.parsetree.EmbedBash._apply_rescope (self, scopemap = None, prepend = None) protected
Replaces Scope objects in this object's defscopes variable.
This function is the internal implementation of the "use" blocks and function calls when parsing or evaluating. Subclasses with a rescope() or similar function use _apply_rescope() to implement such functions.
Parameters
scopemap A mapping from old Scope to new Scope
prepend A list of Scope objects to prepend to defscopes
Definition at line 1952 of file parsetree.py.
apply_parameters()
def produtil.testing.parsetree.EmbedBash.apply_parameters (self, scope, con)
Implements a function call using this Scope as the parameter list.
Creates a new Scope where all parameters in this scope are converted to local variables and possibly overridden. Scope self's parameters are used for the default argument values. The "scope" argument to apply_parameters() contains values to override those. Hence, self is the function definition and scope is the values set in the function call.
A third Scope is created, containing the result of applying the function call and default values. That third Scope has no parameters; all parameters have been converted to local values. The returned Scope has the same defscopes as self. That means any unresolved variables within the function will be resolved in the defining context, NOT the calling context.
Parameters
scope The arguments provided to the function call.
con the Context at which this function is being called. The defining location is in defscopes.
Returns
a Scope representing the function call.
Definition at line 1996 of file parsetree.py.
bash_context() [1/2]
def produtil.testing.parsetree.EmbedBash.bash_context (self, con)
Raises an exception to indicate that the bash script cannot be represented as a bash string.
Parameters
con the Context in which this object is being evaluated
Definition at line 1946 of file parsetree.py.
Referenced by produtil.testing.parsetree.EmbedBash.bash_context().
bash_context() [2/2]
def produtil.testing.parsetree.EmbedBash.bash_context (self, con)
Generates and returns a bash code block to run the embedded script with the script variables set to the function arguments.
Generates a bash code block that sets bash local variables variables to the calling arguments. Any variables whose names contain "." or "%" will not be set since they are not valid bash variable names. Next, the code block contains the embedded bash code. Finally, it will unset the local variables set in the first step.
Parameters
con the Context in which this object is being evaluated
Returns
the resulting bash code
Definition at line 2076 of file parsetree.py.
is_valid_rvalue()
def produtil.testing.parsetree.EmbedBash.is_valid_rvalue (self, con)
Can this EmbedBash object be assigned to a variable?
An EmbedBash definition and function call can always be assigned to a variable. However, the result of apply_parameters() (also an EmbedBash object) cannot be.
Returns
True if this EmbedBash can be assigned to a variable, or False otherwise.
Parameters
con the Context in which this object is being evaluated
Definition at line 2023 of file parsetree.py.
logical_context()
def produtil.testing.parsetree.EmbedBash.logical_context (self, con)
Executes this EmbedBash, returning True if the script returns a 0 status, and False otherwise.
Uses run() to execute this program, via numeric_context() to get the numeric return value.
Returns
True if the script return value was 0, False otherwise
Parameters
con the Context in which this object is being evaluated
Definition at line 2161 of file parsetree.py.
Referenced by produtil.testing.parsetree.EmbedBash.bash_context().
new_empty()
def produtil.testing.parsetree.EmbedBash.new_empty (self)
Creates a new, empty EmbedBash object defined in the same location (defining stack of Scope objects) as self.
Returns
the new EmbedBash
Definition at line 2172 of file parsetree.py.
rescope()
def produtil.testing.parsetree.EmbedBash.rescope (self, scopemap = None, prepend = None)
Modifies this object's scopes, and that of any subobjects.
Subclasses that can be expressed as non-constant values must implement this function for rescoping. This function changes the stack of defining scopes, defscopes, based on arguments
Parameters
scopemap a mapping from old Scope to new Scope during the replacement
prepend a list of Scope objects to prepend. These become the innermost scopes. The scopemap is NOT applied to the prepend list.
Returns
self
Definition at line 1967 of file parsetree.py.
Referenced by produtil.testing.parsetree.EmbedBash.apply_parameters(), and produtil.testing.parsetree.EmbedBash.new_empty().
run()
def produtil.testing.parsetree.EmbedBash.run (self, con)
Runs the script generated by bash_context()
Uses produtil.run.run() and produtil.run.exe() to execute this bash code block.
Returns
the result of produtil.run.run()
Note
Since produtil.run.exe() is used, the program will be run as a "large" or "compute" program. On Cray, this means the program will be run via "aprun," placing it on a compute node.
Parameters
con the Context in which this object is being evaluated @
Definition at line 2132 of file parsetree.py.
settemplate()
def produtil.testing.parsetree.EmbedBash.settemplate (self, template)
Sets the scope used for string expansion of the embedded bash script.
The embedded bash script's string expansion has a special Scope stack when it is evaluated.
Function arguments are searched first. These function arguments are the result of applying the function call arguments to the function definition argument list (and default arguments).
Defining scopes above the function definition are searched next.
The settemplate sets the Scope used for this search.
Parameters
template the calling context
Returns
None
Definition at line 2045 of file parsetree.py.
string_context()
def produtil.testing.parsetree.EmbedBash.string_context (self, con)
Evaluates this EmbedBash in a string context.
Executes this EmbedBash via run(), converts the result to a number (via numeric_context()) and then to a string via "%d"
Parameters
con the Context in which this object is being evaluated
Returns
the string copy of the numeric result of run()
Definition at line 2035 of file parsetree.py.
validate_parameter()
def produtil.testing.parsetree.EmbedBash.validate_parameter (self, name)
Does nothing; this is a placeholder for variable name validation.
This function analyzes the given variable name and raises an exception if the variable name is invalid. Presently, any variable name is valid, so this function is a no-op. However, any variable name that contains a period (".") will not be passed in to generated bash code as a bash variable.
Parameters
name the name of a new parameter (function argument) to validate.
Returns
None
Definition at line 1931 of file parsetree.py.
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/produtil/testing/parsetree.py