METplus: pb2nc_wrapper.PB2NCWrapper Class Reference
pb2nc_wrapper.PB2NCWrapper Class Reference
Wrapper to the MET tool pb2nc which converts prepbufr files to NetCDF for MET's point_stat tool can recognize.
Detailed Description
Wrapper to the MET tool pb2nc which converts prepbufr files to NetCDF for MET's point_stat tool can recognize.
Definition at line 25 of file pb2nc_wrapper.py.
Public Member Functions
def __init__ (self, config, logger)
def create_c_dict (self)
Create a data structure (dictionary) that contains all the values set in the configuration files.
def reformat_grid_id (self, grid_id)
Reformat the grid id (MASK_GRID value in the configuration file) if it starts with G.
def set_environment_variables (self, time_info)
Set environment variables that will be read by the MET config file.
def find_input_files (self, input_dict)
Find prepbufr data to convert.
def set_valid_window_variables (self, time_info)
def run_at_time (self, input_dict)
Loop over each forecast lead and build pb2nc command.
def run_at_time_once (self, input_dict)
Find files needed to run pb2nc and run if found.
def get_command (self)
Builds the command to run the MET application string.
Public Member Functions inherited from command_builder.CommandBuilder
def __init__ (self, config, logger)
def create_c_dict (self)
def clear (self)
Unset class variables to prepare for next run time.
def log_error (self, error_string)
def set_user_environment (self, time_info=None)
Set environment variables defined in [user_env_vars] section of config.
def add_common_envs (self, time_info=None)
def print_all_envs (self)
def handle_window_once (self, c_dict, dtype, edge, app_name)
Check and set window dictionary variables like OBS_WINDOW_BEG or FCST_FILE_WINDW_END Args:
def handle_window_variables (self, c_dict, app_name, dtypes=['FCST', OBS)
Handle all window config variables like [FCST/OBS]_<app_name>_WINDOW_[BEGIN/END] and [FCST/OBS]_<app_name>_FILE_WINDOW_[BEGIN/END] Args:
def set_output_path (self, outpath)
Split path into directory and filename then save both.
def get_output_path (self)
Combine output directory and filename then return result.
def add_env_var (self, key, name)
Sets an environment variable so that the MET application can reference it in the parameter file or the application itself.
def print_env (self)
Print all environment variables set for this application.
def print_env_copy (self, var_list=None)
def get_env_copy (self, var_list=None)
Print list of environment variables that can be easily copied into terminal.
def print_env_item (self, item)
Print single environment variable in the log file.
def print_user_env_items (self)
Prints user environment variables in the log file.
def handle_fcst_and_obs_field (self, gen_name, fcst_name, obs_name, default=None, sec='config')
Handles config variables that have fcst/obs versions or a generic variable to handle both, i.e.
def find_model (self, time_info, var_info, mandatory=True, return_list=False)
Finds the model file to compare Args:
def find_obs (self, time_info, var_info, mandatory=True, return_list=False)
Finds the observation file to compare Args:
def find_data (self, time_info, var_info, data_type, mandatory=True, return_list=False)
Finds the data file to compare Args:
def find_exact_file (self, level, data_type, time_info, mandatory=True, return_list=False)
def find_file_in_window (self, level, data_type, time_info, mandatory=True, return_list=False)
def write_list_file (self, filename, file_list)
Writes a file containing a list of filenames to the staging dir.
def find_and_check_output_file (self, time_info)
Look for expected output file.
def format_list_string (self, list_string)
Add quotation marks around each comma separated item in the string.
def check_for_externals (self)
def check_for_gempak (self)
def check_gempaktocf (self, gempaktocf_jar)
def get_output_prefix (self, time_info)
def check_for_python_embedding (self, input_type, var_info)
Check if field name of given input type is a python script.
def get_command (self)
Builds the command to run the MET application string.
def build_and_run_command (self)
def build (self)
Build and run command.
def run_at_time (self, input_dict)
Used to output error and exit if wrapper is attemped to be run with LOOP_ORDER = times and the run_at_time method is not implemented.
def run_all_times (self)
Loop over time range specified in conf file and call METplus wrapper for each time.
Public Attributes
app_name
app_path
isOK
outfile
outdir
Public Attributes inherited from command_builder.CommandBuilder
isOK
errors
logger
config
env_list
debug
args
input_dir
infiles
outdir
outfile
param
env
c_dict
cmdrunner
Member Function Documentation
create_c_dict()
def pb2nc_wrapper.PB2NCWrapper.create_c_dict (self)
Create a data structure (dictionary) that contains all the values set in the configuration files.
Args:
Returns: c_dict - a dictionary containing the settings in the configuration files (that aren't in the metplus_data, metplus_system, and metplus_runtime config files.
Definition at line 36 of file pb2nc_wrapper.py.
find_input_files()
def pb2nc_wrapper.PB2NCWrapper.find_input_files (self, input_dict)
Find prepbufr data to convert.
If file(s) are found, return timing information dictionary containing offset information of input file. Return None otherwise
Definition at line 213 of file pb2nc_wrapper.py.
Referenced by series_analysis_wrapper.SeriesAnalysisWrapper.run_at_time(), and pb2nc_wrapper.PB2NCWrapper.run_at_time_once().
get_command()
def pb2nc_wrapper.PB2NCWrapper.get_command (self)
Builds the command to run the MET application string.
Returns
Returns a MET command with arguments that you can run
Definition at line 329 of file pb2nc_wrapper.py.
reformat_grid_id()
def pb2nc_wrapper.PB2NCWrapper.reformat_grid_id (self, grid_id)
Reformat the grid id (MASK_GRID value in the configuration file) if it starts with G.
Looks for G<n> where n is a digit 0-999 and zero pads the value. i.e. G7 becomes G007, G13 becomes G013, etc. Args:
Parameters
grid_id identifier of grid Returns:
Returns
reformatted grid id if valid, None if not
Definition at line 152 of file pb2nc_wrapper.py.
Referenced by pb2nc_wrapper.PB2NCWrapper.create_c_dict().
set_environment_variables()
def pb2nc_wrapper.PB2NCWrapper.set_environment_variables (self, time_info)
Set environment variables that will be read by the MET config file.
Reformat as needed. Print list of variables that were set and their values. Args:
Parameters
time_info dictionary containing timing info from current run
Definition at line 179 of file pb2nc_wrapper.py.
Referenced by tc_pairs_wrapper.TCPairsWrapper.run_all_times(), tc_pairs_wrapper.TCPairsWrapper.run_at_time_loop_string(), and pb2nc_wrapper.PB2NCWrapper.run_at_time_once().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/pb2nc_wrapper.py