METplus: produtil.prog.OutIsError Class Reference
produtil.prog.OutIsError Class Reference
Instructs a Runner to send stderr to stdout.
Detailed Description
Instructs a Runner to send stderr to stdout.
Definition at line 325 of file prog.py.
Public Member Functions
def __init__ (self)
OutIsError constructor.
def copy (self)
Returns a new OutIsError object.
def to_shell (self)
Returns "2>&1".
def repr_for_in (self)
This should never be called.
def repr_for_out (self)
Part of the representation of Runner.__repr__.
def __eq__ (self, other)
Is the other object an OutIsError?
Public Member Functions inherited from produtil.prog.StreamGenerator
def for_input (self)
Has no effect.
def for_output (self)
Has no effect.
def repr_for_err (self)
Returns the stderr value.
Constructor & Destructor Documentation
__init__()
def produtil.prog.OutIsError.__init__ (self)
OutIsError constructor.
Definition at line 327 of file prog.py.
Member Function Documentation
__eq__()
def produtil.prog.OutIsError.__eq__ (self, other)
Is the other object an OutIsError?
Parameters
other the other object to analyze.
Definition at line 346 of file prog.py.
copy()
def produtil.prog.OutIsError.copy (self)
Returns a new OutIsError object.
Definition at line 329 of file prog.py.
Referenced by produtil.prog.ImmutableRunner.runner(), and produtil.prog.Runner.to_shell().
repr_for_in()
def produtil.prog.OutIsError.repr_for_in (self)
This should never be called.
It returns ".err2out()".
Definition at line 338 of file prog.py.
repr_for_out()
def produtil.prog.OutIsError.repr_for_out (self)
Part of the representation of Runner.__repr__.
Returns ".err2out()" which instructs a Runner to send stderr to stdout.
Definition at line 341 of file prog.py.
Referenced by produtil.prog.StreamGenerator.repr_for_err().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/produtil/prog.py