METplus: produtil.testing.rocoto.RocotoWorkflow Class Reference
produtil.testing.rocoto.RocotoWorkflow Class Reference
Represents a Rocoto workflow, and creates the files needed to run one.
Detailed Description
Represents a Rocoto workflow, and creates the files needed to run one.
Definition at line 227 of file rocoto.py.
Public Member Functions
def __init__ (self, name, scope, mode)
Constructor for RocotoWorkflow.
def generate_install_script (self)
Generates the contents of the sorc/install.sh script.
def generate_uninstall_script (self)
Generates the contents of the sorc/uninstall.sh script.
def has_builds (self)
Does this RocotoWorkflow contain any produtil.testing.parsetree.Build objects?
def getvar (self, var, default=NODEFAULT)
Resolves the specified variable reference within the global scope.
def as_attr (self, var, con)
Resolves the specified variable reference in the given context and returns its value quoted for an XML attribute.
def run (self, obj, con)
Adds a RocotoTask to the RocotoWorkflow.
def run_test (self, test, con)
Adds the given produtil.testing.parsetree.Test to this RocotoWorkflow as a test to execute.
def run_build (self, build, con)
Adds a build from the given produtil.testing.parsetree.Build to this RocotoWorkflow as an executable to build.
def add_file (self, path, contents)
Adds a file to the list of files that will be generated.
def add_build (self, buildname)
Adds the given build name to the list of known build names.
def add_test (self, taskname, obj)
Adds the given produtil.testing.parsetree.Test to this RocotoWorkflow as a RocotoTask.
def iter_buildnames (self)
Iterates over build names.
def iter_paths (self)
Iterates over paths to files that must be generated.
def iter_testnames (self)
Iterates over names of tests.
def iter_files (self)
Iterates over files to be generated, yielding tuples containing the path and contents.
def iter_tests (self)
Iterates over all RocotoTasks for tests to run, yielding a tuple containing the test name and RocotoTask.
def as_walltime (self, time, con)
Resolves the given numeric variable and turns it into a Rocoto-style wallclock time.
def install_dir (self, con)
Returns the directory in which to install the generated workflow.
def make_prep_baseline_sh (self, con)
Creates a script that prepares the baseline when run in baseline generation mode.
def generate_xml (self, out, con)
Generates the Rocoto workflow document.
Public Attributes
name
mode
NAME
cycle
Constructor & Destructor Documentation
__init__()
def produtil.testing.rocoto.RocotoWorkflow.__init__ (self, name, scope, mode)
Constructor for RocotoWorkflow.
Parameters
name The name of the workflow.
scope The global scope from produtil.testing.parser.Parse
mode the run mode: produtil.testing.utilities.BASELINE or produtil.testing.utilities.EXECUTION
Definition at line 230 of file rocoto.py.
Member Function Documentation
add_build()
def produtil.testing.rocoto.RocotoWorkflow.add_build (self, buildname)
Adds the given build name to the list of known build names.
Parameters
buildname the name of the build; this is used in the executable names, module name, and arguments to install.sh and uninstall.sh
Definition at line 414 of file rocoto.py.
Referenced by produtil.testing.rocoto.RocotoWorkflow.run_build().
add_file()
def produtil.testing.rocoto.RocotoWorkflow.add_file (self, path, contents)
Adds a file to the list of files that will be generated.
Parameters
path the path to the file
contents the text to write to the file
Definition at line 404 of file rocoto.py.
add_test()
def produtil.testing.rocoto.RocotoWorkflow.add_test (self, taskname, obj)
Adds the given produtil.testing.parsetree.Test to this RocotoWorkflow as a RocotoTask.
Parameters
testname The string name of the test.
test A produtil.testing.parsetree.Test representing the test to run.
Returns
the resulting RocotoTask
Definition at line 423 of file rocoto.py.
Referenced by produtil.testing.rocoto.RocotoWorkflow.run_test().
as_attr()
def produtil.testing.rocoto.RocotoWorkflow.as_attr (self, var, con)
Resolves the specified variable reference in the given context and returns its value quoted for an XML attribute.
Calls getvar() to resolve the variable, and expresses it within a string context. Quotes the resulting string for an XML attribute.
See also
as_xml_attr()
produtil.testing.parsetree.BaseObject.string_context()
produtil.testing.parsetree.Context
Definition at line 303 of file rocoto.py.
Referenced by produtil.testing.rocoto.RocotoWorkflow.generate_xml().
as_walltime()
def produtil.testing.rocoto.RocotoWorkflow.as_walltime (self, time, con)
Resolves the given numeric variable and turns it into a Rocoto-style wallclock time.
Parameters
time the variable reference
con a produtil.testing.parsetree.Context to use when resolving variables.
Definition at line 461 of file rocoto.py.
Referenced by produtil.testing.rocoto.RocotoWorkflow.generate_xml().
generate_install_script()
def produtil.testing.rocoto.RocotoWorkflow.generate_install_script (self)
Generates the contents of the sorc/install.sh script.
Constructs a script that knows how to build any of the possible build targets. This is the contents of the sorc/install.sh script.
Returns
The resulting script, as a string.
Definition at line 260 of file rocoto.py.
generate_uninstall_script()
def produtil.testing.rocoto.RocotoWorkflow.generate_uninstall_script (self)
Generates the contents of the sorc/uninstall.sh script.
Constructs a script that knows how to uninstall any of the possible build targets. This is the contents of the sorc/uninstall.sh script.
Returns
The resulting script, as a string.
Definition at line 273 of file rocoto.py.
generate_xml()
def produtil.testing.rocoto.RocotoWorkflow.generate_xml (self, out, con)
Generates the Rocoto workflow document.
Writes the contents of the Rocoto XML document to the given file-like stream.
Parameters
out a file-like stream to which the document will be written.
con a produtil.testing.parsetree.Context to use when resolving variables.
Returns
None
Definition at line 504 of file rocoto.py.
getvar()
def produtil.testing.rocoto.RocotoWorkflow.getvar (self, var, default = NODEFAULT)
Resolves the specified variable reference within the global scope.
Parameters
var A variable reference, such as "varname" or "scope1%scope2%varname"
Returns
The value of the variable as a produtil.testing.parsetree.BaseObject or subclass thereof.
Definition at line 290 of file rocoto.py.
Referenced by produtil.testing.rocoto.RocotoWorkflow.as_attr(), produtil.testing.rocoto.RocotoWorkflow.as_walltime(), produtil.testing.rocoto.RocotoWorkflow.generate_xml(), produtil.testing.rocoto.RocotoWorkflow.install_dir(), and produtil.testing.rocoto.RocotoWorkflow.make_prep_baseline_sh().
install_dir()
def produtil.testing.rocoto.RocotoWorkflow.install_dir (self, con)
Returns the directory in which to install the generated workflow.
Gets the installation area for the created workflow from "plat%rocoto%install_dir", expressed in a string context. This is the top-level installation directory; the parent of ush/, jobs/, etc.
Parameters
con a produtil.testing.parsetree.Context to use when resolving variables.
Returns
the directory in which to install the workflow
Definition at line 471 of file rocoto.py.
iter_buildnames()
def produtil.testing.rocoto.RocotoWorkflow.iter_buildnames (self)
Iterates over build names.
Definition at line 439 of file rocoto.py.
Referenced by produtil.testing.rocoto.RocotoWorkflow.generate_xml().
iter_files()
def produtil.testing.rocoto.RocotoWorkflow.iter_files (self)
Iterates over files to be generated, yielding tuples containing the path and contents.
Definition at line 451 of file rocoto.py.
iter_paths()
def produtil.testing.rocoto.RocotoWorkflow.iter_paths (self)
Iterates over paths to files that must be generated.
Definition at line 443 of file rocoto.py.
iter_testnames()
def produtil.testing.rocoto.RocotoWorkflow.iter_testnames (self)
Iterates over names of tests.
Definition at line 447 of file rocoto.py.
iter_tests()
def produtil.testing.rocoto.RocotoWorkflow.iter_tests (self)
Iterates over all RocotoTasks for tests to run, yielding a tuple containing the test name and RocotoTask.
Definition at line 456 of file rocoto.py.
Referenced by produtil.testing.rocoto.RocotoWorkflow.generate_xml().
make_prep_baseline_sh()
def produtil.testing.rocoto.RocotoWorkflow.make_prep_baseline_sh (self, con)
Creates a script that prepares the baseline when run in baseline generation mode.
Parameters
con a produtil.testing.parsetree.Context to use when resolving variables.
Returns
the resulting script as a string
Definition at line 485 of file rocoto.py.
run()
def produtil.testing.rocoto.RocotoWorkflow.run (self, obj, con)
Adds a RocotoTask to the RocotoWorkflow.
Parameters
obj a produtil.testing.parsetree.Test or produtil.testing.parsetree.Build for which the RocotoTask is to be constructed.
con a produtil.testing.parsetree.Context to use when resolving variables.
Definition at line 318 of file rocoto.py.
run_build()
def produtil.testing.rocoto.RocotoWorkflow.run_build (self, build, con)
Adds a build from the given produtil.testing.parsetree.Build to this RocotoWorkflow as an executable to build.
Parameters
test The produtil.testing.parsetree.Build representing the executable to build
con a produtil.testing.parsetree.Context to use when resolving variables.
Definition at line 344 of file rocoto.py.
Referenced by produtil.testing.rocoto.RocotoWorkflow.run().
run_test()
def produtil.testing.rocoto.RocotoWorkflow.run_test (self, test, con)
Adds the given produtil.testing.parsetree.Test to this RocotoWorkflow as a test to execute.
Parameters
test A produtil.testing.parsetree.Test representing the test to run.
con a produtil.testing.parsetree.Context to use when resolving variables.
Definition at line 334 of file rocoto.py.
Referenced by produtil.testing.rocoto.RocotoWorkflow.run().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/produtil/testing/rocoto.py