METplus: confdoc.docbase Class Reference
confdoc.docbase Class Reference
Stores documentation for all configuration options and sections.
Detailed Description
Stores documentation for all configuration options and sections.
Definition at line 57 of file confdoc.py.
Public Member Functions
def __init__ (self)
docbase constructor
def set_subdoc (self, basename, doc)
Sets the documentation object that will contain file-specific information for the given file.
def fileanch (self, basename)
Returns the anchor for a configuration file.
def secanch (self, section, where='sec')
Returns the anchor for a specified section.
def optanch (self, section, option, where='sec')
Returns the anchor for a specified option.
def make_brief (self, detail)
Given a detailed description for something that has no brief description, return the brief description.
def add_section (self, section, brief, detail, replace=None)
Adds documentation for a conf section.
def section_inc (self, section, inc)
Sets the @inc list for a conf section.
def file_block (self, basename, brief, detail)
Adds a documentation block that is not associated with any section or option.
def add_option (self, section, option, ivalue, brief, detail, basename=None, replace=None)
Adds documentation for an option in a conf section.
def print_doc (self, s)
Writes Doxygen documentation to the stream "s" which is assumed to be a io.StringIO.
Public Attributes
sections
Mapping of section name to description.
secref
Mapping from section name to anchor name.
secrefset
secfile
Mapping from doxified filename to list of sections in that file.
secinc
Mapping from section name to the list of sections that are @inc included by that section.
seclist
List of section names, in the order they were first seen.
options
Mapping from option anchor name to the description of the option.
optbrief
Mapping from option anchor to the option's brief description.
secbrief
Mapping from section name to the section's brief description.
fileset
filelist
blocks
Mapping from file basename to the list of documentation blocks in that file that were not associated with any section or option.
Constructor & Destructor Documentation
__init__()
def confdoc.docbase.__init__ (self)
docbase constructor
Initializes the documentation to an empty configuration suite. No sections, no options, no files, etc.
Definition at line 59 of file confdoc.py.
Member Function Documentation
add_option()
def confdoc.docbase.add_option (self, section, option, ivalue, brief, detail, basename = None, replace = None)
Adds documentation for an option in a conf section.
Parameters
section The conf section name
option The name of the option in that section
ivalue A shortened form of the option value
brief The brief documentation
detail The detailed documentation
basename The file basename
replace If True, any existing documentation is replaced. Otherwise, it is ignored.
Definition at line 253 of file confdoc.py.
add_section()
def confdoc.docbase.add_section (self, section, brief, detail, replace = None)
Adds documentation for a conf section.
Parameters
section The conf section name
brief The brief documentation
detail The detailed documentation or None
replace If True, any existing documentation is replaced. Otherwise, it is ignored.
Definition at line 206 of file confdoc.py.
Referenced by confdoc.docbase.print_doc().
file_block()
def confdoc.docbase.file_block (self, basename, brief, detail)
Adds a documentation block that is not associated with any section or option.
Parameters
basename the file that contains the block
brief the brief documentation
detail the detailed documentation
Definition at line 238 of file confdoc.py.
fileanch()
def confdoc.docbase.fileanch (self, basename)
Returns the anchor for a configuration file.
Parameters
basename the basename of the configuration file.
Definition at line 119 of file confdoc.py.
Referenced by confdoc.docbase.optanch().
make_brief()
def confdoc.docbase.make_brief (self, detail)
Given a detailed description for something that has no brief description, return the brief description.
Parameters
detail the detailed description
Returns
A brief description, or None if no suitable description was found.
Definition at line 191 of file confdoc.py.
Referenced by confdoc.docbase.add_section().
optanch()
def confdoc.docbase.optanch (self, section, option, where = 'sec')
Returns the anchor for a specified option.
Parameters
section The conf file section name.
option The option name.
where Configuration override file name. Default: "sec" which is the special name used for the page that stores information about ALL configuration options.
Definition at line 133 of file confdoc.py.
Referenced by confdoc.docbase.add_option(), confdoc.override.find_optbrief(), and confdoc.docbase.optanch().
print_doc()
def confdoc.docbase.print_doc (self, s)
Writes Doxygen documentation to the stream "s" which is assumed to be a io.StringIO.
Parameters
s a io.StringIO to receive documentation.
Definition at line 279 of file confdoc.py.
secanch()
def confdoc.docbase.secanch (self, section, where = 'sec')
Returns the anchor for a specified section.
Parameters
section The conf file section name.
where Configuration override file name. Default: "sec" which is the special name used for the page that stores information about ALL configuration options.
Definition at line 124 of file confdoc.py.
Referenced by confdoc.docbase.add_section(), confdoc.docbase.optanch(), and confdoc.override.print_sec_opt().
section_inc()
def confdoc.docbase.section_inc (self, section, inc)
Sets the @inc list for a conf section.
Parameters
section The conf section name
inc The contents of the @inc= option
Definition at line 227 of file confdoc.py.
set_subdoc()
def confdoc.docbase.set_subdoc (self, basename, doc)
Sets the documentation object that will contain file-specific information for the given file.
Parameters
basename The file basename
doc The documentation object, a subclass of docbase
Definition at line 78 of file confdoc.py.
Referenced by confdoc.override.__init__().
Member Data Documentation
blocks
confdoc.docbase.blocks
Mapping from file basename to the list of documentation blocks in that file that were not associated with any section or option.
These blocks are placed at the top of that file's documentation page.
Definition at line 76 of file confdoc.py.
Referenced by confdoc.docbase.file_block(), and confdoc.docbase.print_doc().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/confdoc.py