METplus: produtil.mpiprog.MPIRanksSPMD Class Reference
produtil.mpiprog.MPIRanksSPMD Class Reference
Represents one MPI program duplicated across many ranks.
Detailed Description
Represents one MPI program duplicated across many ranks.
Definition at line 464 of file mpiprog.py.
Public Member Functions
def __init__ (self, mpirank, count)
MPIRanksSPMD constructor.
def env (self, kwargs)
def getranks_per_node (self)
Returns the number of MPI ranks per node requsted by this MPI rank, or 0 if unspecified.
def setranks_per_node (self, rpn)
Sets the number of MPI ranks per node requsted by this MPI rank.
def delranks_per_node (self)
Unsets the requested number of ranks per node.
def setturbomode (self, tm)
def getturbomode (self)
def delturbomode (self)
def setlocalopts (self, localopts)
def addlocalopts (self, localopts)
def addlocalopt (self, localopt)
def make_runners_immutable (self)
Returns a new MPIRanksSPMD with an immutable version of self._mpirank.
def __repr__ (self)
Returns "X*N" where X is the MPI program and N is the number of ranks.
def ngroups (self)
Returns 1 or 0: 1 if there are ranks and 0 if there are none.
def groups (self, threads=False)
Yields a tuple (X,N) where X is the mpi program and N is the number of ranks.
def copy (self)
Returns a deep copy of self.
def ranks (self)
Iterates over MPI ranks within self.
def nranks (self)
Returns the number of ranks this program requests.
def __mul__ (self, factor)
Multiply the number of requested ranks by some factor.
def __rmul__ (self, factor)
Multiply the number of requested ranks by some factor.
def __add__ (self, other)
Add some new ranks to self.
def check_serial (self)
Checks to see if this program contains serial (non-MPI) or MPI components.
def get_logger (self)
Returns my MPI program's logger.
Public Member Functions inherited from produtil.mpiprog.MPIRanksBase
def to_arglist (self, to_shell=False, expand=False, shell_validate=None, pre=[], before=[], between=[], after=[], post=[], extra={}, include_localopts=False)
This is the underlying implementation of most of the mpi_impl modules, and hence make_runner as well.
def haslocalopts (self)
Returns True if setlocalopts(), addlocalopts() or addlocalopt() was called to add localopt values.
def setlocalopts (self, localopts)
Sets MPI options that are only meaningful to the currently used MPI configuration.
def addlocalopts (self, localopts)
Adds MPI options that are only meaningful to the currently used MPI configuration.
def addlocalopt (self, localopts)
Adds one MPI option to the local option list.
def localoptiter (self)
Iterates over local MPI configuration options for this rank or group of ranks.
def mixedlocalopts (self)
Do the MPI ranks within this group contain mixed values for local options?
def samelocalopts (self, other)
def getturbomode (self)
Do we want turbo mode to be enabled for this set of ranks?
def setturbomode (self, tm)
Sets the turbo mode setting: on (True) or off (False).
def delturbomode (self, tm)
Removes the request for turbo mode to be on or off.
def turbo (self, flag=True)
def rpn (self, count=0)
def env (self, kwargs)
Sets environment variables in the individual MPI ranks.
def make_runners_immutable (self)
Returns a copy of this object where all child produtil.prog.Runner objects have been replaced with produtil.prog.ImmutableRunner objects.
def get_logger (self)
Returns a logger.Logger object for this MPIRanksBase or one from its child MPIRanksBase objects (if it has any).
def check_serial (self)
Returns a tuple (s,p) where s=True if there are serial ranks in this part of the MPI program, and p=True if there are parallel ranks.
def getranks_per_node (self)
Returns the number of MPI ranks per node requsted by this MPI rank, or 0 if unspecified.
def setranks_per_node (self, rpn)
Sets the number of MPI ranks per node requsted by this MPI rank.
def delranks_per_node (self)
Unsets the requested number of ranks per node.
def nranks (self)
Returns the number of ranks in this part of the MPI program.
def ranks (self)
Iterates over all MPIRank objects in this part of the MPI program.
def ngroups (self)
Returns the number of groups of repeated MPI ranks in the MPI program.
def groups (self, threads=False)
Iterates over all groups of repeating MPI ranks in the MPI program returning tuples (r,c) containing a rank r and the count (number) of that rank c.
def getthreads (self)
Returns the number of threads requested by this MPI rank, or by each MPI rank in this group of MPI ranks.
def nonzero_threads (self)
The number of threads requested, or 1 if no threads are requested.
def setthreads (self, nthreads)
Sets the number of threads requested by each MPI rank within this group of MPI ranks.
def delthreads (self)
Removes the request for threads.
def __mul__ (self, factor)
Returns a new set of MPI ranks that consist of this group of ranks repeated "factor" times.
def __rmul__ (self, other)
Returns a new set of MPI ranks that consist of this group of ranks repeated "factor" times.
def __add__ (self, other)
Returns a new set of MPI ranks that consist of this set of ranks with the "other" set appended.
def __radd__ (self, other)
Returns a new set of MPI ranks that consist of the "other" set of ranks with this set appended.
def isplainexe (self)
Determines if this set of MPI ranks can be represented by a single serial executable with a single set of arguments run without MPI.
def to_shell (self)
Returns a POSIX sh command that will execute the serial program, if possible, or raise a subclass of NotValidPosixSh otherwise.
def expand_iter (self, expand, threads=False)
This is a wrapper around ranks() and groups() which will call self.groups() if expand=False.
def __repr__ (self)
Returns a string representation of this object intended for debugging.
def __eq__ (self, other)
Static Public Attributes
ranks_per_node
turbomode
Static Public Attributes inherited from produtil.mpiprog.MPIRanksBase
turbomode
ranks_per_node
The number of MPI ranks per node or 0 if no specific request is made.
threads
Constructor & Destructor Documentation
__init__()
def produtil.mpiprog.MPIRanksSPMD.__init__ (self, mpirank, count)
MPIRanksSPMD constructor.
Parameters
mpirank the program to run
count how many times to run it
Definition at line 466 of file mpiprog.py.
Member Function Documentation
__add__()
def produtil.mpiprog.MPIRanksSPMD.__add__ (self, other)
Add some new ranks to self.
If they are not identical to the MPI program presently requested, this returns a new MPIRanksMPMD.
Definition at line 584 of file mpiprog.py.
__mul__()
def produtil.mpiprog.MPIRanksSPMD.__mul__ (self, factor)
Multiply the number of requested ranks by some factor.
Definition at line 574 of file mpiprog.py.
__repr__()
def produtil.mpiprog.MPIRanksSPMD.__repr__ (self)
Returns "X*N" where X is the MPI program and N is the number of ranks.
Definition at line 527 of file mpiprog.py.
Referenced by produtil.prog.Runner.__str__().
__rmul__()
def produtil.mpiprog.MPIRanksSPMD.__rmul__ (self, factor)
Multiply the number of requested ranks by some factor.
Definition at line 579 of file mpiprog.py.
check_serial()
def produtil.mpiprog.MPIRanksSPMD.check_serial (self)
Checks to see if this program contains serial (non-MPI) or MPI components.
Returns
a tuple (serial,parallel) where serial is True if there are serial components, and parallel is True if there are parallel components. If there are no components, returns (False,False)
Definition at line 605 of file mpiprog.py.
copy()
def produtil.mpiprog.MPIRanksSPMD.copy (self)
Returns a deep copy of self.
Definition at line 556 of file mpiprog.py.
Referenced by produtil.mpiprog.MPIRanksSPMD.__add__(), produtil.mpiprog.MPIRank.__add__(), produtil.mpiprog.MPISerial.__add__(), produtil.mpiprog.MPIRank.__getitem__(), produtil.mpiprog.MPIRanksSPMD.__mul__(), produtil.mpiprog.MPIRanksSPMD.__rmul__(), produtil.prog.ImmutableRunner.runner(), and produtil.prog.Runner.to_shell().
delranks_per_node()
def produtil.mpiprog.MPIRanksSPMD.delranks_per_node (self)
Unsets the requested number of ranks per node.
Definition at line 491 of file mpiprog.py.
get_logger()
def produtil.mpiprog.MPIRanksSPMD.get_logger (self)
Returns my MPI program's logger.
Definition at line 616 of file mpiprog.py.
getranks_per_node()
def produtil.mpiprog.MPIRanksSPMD.getranks_per_node (self)
Returns the number of MPI ranks per node requsted by this MPI rank, or 0 if unspecified.
Definition at line 481 of file mpiprog.py.
groups()
def produtil.mpiprog.MPIRanksSPMD.groups (self, threads = False)
Yields a tuple (X,N) where X is the mpi program and N is the number of ranks.
Definition at line 549 of file mpiprog.py.
make_runners_immutable()
def produtil.mpiprog.MPIRanksSPMD.make_runners_immutable (self)
Returns a new MPIRanksSPMD with an immutable version of self._mpirank.
Definition at line 523 of file mpiprog.py.
ngroups()
def produtil.mpiprog.MPIRanksSPMD.ngroups (self)
Returns 1 or 0: 1 if there are ranks and 0 if there are none.
Definition at line 543 of file mpiprog.py.
nranks()
def produtil.mpiprog.MPIRanksSPMD.nranks (self)
Returns the number of ranks this program requests.
Definition at line 568 of file mpiprog.py.
ranks()
def produtil.mpiprog.MPIRanksSPMD.ranks (self)
Iterates over MPI ranks within self.
Definition at line 563 of file mpiprog.py.
setranks_per_node()
def produtil.mpiprog.MPIRanksSPMD.setranks_per_node (self, rpn)
Sets the number of MPI ranks per node requsted by this MPI rank.
Definition at line 486 of file mpiprog.py.
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/produtil/mpiprog.py