METplus: compare_gridded_wrapper.CompareGriddedWrapper Class Reference
compare_gridded_wrapper.CompareGriddedWrapper Class Reference
Common functionality to wrap similar MET applications that reformat gridded data.
Detailed Description
Common functionality to wrap similar MET applications that reformat gridded data.
Definition at line 30 of file compare_gridded_wrapper.py.
Public Member Functions
def __init__ (self, config, logger)
def create_c_dict (self)
Create dictionary from config items to be used in the wrapper Allows developer to reference config items without having to know the type and consolidates config get calls so it is easier to see which config variables are used in the wrapper.
def check_probabilistic_settings (self)
If dataset is probabilistic, check if *_PROB_IN_GRIB_PDS or INPUT_DATATYPE are set.
def set_climo_env_vars (self)
Set all climatology environment variables from CLIMO_<item>_FILE c_dict values if they are not set to None.
def read_climo_wrapper_specific (self, met_tool, c_dict)
Read climatology directory and template values for specific MET tool specified and set the values in c_dict.
def handle_climo (self, time_info)
Substitute time information into all climatology template values.
def handle_climo_file_item (self, time_info, climo_item)
Handle a single climatology value by substituting time information, prepending input directory if provided, and preprocessing file if necessary.
def run_at_time (self, input_dict)
Runs the MET application for a given run time.
def run_at_time_once (self, time_info)
Build MET command for a given init/valid time and forecast lead combination Args:
def run_at_time_one_field (self, time_info, var_info)
Build MET command for a single field for a given init/valid time and forecast lead combination Args:
def run_at_time_all_fields (self, time_info)
Build MET command for all of the field/level combinations for a given init/valid time and forecast lead combination Args:
def get_field_info (self, v_name, v_level, v_thresh, v_extra, d_type)
Format field information into format expected by MET config file Args:
def set_environment_variables (self, fcst_field, obs_field, time_info)
Set environment variables that are referenced by the MET config file.
def process_fields (self, time_info, fcst_field, obs_field, ens_field=None)
Set and print environment variables, then build/run MET command Args:
def create_and_set_output_dir (self, time_info)
Builds the full output dir path with valid or init time Creates output directory if it doesn't already exist Args:
def get_verification_mask (self, time_info)
If verification mask template is set in the config file, use it to find the verification mask filename.
def get_command (self)
Builds the command to run the MET application string.
Public Member Functions inherited from command_builder.CommandBuilder
def __init__ (self, config, logger)
def create_c_dict (self)
def clear (self)
Unset class variables to prepare for next run time.
def log_error (self, error_string)
def set_user_environment (self, time_info=None)
Set environment variables defined in [user_env_vars] section of config.
def add_common_envs (self, time_info=None)
def print_all_envs (self)
def handle_window_once (self, c_dict, dtype, edge, app_name)
Check and set window dictionary variables like OBS_WINDOW_BEG or FCST_FILE_WINDW_END Args:
def handle_window_variables (self, c_dict, app_name, dtypes=['FCST', OBS)
Handle all window config variables like [FCST/OBS]_<app_name>_WINDOW_[BEGIN/END] and [FCST/OBS]_<app_name>_FILE_WINDOW_[BEGIN/END] Args:
def set_output_path (self, outpath)
Split path into directory and filename then save both.
def get_output_path (self)
Combine output directory and filename then return result.
def add_env_var (self, key, name)
Sets an environment variable so that the MET application can reference it in the parameter file or the application itself.
def print_env (self)
Print all environment variables set for this application.
def print_env_copy (self, var_list=None)
def get_env_copy (self, var_list=None)
Print list of environment variables that can be easily copied into terminal.
def print_env_item (self, item)
Print single environment variable in the log file.
def print_user_env_items (self)
Prints user environment variables in the log file.
def handle_fcst_and_obs_field (self, gen_name, fcst_name, obs_name, default=None, sec='config')
Handles config variables that have fcst/obs versions or a generic variable to handle both, i.e.
def find_model (self, time_info, var_info, mandatory=True, return_list=False)
Finds the model file to compare Args:
def find_obs (self, time_info, var_info, mandatory=True, return_list=False)
Finds the observation file to compare Args:
def find_data (self, time_info, var_info, data_type, mandatory=True, return_list=False)
Finds the data file to compare Args:
def find_exact_file (self, level, data_type, time_info, mandatory=True, return_list=False)
def find_file_in_window (self, level, data_type, time_info, mandatory=True, return_list=False)
def write_list_file (self, filename, file_list)
Writes a file containing a list of filenames to the staging dir.
def find_and_check_output_file (self, time_info)
Look for expected output file.
def format_list_string (self, list_string)
Add quotation marks around each comma separated item in the string.
def check_for_externals (self)
def check_for_gempak (self)
def check_gempaktocf (self, gempaktocf_jar)
def get_output_prefix (self, time_info)
def check_for_python_embedding (self, input_type, var_info)
Check if field name of given input type is a python script.
def get_command (self)
Builds the command to run the MET application string.
def build_and_run_command (self)
def build (self)
Build and run command.
def run_at_time (self, input_dict)
Used to output error and exit if wrapper is attemped to be run with LOOP_ORDER = times and the run_at_time method is not implemented.
def run_all_times (self)
Loop over time range specified in conf file and call METplus wrapper for each time.
Public Attributes
app_name
isOK
param
outdir
Public Attributes inherited from command_builder.CommandBuilder
isOK
errors
logger
config
env_list
debug
args
input_dir
infiles
outdir
outfile
param
env
c_dict
cmdrunner
Static Public Attributes
list climo_types = ['MEAN', 'STDEV']
Member Function Documentation
check_probabilistic_settings()
def compare_gridded_wrapper.CompareGriddedWrapper.check_probabilistic_settings (self)
If dataset is probabilistic, check if *_PROB_IN_GRIB_PDS or INPUT_DATATYPE are set.
If not enough information is set, report an error and set isOK to False
Definition at line 91 of file compare_gridded_wrapper.py.
create_and_set_output_dir()
def compare_gridded_wrapper.CompareGriddedWrapper.create_and_set_output_dir (self, time_info)
Builds the full output dir path with valid or init time Creates output directory if it doesn't already exist Args:
Parameters
time_info dictionary with time information
Definition at line 460 of file compare_gridded_wrapper.py.
Referenced by ensemble_stat_wrapper.EnsembleStatWrapper.process_fields(), compare_gridded_wrapper.CompareGriddedWrapper.process_fields(), mode_wrapper.MODEWrapper.process_fields_one_thresh(), and mtd_wrapper.MTDWrapper.process_fields_one_thresh().
get_command()
def compare_gridded_wrapper.CompareGriddedWrapper.get_command (self)
Builds the command to run the MET application string.
Returns
Returns a MET command with arguments that you can run
Definition at line 502 of file compare_gridded_wrapper.py.
get_field_info()
def compare_gridded_wrapper.CompareGriddedWrapper.get_field_info (self, v_name, v_level, v_thresh, v_extra, d_type)
Format field information into format expected by MET config file Args:
Parameters
v_level level of data to extract
v_thresh threshold value to use in comparison
v_name name of field to process
v_extra additional field information to add if available
d_type type of data to find (FCST or OBS) string
Returns
Returns formatted field information
Definition at line 303 of file compare_gridded_wrapper.py.
Referenced by ensemble_stat_wrapper.EnsembleStatWrapper.get_all_field_info(), mode_wrapper.MODEWrapper.process_fields_one_thresh(), mtd_wrapper.MTDWrapper.process_fields_one_thresh(), series_analysis_wrapper.SeriesAnalysisWrapper.run_at_time(), compare_gridded_wrapper.CompareGriddedWrapper.run_at_time_all_fields(), and compare_gridded_wrapper.CompareGriddedWrapper.run_at_time_one_field().
handle_climo_file_item()
def compare_gridded_wrapper.CompareGriddedWrapper.handle_climo_file_item (self, time_info, climo_item)
Handle a single climatology value by substituting time information, prepending input directory if provided, and preprocessing file if necessary.
All information is read from c_dict. CLIMO_<item>_FILE in c_dict is set.
Definition at line 137 of file compare_gridded_wrapper.py.
Referenced by compare_gridded_wrapper.CompareGriddedWrapper.handle_climo().
process_fields()
def compare_gridded_wrapper.CompareGriddedWrapper.process_fields (self, time_info, fcst_field, obs_field, ens_field = None)
Set and print environment variables, then build/run MET command Args:
Parameters
time_info dictionary with time information
fcst_field field information formatted for MET config file
obs_field field information formatted for MET config file
ens_field field information formatted for MET config file only used for ensemble_stat
Definition at line 431 of file compare_gridded_wrapper.py.
Referenced by ensemble_stat_wrapper.EnsembleStatWrapper.run_at_time_all_fields(), compare_gridded_wrapper.CompareGriddedWrapper.run_at_time_all_fields(), and compare_gridded_wrapper.CompareGriddedWrapper.run_at_time_one_field().
run_at_time()
def compare_gridded_wrapper.CompareGriddedWrapper.run_at_time (self, input_dict)
Runs the MET application for a given run time.
This function loops over the list of forecast leads and runs the application for each. Args:
Parameters
input_dict dictionary containing time information
Definition at line 155 of file compare_gridded_wrapper.py.
run_at_time_all_fields()
def compare_gridded_wrapper.CompareGriddedWrapper.run_at_time_all_fields (self, time_info)
Build MET command for all of the field/level combinations for a given init/valid time and forecast lead combination Args:
Parameters
time_info dictionary containing timing information
Definition at line 258 of file compare_gridded_wrapper.py.
Referenced by compare_gridded_wrapper.CompareGriddedWrapper.run_at_time_once().
run_at_time_once()
def compare_gridded_wrapper.CompareGriddedWrapper.run_at_time_once (self, time_info)
Build MET command for a given init/valid time and forecast lead combination Args:
Parameters
time_info dictionary containing timing information
Definition at line 185 of file compare_gridded_wrapper.py.
Referenced by reformat_gridded_wrapper.ReformatGriddedWrapper.run_at_time(), gempak_to_cf_wrapper.GempakToCFWrapper.run_at_time(), compare_gridded_wrapper.CompareGriddedWrapper.run_at_time(), and pb2nc_wrapper.PB2NCWrapper.run_at_time().
run_at_time_one_field()
def compare_gridded_wrapper.CompareGriddedWrapper.run_at_time_one_field (self, time_info, var_info)
Build MET command for a single field for a given init/valid time and forecast lead combination Args:
Parameters
time_info dictionary containing timing information
var_info object containing variable information
Definition at line 216 of file compare_gridded_wrapper.py.
Referenced by compare_gridded_wrapper.CompareGriddedWrapper.run_at_time_once().
set_environment_variables()
def compare_gridded_wrapper.CompareGriddedWrapper.set_environment_variables (self, fcst_field, obs_field, time_info)
Set environment variables that are referenced by the MET config file.
Implemented in child class
Definition at line 426 of file compare_gridded_wrapper.py.
Referenced by ensemble_stat_wrapper.EnsembleStatWrapper.process_fields(), compare_gridded_wrapper.CompareGriddedWrapper.process_fields(), mode_wrapper.MODEWrapper.process_fields_one_thresh(), mtd_wrapper.MTDWrapper.process_fields_one_thresh(), tc_pairs_wrapper.TCPairsWrapper.run_all_times(), series_analysis_wrapper.SeriesAnalysisWrapper.run_at_time(), tc_pairs_wrapper.TCPairsWrapper.run_at_time_loop_string(), and pb2nc_wrapper.PB2NCWrapper.run_at_time_once().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/compare_gridded_wrapper.py