METplus: series_by_init_wrapper.SeriesByInitWrapper Class Reference
series_by_init_wrapper.SeriesByInitWrapper Class Reference
Performs series analysis based on init time by first performing any additional filtering via the wrapper to the MET tool tc_stat, tc_stat_wrapper.
Detailed Description
Performs series analysis based on init time by first performing any additional filtering via the wrapper to the MET tool tc_stat, tc_stat_wrapper.
Next, the arguments to run the MET tool series_analysis is done
Definition at line 29 of file series_by_init_wrapper.py.
Public Member Functions
def __init__ (self, config, logger)
def create_c_dict (self)
def run_all_times (self)
Invoke the series analysis script based on the init time in the format YYYYMMDD_hh.
def apply_series_filters (self, tile_dir, init_times, series_output_dir, filter_opts, staging_dir)
Apply filter options, as specified in the param/config file.
def is_netcdf_created (self)
Check for the presence of NetCDF files in the series_analysis_init directory.
def get_fcst_file_info (self, dir_to_search, cur_init, cur_storm)
Get the number of all the gridded forecast n x m tile files for a given storm id and init time (that were created by extract_tiles).
def get_ascii_storm_files_list (self, tile_dir)
Creates the list of ASCII files that contain the storm id and init times.
def build_and_run_series_request (self, sorted_filter_init, tile_dir)
Build up the -obs, -fcst, -out necessary for running the series_analysis MET tool, then invoke series_analysis.
def create_obs_fcst_arg (self, param_arg, ascii_file_base, cur_storm, cur_init)
Create the argument to the -obs or -fcst flag to the MET tool, series_analysis.
def create_out_arg (self, cur_storm, cur_init, name, level)
Create/build the -out portion of the series_analysis command and creates the output directory.
def clear (self)
def add_input_file (self, filename, type_id)
def get_command (self)
def generate_plots (self, sorted_filter_init, tile_dir)
Generate the plots from the series_analysis output.
def get_storms_for_init (self, cur_init, out_dir_base)
Retrieve all the filter files which have the .tcst extension.
def create_fcst_anly_to_ascii_file (self, fcst_anly_grid_files, cur_init, cur_storm, fcst_anly_filename_base)
Create ASCII file for either the FCST or ANLY files that are aggregated based on init time and storm id.
Public Member Functions inherited from command_builder.CommandBuilder
def __init__ (self, config, logger)
def create_c_dict (self)
def clear (self)
Unset class variables to prepare for next run time.
def log_error (self, error_string)
def set_user_environment (self, time_info=None)
Set environment variables defined in [user_env_vars] section of config.
def add_common_envs (self, time_info=None)
def print_all_envs (self)
def handle_window_once (self, c_dict, dtype, edge, app_name)
Check and set window dictionary variables like OBS_WINDOW_BEG or FCST_FILE_WINDW_END Args:
def handle_window_variables (self, c_dict, app_name, dtypes=['FCST', OBS)
Handle all window config variables like [FCST/OBS]_<app_name>_WINDOW_[BEGIN/END] and [FCST/OBS]_<app_name>_FILE_WINDOW_[BEGIN/END] Args:
def set_output_path (self, outpath)
Split path into directory and filename then save both.
def get_output_path (self)
Combine output directory and filename then return result.
def add_env_var (self, key, name)
Sets an environment variable so that the MET application can reference it in the parameter file or the application itself.
def print_env (self)
Print all environment variables set for this application.
def print_env_copy (self, var_list=None)
def get_env_copy (self, var_list=None)
Print list of environment variables that can be easily copied into terminal.
def print_env_item (self, item)
Print single environment variable in the log file.
def print_user_env_items (self)
Prints user environment variables in the log file.
def handle_fcst_and_obs_field (self, gen_name, fcst_name, obs_name, default=None, sec='config')
Handles config variables that have fcst/obs versions or a generic variable to handle both, i.e.
def find_model (self, time_info, var_info, mandatory=True, return_list=False)
Finds the model file to compare Args:
def find_obs (self, time_info, var_info, mandatory=True, return_list=False)
Finds the observation file to compare Args:
def find_data (self, time_info, var_info, data_type, mandatory=True, return_list=False)
Finds the data file to compare Args:
def find_exact_file (self, level, data_type, time_info, mandatory=True, return_list=False)
def find_file_in_window (self, level, data_type, time_info, mandatory=True, return_list=False)
def write_list_file (self, filename, file_list)
Writes a file containing a list of filenames to the staging dir.
def find_and_check_output_file (self, time_info)
Look for expected output file.
def format_list_string (self, list_string)
Add quotation marks around each comma separated item in the string.
def check_for_externals (self)
def check_for_gempak (self)
def check_gempaktocf (self, gempaktocf_jar)
def get_output_prefix (self, time_info)
def check_for_python_embedding (self, input_type, var_info)
Check if field name of given input type is a python script.
def get_command (self)
Builds the command to run the MET application string.
def build_and_run_command (self)
def build (self)
Build and run command.
def run_at_time (self, input_dict)
Used to output error and exit if wrapper is attemped to be run with LOOP_ORDER = times and the run_at_time method is not implemented.
def run_all_times (self)
Loop over time range specified in conf file and call METplus wrapper for each time.
Public Attributes
app_path
app_name
stat_list
extract_tiles_dir
series_out_dir
series_filtered_out_dir
filter_opts
fcst_ascii_file_prefix
anly_ascii_file_prefix
convert_exe
isOK
sbi_plotting_out_dir
inaddons
infiles
outdir
outfile
args
param
Public Attributes inherited from command_builder.CommandBuilder
isOK
errors
logger
config
env_list
debug
args
input_dir
infiles
outdir
outfile
param
env
c_dict
cmdrunner
Member Function Documentation
apply_series_filters()
def series_by_init_wrapper.SeriesByInitWrapper.apply_series_filters (self, tile_dir, init_times, series_output_dir, filter_opts, staging_dir)
Apply filter options, as specified in the param/config file.
Args:
Parameters
tile_dir Directory where input data files reside. e.g. data which we will be applying our filter criteria.
init_times List of init times that define the input data.
series_output_dir The directory where the filter results will be stored.
filter_opts The filter options to apply
staging_dir The staging directory where intermediate files are saved. Returns: None
Definition at line 212 of file series_by_init_wrapper.py.
Referenced by series_by_lead_wrapper.SeriesByLeadWrapper.filter_with_tc_stat(), and series_by_init_wrapper.SeriesByInitWrapper.run_all_times().
build_and_run_series_request()
def series_by_init_wrapper.SeriesByInitWrapper.build_and_run_series_request (self, sorted_filter_init, tile_dir)
Build up the -obs, -fcst, -out necessary for running the series_analysis MET tool, then invoke series_analysis.
Args:
Parameters
sorted_filter_init A list of the sorted directories corresponding to the init times that are the result of filtering. If filtering produced no results, this is the list of files created from running extract_tiles.
tile_dir The directory where the input resides. Returns:
Definition at line 487 of file series_by_init_wrapper.py.
Referenced by series_by_init_wrapper.SeriesByInitWrapper.run_all_times().
create_fcst_anly_to_ascii_file()
def series_by_init_wrapper.SeriesByInitWrapper.create_fcst_anly_to_ascii_file (self, fcst_anly_grid_files, cur_init, cur_storm, fcst_anly_filename_base)
Create ASCII file for either the FCST or ANLY files that are aggregated based on init time and storm id.
Args: fcst_anly_grid_files: A list of the FCST or ANLY gridded files under consideration.
cur_init: The initialization time of interest
cur_storm: The storm id of interest
fcst_anly_filename_base: The base name of the ASCII file (either ANLY_ASCII_FILES_ or FCST_ASCII_FILES_ which will be appended with the storm id.
Returns: None: Creates an ASCII file containing a list of either FCST or ANLY files based on init time and storm id.
Definition at line 827 of file series_by_init_wrapper.py.
Referenced by series_by_init_wrapper.SeriesByInitWrapper.get_ascii_storm_files_list(), and series_by_init_wrapper.SeriesByInitWrapper.get_storms_for_init().
create_obs_fcst_arg()
def series_by_init_wrapper.SeriesByInitWrapper.create_obs_fcst_arg (self, param_arg, ascii_file_base, cur_storm, cur_init)
Create the argument to the -obs or -fcst flag to the MET tool, series_analysis.
Args:
Parameters
param_arg '-obs' for the -obs argument to series_analysis, or '-fcst' for the -fcst argument to series_analysis.
ascii_file_base The base name of the obs or fcst ASCII file that contains a list of the full filepath to the input files.
cur_storm The storm of interest.
cur_init The initialization time of interest.
Returns:
Definition at line 544 of file series_by_init_wrapper.py.
Referenced by series_by_init_wrapper.SeriesByInitWrapper.build_and_run_series_request().
create_out_arg()
def series_by_init_wrapper.SeriesByInitWrapper.create_out_arg (self, cur_storm, cur_init, name, level)
Create/build the -out portion of the series_analysis command and creates the output directory.
Args:
Parameters
cur_storm The storm of interest.
cur_init The initialization time of interest.
name The variable name of interest.
level The level of interest.
Returns:
Definition at line 578 of file series_by_init_wrapper.py.
Referenced by series_by_init_wrapper.SeriesByInitWrapper.build_and_run_series_request().
generate_plots()
def series_by_init_wrapper.SeriesByInitWrapper.generate_plots (self, sorted_filter_init, tile_dir)
Generate the plots from the series_analysis output.
Args:
Parameters
sorted_filter_init A list of the sorted directories corresponding to the init times (that are the result of filtering). If filtering produced no results, this is the list of files created from running extract_tiles.
tile_dir The directory where input data resides. Returns:
Definition at line 659 of file series_by_init_wrapper.py.
Referenced by series_by_init_wrapper.SeriesByInitWrapper.run_all_times(), and series_by_lead_wrapper.SeriesByLeadWrapper.run_all_times().
get_ascii_storm_files_list()
def series_by_init_wrapper.SeriesByInitWrapper.get_ascii_storm_files_list (self, tile_dir)
Creates the list of ASCII files that contain the storm id and init times.
The list is used to create an ASCII file which will be used as the option to the -obs or -fcst flag to the MET series_analysis tool. Args:
Parameters
tile_dir The directory where input files reside. Returns: sorted_filter_init: A list of the sorted directories corresponding to the init times after filtering has been applied. If filtering produced no results, this is the list of files created from running extract_tiles.
Definition at line 417 of file series_by_init_wrapper.py.
Referenced by series_by_init_wrapper.SeriesByInitWrapper.run_all_times().
get_fcst_file_info()
def series_by_init_wrapper.SeriesByInitWrapper.get_fcst_file_info (self, dir_to_search, cur_init, cur_storm)
Get the number of all the gridded forecast n x m tile files for a given storm id and init time (that were created by extract_tiles).
Determine the filename of the first and last files. This information is used to create the title value to the -title opt in plot_data_plane.
Args:
Parameters
dir_to_search The directory of the gridded files of interest.
cur_init The init time of interest.
cur_storm The storm id of interest.
Returns: num, beg, end: A tuple representing the number of forecast tile files, and the first and last file.
sys.exit(1) otherwise
Definition at line 345 of file series_by_init_wrapper.py.
Referenced by series_by_init_wrapper.SeriesByInitWrapper.generate_plots().
get_storms_for_init()
def series_by_init_wrapper.SeriesByInitWrapper.get_storms_for_init (self, cur_init, out_dir_base)
Retrieve all the filter files which have the .tcst extension.
Inside each file, extract the STORM_ID and append to the list, if the storm_list directory exists.
Args:
Parameters
cur_init the init time
out_dir_base The directory where one should start searching for the filter file(s)
those with a .tcst file extension.
Returns: storm_list: A list of all the storms ids that correspond to this init time and actually has a directory in the init dir (additional filtering in a previous step may result in missing storm ids even though they are in the filter.tcst file)
Definition at line 786 of file series_by_init_wrapper.py.
Referenced by series_by_init_wrapper.SeriesByInitWrapper.build_and_run_series_request(), series_by_init_wrapper.SeriesByInitWrapper.generate_plots(), and series_by_init_wrapper.SeriesByInitWrapper.get_ascii_storm_files_list().
is_netcdf_created()
def series_by_init_wrapper.SeriesByInitWrapper.is_netcdf_created (self)
Check for the presence of NetCDF files in the series_analysis_init directory.
Returns: is_created True if NetCDF files were found in the series_analysis_init/YYYYMMDD_hh/storm sub-directories, False otherwise.
Definition at line 312 of file series_by_init_wrapper.py.
Referenced by series_by_init_wrapper.SeriesByInitWrapper.run_all_times().
run_all_times()
def series_by_init_wrapper.SeriesByInitWrapper.run_all_times (self)
Invoke the series analysis script based on the init time in the format YYYYMMDD_hh.
Args:
Returns: None: Creates graphical plots of storm tracks
Definition at line 73 of file series_by_init_wrapper.py.
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/series_by_init_wrapper.py