METplus: config_launcher.METplusConfig Class Reference
config_launcher.METplusConfig Class Reference
A replacement for the produtil.config.ProdConfig used throughout the METplus system.
Detailed Description
A replacement for the produtil.config.ProdConfig used throughout the METplus system.
You should never need to instantiate one of these — the launch() and load() functions do that for you. This class is the underlying implementation of most of the functionality described in launch() and load()
Definition at line 405 of file config_launcher.py.
Public Member Functions
def __init__ (self, conf=None)
Creates a new METplusConfig.
def log (self, sublog=None)
returns a logging.Logger object
def sanity_check (self)
Runs nearly all sanity checks.
def getraw (self, sec, opt, default='', count=0)
def check_default (self, sec, name, default)
helper function for get methods, report error and exit if default is not set
def getexe (self, exe_name, default=None, morevars=None)
Wraps produtil exe with checks to see if option is set and if exe actually exists.
def getdir (self, dir_name, default=None, morevars=None, taskvars=None, must_exist=False)
Wraps produtil getdir and reports an error if it is set to /path/to.
def getdir_nocheck (self, dir_name, default=None)
def getstr_nocheck (self, sec, name, default=None)
def getstr (self, sec, name, default=None, badtypeok=False, morevars=None, taskvars=None)
Wraps produtil getstr to gracefully report if variable is not set and no default value is specified.
def getbool (self, sec, name, default=None, badtypeok=False, morevars=None, taskvars=None)
Wraps produtil getbool to gracefully report if variable is not set and no default value is specified.
def getint (self, sec, name, default=None, badtypeok=False, morevars=None, taskvars=None)
Wraps produtil getint to gracefully report if variable is not set and no default value is specified.
def getfloat (self, sec, name, default=None, badtypeok=False, morevars=None, taskvars=None)
Wraps produtil getfloat to gracefully report if variable is not set and no default value is specified.
def getseconds (self, sec, name, default=None, badtypeok=False, morevars=None, taskvars=None)
Converts time values ending in H, M, or S to seconds.
Public Member Functions inherited from produtil.config.ProdConfig
def __init__ (self, conf=None, quoted_literals=False, strict=False, inline_comment_prefixes=(';',))
ProdConfig constructor.
def quoted_literals (self)
def fallback (self, name, details)
Asks whether the specified fallback is allowed.
def add_fallback_callback (self, function)
Appends a function to the list of fallback callback functions called by fallback()
def readstr (self, source)
read config data and add it to this object
def from_args (self, args=None, allow_files=True, allow_options=True, rel_path=None, verbose=False)
Given a list of arguments, usually from sys.argv[1:], reads configuration files or sets option values.
def read (self, source)
reads and parses a config file
def readfp (self, source)
read config data from an open file
def readstr (self, string)
reads config data from an in-memory string
def set_options (self, section, kwargs)
set values of several options in a section
def realtime (self)
is this a real-time simulation?
def set (self, section, key, value)
set a config option
def __enter__ (self)
grab the thread lock
def __exit__ (self, a, b, c)
release the thread lock
def register_task (self, name)
add a ConfigurableTask to the database
def log (self, sublog=None)
returns a logging.Logger object
def getdatastore (self)
returns the Datastore
def getcycle (self)
get the analysis time
def setcycle (self, cycle)
set the analysis time
def set_time_vars (self)
internal function that sets time-related variables
def add_section (self, sec)
add a new config section
def has_section (self, sec)
does this section exist?
def has_option (self, sec, opt)
is this option set?
def getdir (self, name, default=None, morevars=None, taskvars=None)
query the "dir" section
def getloc (self, name, default=None, morevars=None, taskvars=None)
search the config, exe and dir sections in that order
def getexe (self, name, default=None, morevars=None, taskvars=None)
query the "exe" section
def __getitem__ (self, arg)
convenience function; replaces self.items and self.get
def makedirs (self, args)
calls produtil.fileop.makedirs() on directories in the [dir] section
def keys (self, sec)
get options in a section
def sections (self)
gets the list of all sections from a configuration object
def items (self, sec, morevars=None, taskvars=None)
get the list of (option,value) tuples for a section
def write (self, fileobject)
write the contents of this ProdConfig to a file
def getraw (self, sec, opt, default=None)
return the raw value of an option
def strinterp (self, sec, string, kwargs)
perform string expansion
def timestrinterp (self, sec, string, ftime=None, atime=None, kwargs)
performs string expansion, including time variables
def getint (self, sec, opt, default=None, badtypeok=False, morevars=None, taskvars=None)
get an integer value
def getfloat (self, sec, opt, default=None, badtypeok=False, morevars=None, taskvars=None)
get a float value
def getstr (self, sec, opt, default=None, badtypeok=False, morevars=None, taskvars=None)
get a string value
def get (self, sec, opt, default=None, badtypeok=False, morevars=None, taskvars=None)
get the value of an option from a section
def options (self, sec)
what options are in this section?
def getboolean (self, sec, opt, default=None, badtypeok=False, morevars=None, taskvars=None)
alias for getbool: get a bool value
def getbool (self, sec, opt, default=None, badtypeok=False, morevars=None, taskvars=None)
get a bool value
Public Attributes
logger
env
Additional Inherited Members
Properties inherited from produtil.config.ProdConfig
datastore
read-only property: the Datastore object for this simulation
cycle
the analysis cycle, a datetime.datetime object
Constructor & Destructor Documentation
__init__()
def config_launcher.METplusConfig.__init__ (self, conf = None)
Creates a new METplusConfig.
Parameters
conf The configuration file.
Definition at line 412 of file config_launcher.py.
Member Function Documentation
getexe()
def config_launcher.METplusConfig.getexe (self, exe_name, default = None, morevars = None)
Wraps produtil exe with checks to see if option is set and if exe actually exists.
Returns None if not found instead of exiting
Definition at line 529 of file config_launcher.py.
getraw()
def config_launcher.METplusConfig.getraw (self, sec, opt, default = '', count = 0)
parse parameter and replace any existing parameters
    referenced with the value (looking in same section, then
    config, dir, and os environment)
    returns raw string, preserving {valid?fmt=%Y} blocks
    Args:
@param sec: Section in the conf file to look for variable
@param opt: Variable to interpret
@param default: Default value to use if config is not set
@param count: Counter used to stop recursion to prevent infinite
    Returns:
Raw string
Definition at line 455 of file config_launcher.py.
Referenced by config_launcher.METplusConfig.getraw().
log()
def config_launcher.METplusConfig.log (self, sublog = None)
returns a logging.Logger object
Returns a logging.Logger object. If the sublog argument is provided, then the logger will be under that subdomain of the "metplus" logging domain. Otherwise, this METpluslauncher's logger (usually the "metplus" domain) is returned.
Parameters
sublog the logging subdomain, or None
Returns
a logging.Logger object
Definition at line 432 of file config_launcher.py.
Referenced by produtil.config.ProdConfig.from_args(), produtil.config.ProdConfig.getdatastore(), and config_launcher.METplusConfig.sanity_check().
sanity_check()
def config_launcher.METplusConfig.sanity_check (self)
Runs nearly all sanity checks.
Runs simple sanity checks on the METplus installation directory and configuration to make sure everything looks okay. May throw a wide variety of exceptions if sanity checks fail.
Definition at line 446 of file config_launcher.py.
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/config_launcher.py