METplus: produtil.mpiprog.MPIRank Class Reference
produtil.mpiprog.MPIRank Class Reference
Represents a single MPI rank.
Detailed Description
Represents a single MPI rank.
Definition at line 821 of file mpiprog.py.
Public Member Functions
def __init__ (self, arg, logger=None)
MPIRank constructor.
def env (self, kwargs)
def getthreads (self)
Returns the number of threads requested by this MPI rank, or by each MPI rank in this group of MPI ranks.
def setthreads (self, nthreads)
Sets the number of threads requested by each MPI rank within this group of MPI ranks.
def delthreads (self)
Removes the request for threads.
def to_shell (self)
Return a POSIX sh representation of this MPI rank, if possible.
def __getitem__ (self, args)
Adds arguments to this MPI rank's program.
def __repr__ (self)
Returns a Pythonic representation of this object for debugging.
def get_logger (self)
Returns a logging.Logger for this object, or None.
def validate (self, more=None)
Checks to see if this MPIRank is valid, or has errors.
def args (self)
Iterates over the executable arguments.
def copy (self)
Return a copy of self.
def nranks (self)
Returns 1: the number of MPI ranks.
def ngroups (self)
Returns 1: the number of groups of identical ranks.
def ranks (self)
Yields self once: all MPI ranks.
def groups (self, threads=False)
Yields (self,1): all groups of identical ranks and the number per group.
def __add__ (self, other)
Creates an MPIRanksSPMD or MPIRanksMPMD with this MPIRank and the other ranks.
def __mul__ (self, factor)
Creates an MPIRanksSPMD with this MPIRank duplicated factor times.
def __rmul__ (self, factor)
Creates an MPIRanksSPMD with this MPIRank duplicated factor times.
def __eq__ (self, other)
Returns True if this MPIRank is equal to the other object.
def check_serial (self)
Returns (False,True): this is a pure parallel program.
Public Member Functions inherited from produtil.mpiprog.MPIRanksBase
def to_arglist (self, to_shell=False, expand=False, shell_validate=None, pre=[], before=[], between=[], after=[], post=[], extra={}, include_localopts=False)
This is the underlying implementation of most of the mpi_impl modules, and hence make_runner as well.
def haslocalopts (self)
Returns True if setlocalopts(), addlocalopts() or addlocalopt() was called to add localopt values.
def setlocalopts (self, localopts)
Sets MPI options that are only meaningful to the currently used MPI configuration.
def addlocalopts (self, localopts)
Adds MPI options that are only meaningful to the currently used MPI configuration.
def addlocalopt (self, localopts)
Adds one MPI option to the local option list.
def localoptiter (self)
Iterates over local MPI configuration options for this rank or group of ranks.
def mixedlocalopts (self)
Do the MPI ranks within this group contain mixed values for local options?
def samelocalopts (self, other)
def getturbomode (self)
Do we want turbo mode to be enabled for this set of ranks?
def setturbomode (self, tm)
Sets the turbo mode setting: on (True) or off (False).
def delturbomode (self, tm)
Removes the request for turbo mode to be on or off.
def turbo (self, flag=True)
def rpn (self, count=0)
def env (self, kwargs)
Sets environment variables in the individual MPI ranks.
def make_runners_immutable (self)
Returns a copy of this object where all child produtil.prog.Runner objects have been replaced with produtil.prog.ImmutableRunner objects.
def get_logger (self)
Returns a logger.Logger object for this MPIRanksBase or one from its child MPIRanksBase objects (if it has any).
def check_serial (self)
Returns a tuple (s,p) where s=True if there are serial ranks in this part of the MPI program, and p=True if there are parallel ranks.
def getranks_per_node (self)
Returns the number of MPI ranks per node requsted by this MPI rank, or 0 if unspecified.
def setranks_per_node (self, rpn)
Sets the number of MPI ranks per node requsted by this MPI rank.
def delranks_per_node (self)
Unsets the requested number of ranks per node.
def nranks (self)
Returns the number of ranks in this part of the MPI program.
def ranks (self)
Iterates over all MPIRank objects in this part of the MPI program.
def ngroups (self)
Returns the number of groups of repeated MPI ranks in the MPI program.
def groups (self, threads=False)
Iterates over all groups of repeating MPI ranks in the MPI program returning tuples (r,c) containing a rank r and the count (number) of that rank c.
def getthreads (self)
Returns the number of threads requested by this MPI rank, or by each MPI rank in this group of MPI ranks.
def nonzero_threads (self)
The number of threads requested, or 1 if no threads are requested.
def setthreads (self, nthreads)
Sets the number of threads requested by each MPI rank within this group of MPI ranks.
def delthreads (self)
Removes the request for threads.
def __mul__ (self, factor)
Returns a new set of MPI ranks that consist of this group of ranks repeated "factor" times.
def __rmul__ (self, other)
Returns a new set of MPI ranks that consist of this group of ranks repeated "factor" times.
def __add__ (self, other)
Returns a new set of MPI ranks that consist of this set of ranks with the "other" set appended.
def __radd__ (self, other)
Returns a new set of MPI ranks that consist of the "other" set of ranks with this set appended.
def isplainexe (self)
Determines if this set of MPI ranks can be represented by a single serial executable with a single set of arguments run without MPI.
def to_shell (self)
Returns a POSIX sh command that will execute the serial program, if possible, or raise a subclass of NotValidPosixSh otherwise.
def expand_iter (self, expand, threads=False)
This is a wrapper around ranks() and groups() which will call self.groups() if expand=False.
def __repr__ (self)
Returns a string representation of this object intended for debugging.
def __eq__ (self, other)
Static Public Attributes
threads
Static Public Attributes inherited from produtil.mpiprog.MPIRanksBase
turbomode
ranks_per_node
The number of MPI ranks per node or 0 if no specific request is made.
threads
Constructor & Destructor Documentation
__init__()
def produtil.mpiprog.MPIRank.__init__ (self, arg, logger = None)
MPIRank constructor.
Parameters
arg What program to run. Can be a produtil.prog.Runner, or some way of creating one, such as a program name or list of program+arguments.
logger a logging.Logger for log messages or None to have no logger.
Definition at line 823 of file mpiprog.py.
Member Function Documentation
__add__()
def produtil.mpiprog.MPIRank.__add__ (self, other)
Creates an MPIRanksSPMD or MPIRanksMPMD with this MPIRank and the other ranks.
Parameters
other The other ranks.
Definition at line 956 of file mpiprog.py.
__eq__()
def produtil.mpiprog.MPIRank.__eq__ (self, other)
Returns True if this MPIRank is equal to the other object.
Definition at line 978 of file mpiprog.py.
__getitem__()
def produtil.mpiprog.MPIRank.__getitem__ (self, args)
Adds arguments to this MPI rank's program.
Definition at line 884 of file mpiprog.py.
__mul__()
def produtil.mpiprog.MPIRank.__mul__ (self, factor)
Creates an MPIRanksSPMD with this MPIRank duplicated factor times.
Parameters
factor the number of times to duplicate
Definition at line 966 of file mpiprog.py.
__repr__()
def produtil.mpiprog.MPIRank.__repr__ (self)
Returns a Pythonic representation of this object for debugging.
Definition at line 892 of file mpiprog.py.
Referenced by produtil.prog.Runner.__str__().
__rmul__()
def produtil.mpiprog.MPIRank.__rmul__ (self, factor)
Creates an MPIRanksSPMD with this MPIRank duplicated factor times.
Parameters
factor the number of times to duplicate
Definition at line 972 of file mpiprog.py.
args()
def produtil.mpiprog.MPIRank.args (self)
Iterates over the executable arguments.
Definition at line 925 of file mpiprog.py.
Referenced by produtil.mpiprog.MPIRank.validate().
check_serial()
def produtil.mpiprog.MPIRank.check_serial (self)
Returns (False,True): this is a pure parallel program.
Definition at line 985 of file mpiprog.py.
copy()
def produtil.mpiprog.MPIRank.copy (self)
Return a copy of self.
This is a deep copy except for the logger which whose reference is copied.
Definition at line 932 of file mpiprog.py.
Referenced by produtil.mpiprog.MPIRank.__add__(), produtil.mpiprog.MPISerial.__add__(), produtil.mpiprog.MPIRank.__getitem__(), produtil.prog.ImmutableRunner.runner(), and produtil.prog.Runner.to_shell().
delthreads()
def produtil.mpiprog.MPIRank.delthreads (self)
Removes the request for threads.
Definition at line 876 of file mpiprog.py.
get_logger()
def produtil.mpiprog.MPIRank.get_logger (self)
Returns a logging.Logger for this object, or None.
Definition at line 908 of file mpiprog.py.
getthreads()
def produtil.mpiprog.MPIRank.getthreads (self)
Returns the number of threads requested by this MPI rank, or by each MPI rank in this group of MPI ranks.
Definition at line 864 of file mpiprog.py.
groups()
def produtil.mpiprog.MPIRank.groups (self, threads = False)
Yields (self,1): all groups of identical ranks and the number per group.
Definition at line 949 of file mpiprog.py.
ngroups()
def produtil.mpiprog.MPIRank.ngroups (self)
Returns 1: the number of groups of identical ranks.
Definition at line 943 of file mpiprog.py.
nranks()
def produtil.mpiprog.MPIRank.nranks (self)
Returns 1: the number of MPI ranks.
Definition at line 940 of file mpiprog.py.
ranks()
def produtil.mpiprog.MPIRank.ranks (self)
Yields self once: all MPI ranks.
Definition at line 946 of file mpiprog.py.
setthreads()
def produtil.mpiprog.MPIRank.setthreads (self, nthreads)
Sets the number of threads requested by each MPI rank within this group of MPI ranks.
Definition at line 868 of file mpiprog.py.
to_shell()
def produtil.mpiprog.MPIRank.to_shell (self)
Return a POSIX sh representation of this MPI rank, if possible.
Definition at line 880 of file mpiprog.py.
validate()
def produtil.mpiprog.MPIRank.validate (self, more = None)
Checks to see if this MPIRank is valid, or has errors.
Parameters
more Arguments to the executable to validate.
Returns
None if there are no errors, or raises a descriptive exception.
Definition at line 911 of file mpiprog.py.
Referenced by produtil.mpiprog.MPIRank.__init__().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/produtil/mpiprog.py