METplus: tc_pairs_wrapper.TCPairsWrapper Class Reference
tc_pairs_wrapper.TCPairsWrapper Class Reference
Wraps the MET tool, tc_pairs to parse and match ATCF_by_pairs adeck and bdeck files.
Detailed Description
Wraps the MET tool, tc_pairs to parse and match ATCF_by_pairs adeck and bdeck files.
Pre-processes extra tropical cyclone data.
Definition at line 41 of file tc_pairs_wrapper.py.
Public Member Functions
def __init__ (self, config, logger)
def create_c_dict (self)
Create a dictionary containing all the values set in the config file.
def run_all_times (self)
Build up the command to invoke the MET tool tc_pairs.
def run_at_time (self, input_dict)
Create the arguments to run MET tc_pairs Args: input_dict dictionary containing init or valid time Returns:
def run_at_time_loop_string (self, input_dict)
Create the arguments to run MET tc_pairs Args: input_dict dictionary containing init or valid time Returns:
def set_environment_variables (self, time_info)
Set up all the environment variables that are assigned in the METplus config file which are to be used by the MET TC-pairs config file.
def process_data (self, basin, cyclone, model_list, time_info)
Find requested files and run tc_pairs Args:
def find_deck_files (self, deck, basin, cyclone, model_list, time_info)
Find ADECK or EDECK files that correspond to the BDECk file found Args:
def reformat_files (self, file_list, deck_type, time_info)
Reformat track data to match expected ATCF format Args:
def get_command (self)
Over-ride CommandBuilder's get_command because unlike other MET tools, tc_pairs handles input files differently- namely, through flags -adeck and -bdeck and doesn't require an output file, as there is a default.
def read_modify_write_file (self, in_csvfile, storm_month, missing_values, out_csvfile)
Reads, modifies and writes file Args:
Public Member Functions inherited from command_builder.CommandBuilder
def __init__ (self, config, logger)
def create_c_dict (self)
def clear (self)
Unset class variables to prepare for next run time.
def log_error (self, error_string)
def set_user_environment (self, time_info=None)
Set environment variables defined in [user_env_vars] section of config.
def add_common_envs (self, time_info=None)
def print_all_envs (self)
def handle_window_once (self, c_dict, dtype, edge, app_name)
Check and set window dictionary variables like OBS_WINDOW_BEG or FCST_FILE_WINDW_END Args:
def handle_window_variables (self, c_dict, app_name, dtypes=['FCST', OBS)
Handle all window config variables like [FCST/OBS]_<app_name>_WINDOW_[BEGIN/END] and [FCST/OBS]_<app_name>_FILE_WINDOW_[BEGIN/END] Args:
def set_output_path (self, outpath)
Split path into directory and filename then save both.
def get_output_path (self)
Combine output directory and filename then return result.
def add_env_var (self, key, name)
Sets an environment variable so that the MET application can reference it in the parameter file or the application itself.
def print_env (self)
Print all environment variables set for this application.
def print_env_copy (self, var_list=None)
def get_env_copy (self, var_list=None)
Print list of environment variables that can be easily copied into terminal.
def print_env_item (self, item)
Print single environment variable in the log file.
def print_user_env_items (self)
Prints user environment variables in the log file.
def handle_fcst_and_obs_field (self, gen_name, fcst_name, obs_name, default=None, sec='config')
Handles config variables that have fcst/obs versions or a generic variable to handle both, i.e.
def find_model (self, time_info, var_info, mandatory=True, return_list=False)
Finds the model file to compare Args:
def find_obs (self, time_info, var_info, mandatory=True, return_list=False)
Finds the observation file to compare Args:
def find_data (self, time_info, var_info, data_type, mandatory=True, return_list=False)
Finds the data file to compare Args:
def find_exact_file (self, level, data_type, time_info, mandatory=True, return_list=False)
def find_file_in_window (self, level, data_type, time_info, mandatory=True, return_list=False)
def write_list_file (self, filename, file_list)
Writes a file containing a list of filenames to the staging dir.
def find_and_check_output_file (self, time_info)
Look for expected output file.
def format_list_string (self, list_string)
Add quotation marks around each comma separated item in the string.
def check_for_externals (self)
def check_for_gempak (self)
def check_gempaktocf (self, gempaktocf_jar)
def get_output_prefix (self, time_info)
def check_for_python_embedding (self, input_type, var_info)
Check if field name of given input type is a python script.
def get_command (self)
Builds the command to run the MET application string.
def build_and_run_command (self)
def build (self)
Build and run command.
def run_at_time (self, input_dict)
Used to output error and exit if wrapper is attemped to be run with LOOP_ORDER = times and the run_at_time method is not implemented.
def run_all_times (self)
Loop over time range specified in conf file and call METplus wrapper for each time.
Public Attributes
app_name
app_path
adeck
bdeck
edeck
isOK
outdir
outfile
Public Attributes inherited from command_builder.CommandBuilder
isOK
errors
logger
config
env_list
debug
args
input_dir
infiles
outdir
outfile
param
env
c_dict
cmdrunner
Member Function Documentation
create_c_dict()
def tc_pairs_wrapper.TCPairsWrapper.create_c_dict (self)
Create a dictionary containing all the values set in the config file.
This will make it easier for unit testing.
Args:
Returns: c_dict - A dictionary of the values from the config file
Definition at line 55 of file tc_pairs_wrapper.py.
find_deck_files()
def tc_pairs_wrapper.TCPairsWrapper.find_deck_files (self, deck, basin, cyclone, model_list, time_info)
Find ADECK or EDECK files that correspond to the BDECk file found Args:
Parameters
deck type of deck (A or E)
basin region of storm from config
cyclone ID number of cyclone from config
model_list list of models that be available
time_info object containing timing information to process
Definition at line 604 of file tc_pairs_wrapper.py.
Referenced by tc_pairs_wrapper.TCPairsWrapper.process_data().
get_command()
def tc_pairs_wrapper.TCPairsWrapper.get_command (self)
Over-ride CommandBuilder's get_command because unlike other MET tools, tc_pairs handles input files differently- namely, through flags -adeck and -bdeck and doesn't require an output file, as there is a default.
Build command to run from arguments
Definition at line 676 of file tc_pairs_wrapper.py.
process_data()
def tc_pairs_wrapper.TCPairsWrapper.process_data (self, basin, cyclone, model_list, time_info)
Find requested files and run tc_pairs Args:
Parameters
basin region of storm from config
cyclone ID number of cyclone from config
model_list list of models that be available
time_info object containing timing information to process
Definition at line 457 of file tc_pairs_wrapper.py.
Referenced by tc_pairs_wrapper.TCPairsWrapper.run_at_time_loop_string().
read_modify_write_file()
def tc_pairs_wrapper.TCPairsWrapper.read_modify_write_file (self, in_csvfile, storm_month, missing_values, out_csvfile)
Reads, modifies and writes file Args:
Parameters
in_csvfile input csv file that is being parsed
storm_month The storm month
missing_values a tuple where (MISSING_VAL_TO_REPLACE, MISSING_VAL)
out_csvfile the output csv file
logger the log where logging is directed
Definition at line 723 of file tc_pairs_wrapper.py.
Referenced by tc_pairs_wrapper.TCPairsWrapper.get_command(), and tc_pairs_wrapper.TCPairsWrapper.reformat_files().
reformat_files()
def tc_pairs_wrapper.TCPairsWrapper.reformat_files (self, file_list, deck_type, time_info)
Reformat track data to match expected ATCF format Args:
Parameters
file_list list of files to reformat
deck_type type of deck (A or E)
time_info object with timing information to get storm month Returns: list of output files that are in ATCF format
Definition at line 643 of file tc_pairs_wrapper.py.
Referenced by tc_pairs_wrapper.TCPairsWrapper.process_data().
set_environment_variables()
def tc_pairs_wrapper.TCPairsWrapper.set_environment_variables (self, time_info)
Set up all the environment variables that are assigned in the METplus config file which are to be used by the MET TC-pairs config file.
Args: nothing - retrieves necessary MET+ config values via class attributes
Returns: nothing - sets the environment variables
Definition at line 295 of file tc_pairs_wrapper.py.
Referenced by tc_pairs_wrapper.TCPairsWrapper.run_all_times(), and tc_pairs_wrapper.TCPairsWrapper.run_at_time_loop_string().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/tc_pairs_wrapper.py