METplus: cyclone_plotter_wrapper.CyclonePlotterWrapper Class Reference
cyclone_plotter_wrapper.CyclonePlotterWrapper Class Reference
Generate plots of extra tropical storm forecast tracks.
Detailed Description
Generate plots of extra tropical storm forecast tracks.
Reads input from ATCF files generated from MET TC-Pairs
Definition at line 31 of file cyclone_plotter_wrapper.py.
Public Member Functions
def __init__ (self, config, logger)
def run_all_times (self)
Calls the defs needed to create the cyclone plots run_all_times() is required by CommandBuilder.
def retrieve_data (self)
Retrieve data from track files and return the min and max lon.
def get_columns_and_indices (self, header)
def create_plot (self)
Create the plot, using Cartopy.
Public Member Functions inherited from command_builder.CommandBuilder
def __init__ (self, config, logger)
def create_c_dict (self)
def clear (self)
Unset class variables to prepare for next run time.
def log_error (self, error_string)
def set_user_environment (self, time_info=None)
Set environment variables defined in [user_env_vars] section of config.
def add_common_envs (self, time_info=None)
def print_all_envs (self)
def handle_window_once (self, c_dict, dtype, edge, app_name)
Check and set window dictionary variables like OBS_WINDOW_BEG or FCST_FILE_WINDW_END Args:
def handle_window_variables (self, c_dict, app_name, dtypes=['FCST', OBS)
Handle all window config variables like [FCST/OBS]_<app_name>_WINDOW_[BEGIN/END] and [FCST/OBS]_<app_name>_FILE_WINDOW_[BEGIN/END] Args:
def set_output_path (self, outpath)
Split path into directory and filename then save both.
def get_output_path (self)
Combine output directory and filename then return result.
def add_env_var (self, key, name)
Sets an environment variable so that the MET application can reference it in the parameter file or the application itself.
def print_env (self)
Print all environment variables set for this application.
def print_env_copy (self, var_list=None)
def get_env_copy (self, var_list=None)
Print list of environment variables that can be easily copied into terminal.
def print_env_item (self, item)
Print single environment variable in the log file.
def print_user_env_items (self)
Prints user environment variables in the log file.
def handle_fcst_and_obs_field (self, gen_name, fcst_name, obs_name, default=None, sec='config')
Handles config variables that have fcst/obs versions or a generic variable to handle both, i.e.
def find_model (self, time_info, var_info, mandatory=True, return_list=False)
Finds the model file to compare Args:
def find_obs (self, time_info, var_info, mandatory=True, return_list=False)
Finds the observation file to compare Args:
def find_data (self, time_info, var_info, data_type, mandatory=True, return_list=False)
Finds the data file to compare Args:
def find_exact_file (self, level, data_type, time_info, mandatory=True, return_list=False)
def find_file_in_window (self, level, data_type, time_info, mandatory=True, return_list=False)
def write_list_file (self, filename, file_list)
Writes a file containing a list of filenames to the staging dir.
def find_and_check_output_file (self, time_info)
Look for expected output file.
def format_list_string (self, list_string)
Add quotation marks around each comma separated item in the string.
def check_for_externals (self)
def check_for_gempak (self)
def check_gempaktocf (self, gempaktocf_jar)
def get_output_prefix (self, time_info)
def check_for_python_embedding (self, input_type, var_info)
Check if field name of given input type is a python script.
def get_command (self)
Builds the command to run the MET application string.
def build_and_run_command (self)
def build (self)
Build and run command.
def run_at_time (self, input_dict)
Used to output error and exit if wrapper is attemped to be run with LOOP_ORDER = times and the run_at_time method is not implemented.
def run_all_times (self)
Loop over time range specified in conf file and call METplus wrapper for each time.
Static Public Member Functions
def extract_date_and_time_from_init (init_time_str)
def extract_lead_hr (lead_str)
def set_lead_group (track_dict, init_hh)
Sets the position indicator key to 0 if init hour is 0 or 12, and 6 if init hour is 6 or 18.
def rescale_lon (lon)
Rescales longitude, using the same logic employed by MET.
Public Attributes
app_name
input_data
output_dir
init_date
init_hr
model
title
gen_ascii
unique_storm_id
storm_id_dict
columns_of_interest
circle_marker
cross_marker
isOK
Public Attributes inherited from command_builder.CommandBuilder
isOK
errors
logger
config
env_list
debug
args
input_dir
infiles
outdir
outfile
param
env
c_dict
cmdrunner
Member Function Documentation
extract_date_and_time_from_init()
def cyclone_plotter_wrapper.CyclonePlotterWrapper.extract_date_and_time_from_init (init_time_str) static
Extract and return the YYYYMMDD portion and the
    hh portion from the init time taken from the .tcst file.
Definition at line 278 of file cyclone_plotter_wrapper.py.
Referenced by cyclone_plotter_wrapper.CyclonePlotterWrapper.retrieve_data().
extract_lead_hr()
def cyclone_plotter_wrapper.CyclonePlotterWrapper.extract_lead_hr (lead_str) static
Extract and return the lead hours from the hhmmss lead string.
Definition at line 292 of file cyclone_plotter_wrapper.py.
Referenced by cyclone_plotter_wrapper.CyclonePlotterWrapper.retrieve_data().
get_columns_and_indices()
def cyclone_plotter_wrapper.CyclonePlotterWrapper.get_columns_and_indices (self, header)
Parse the header for the columns of interest and store the
    information in a dictionary where the key is the column name
    and value is the index/column number.
    Returns:
column_dict:  A dictionary containing the column name
              and its index
Definition at line 259 of file cyclone_plotter_wrapper.py.
Referenced by cyclone_plotter_wrapper.CyclonePlotterWrapper.retrieve_data().
rescale_lon()
def cyclone_plotter_wrapper.CyclonePlotterWrapper.rescale_lon (lon) static
Rescales longitude, using the same logic employed by MET.
Definition at line 544 of file cyclone_plotter_wrapper.py.
retrieve_data()
def cyclone_plotter_wrapper.CyclonePlotterWrapper.retrieve_data (self)
Retrieve data from track files and return the min and max lon.
Returns: None
Definition at line 72 of file cyclone_plotter_wrapper.py.
Referenced by cyclone_plotter_wrapper.CyclonePlotterWrapper.run_all_times().
set_lead_group()
def cyclone_plotter_wrapper.CyclonePlotterWrapper.set_lead_group (track_dict, init_hh) static
Sets the position indicator key to 0 if init hour is 0 or 12, and 6 if init hour is 6 or 18.
This is used to determine which symbol to use, a '+' or 'o' when plotting track points.
Definition at line 534 of file cyclone_plotter_wrapper.py.
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/ush/cyclone_plotter_wrapper.py