METplus: string_template_substitution Namespace Reference
string_template_substitution Namespace Reference
Detailed Description
Program Name: string_template_substitution.py
Contact(s): Julie Prestopnik, NCAR RAL DTC, jpresto@ucar.edu, George McCabe
Abstract: Supporting functions for parsing and creating filename templates
History Log:  Initial version for METPlus
Usage: Usually imported in other Python code for individual function calls
Parameters: Varies
Input Files: None
Output Files: None
Condition codes: Varies
Classes
class StringExtract
Class to pull out timing and other information from a filename based on the filename template.
class StringSub
Functions
def multiple_replace (replace_dict, text)
def get_tags (template)
Parse template and pull out all wildcard characters (* or ?) and all tags, i.e.
def get_seconds_from_template (split_item)
Get seconds value from tag that contains a shift or truncate item.
def format_one_time_item (item, time_str, unit)
Determine precision of time offset value and format Args:
def format_hms (fmt, obj)
For time offset values, get hour, minute, and second values to format as necessary Args:
def set_output_dict_from_time_info (time_dict, output_dict, key)
Create datetime object from time data, get month and day from julian date if applicable.
def add_to_dict (match, match_dict, full_str, new_len)
Add extracted information to match dictionary Args:
Variables
string TEMPLATE_IDENTIFIER_BEGIN = "{"
string TEMPLATE_IDENTIFIER_END = "}"
string FORMATTING_DELIMITER = "?"
string FORMATTING_VALUE_DELIMITER = "="
string FORMAT_STRING = "fmt"
string SHIFT_STRING = "shift"
string TRUNCATE_STRING = "truncate"
string VALID_STRING = "valid"
string LEAD_STRING = "lead"
string INIT_STRING = "init"
string DA_INIT_STRING = "da_init"
string OFFSET_STRING = "offset"
string DATE_STRING = "date"
string REGION_STRING = "region"
string CYCLONE_STRING = "cyclone"
string MISC_STRING = "misc"
GLOBAL_LOGGER = None
dictionary LENGTH_DICT
Function Documentation
add_to_dict()
def string_template_substitution.add_to_dict (match, match_dict, full_str, new_len)
Add extracted information to match dictionary Args:
Parameters
match key for match dictionary containing tag name and units i.e. 'init_H' or 'lead_S'
match_dict dictionary of info extracted from filename
full_str rest of filename string to be parsed
new_len length of full_str to extract Returns: True if info was added to dictionary or it already exists and matched newly parsed info, False if info could not be extracted or if info differed from info already in match dictionary
Definition at line 200 of file string_template_substitution.py.
Referenced by string_template_substitution.StringExtract.get_fmt_info().
format_hms()
def string_template_substitution.format_hms (fmt, obj)
For time offset values, get hour, minute, and second values to format as necessary Args:
Parameters
fmt format to substitute, i.e. %3H or %2M or S
obj time value in seconds to format, i.e. 3600 Returns: Formatted time value
Definition at line 133 of file string_template_substitution.py.
Referenced by string_template_substitution.StringSub.handle_format_delimiter().
format_one_time_item()
def string_template_substitution.format_one_time_item (item, time_str, unit)
Determine precision of time offset value and format Args:
Parameters
item format to substitute, i.e. 3M or H
time_str time value that precision will be applied, i.e. 60
unit currently being processed, i.e. M or H or S Returns: Padded value or empty string if unit is not found in item
Definition at line 103 of file string_template_substitution.py.
Referenced by format_hms().
get_tags()
def string_template_substitution.get_tags (template)
Parse template and pull out all wildcard characters (* or ?) and all tags, i.e.
{init?fmt=H}. Used to pull out information from a template that contains wildcards and add that information when filled out another template Returns a list of wildcards and tag names found, i.e. [ '*', 'init', 'lead']
Definition at line 69 of file string_template_substitution.py.
multiple_replace()
def string_template_substitution.multiple_replace (replace_dict, text)
Replace in 'text' all occurrences of any key in the
given dictionary by its corresponding value.  Returns the new string.
Definition at line 59 of file string_template_substitution.py.
Referenced by string_template_substitution.StringSub.do_string_sub().
Variable Documentation
LENGTH_DICT
dictionary string_template_substitution.LENGTH_DICT
Initial value:
 =  {'%Y': 4,
                '%m': 2,
                '%d': 2,
                '%H': 2,
                '%M': 2,
                '%S': 2,
                '%j': 3,
                '%y': 2,
                '%b': 3,
                }
Definition at line 47 of file string_template_substitution.py.