METplus: produtil.batchsystem Namespace Reference
produtil.batchsystem Namespace Reference
Provides information about the batch system.
Detailed Description
Provides information about the batch system.
This module is intended to be used to communicate with the batch system. At present, it just knows how to guess the job name and id, as well as a "longname" that combines the two.
Classes
class FakeClass
A special class for constants.
Functions
def set_default_name (default_name)
Set default for all job names.
def set_jobname (jobname)
Sets the value that jobname() should return.
def set_jobid (jobid)
Sets the value that jobid() should return.
def set_joblongname (joblongname)
Sets the value that joblongname() should return.
def getenvs (names, fallback=None)
Get an environment variable, with various fallback options.
def jobname (fallback=UNSPECIFIED)
Get the batch job name.
def jobid (fallback=UNSPECIFIED)
Get the batch job ID.
def joblongname (jobid_fallback=UNSPECIFIED, jobname_fallback=UNSPECIFIED)
Get the job longname.
Variables
UNSPECIFIED = FakeClass()
Constant for unspecified arguments.
string NONAME = "NONAME"
Name for jobs that have no name.
Function Documentation
getenvs()
def produtil.batchsystem.getenvs (names, fallback = None)
Get an environment variable, with various fallback options.
Tries the list of environment variable names, returning the first one that exists and is non-blank. If none are found, returns the fallback.
Parameters
names the list of environment variables
fallback the fallback option if none are set
Definition at line 68 of file batchsystem.py.
Referenced by produtil.batchsystem.jobid(), produtil.batchsystem.joblongname(), and produtil.batchsystem.jobname().
jobid()
def produtil.batchsystem.jobid (fallback = UNSPECIFIED)
Get the batch job ID.
Returns the batch system job id for the batch job that is running this program, if known. If set_jobid was called, returns its value. Otherwise, tries the NCO $pid first, then the various batch system environment variables. If none are found, and the fallback is specified, returns the fallback. Otherwise, returns "o$PID" where $PID is the process ID.
Parameters
fallback the fallback if no id is known
Definition at line 103 of file batchsystem.py.
Referenced by produtil.batchsystem.joblongname().
joblongname()
def produtil.batchsystem.joblongname (jobid_fallback = UNSPECIFIED, jobname_fallback = UNSPECIFIED)
Get the job longname.
Returns a human-readable job name that includes both the batch system job name and id. If set_joblongname was called, returns its value. Next, returns the NCO $jobid variable if available, otherwise returns LL{jobid()}.o{jobname()} where jobid and jobname are the results of those two functions. The jobid_fallback and jobname_fallback are passed as the fallback parameters to the calls to jobid and jobname.
Parameters
jobid_fallback the fallback if no id is known
jobname_fallback the fallback if no name is known
Definition at line 120 of file batchsystem.py.
Referenced by produtil.batchsystem.jobid().
jobname()
def produtil.batchsystem.jobname (fallback = UNSPECIFIED)
Get the batch job name.
Returns the human-readable job name, if one exists. If set_jobname was called, returns its value. Otherwise, attempts to get it from the NCO $job environment variable first, then tries the batch system variables. If none are found, and fallback is specified, then the fallback is returned. Otherwise, the module-level NONAME variable is returned (which defaults to "NONAME").
Parameters
fallback return value if no job name is known
Definition at line 84 of file batchsystem.py.
Referenced by produtil.log.configureLogging(), and produtil.batchsystem.joblongname().
set_default_name()
def produtil.batchsystem.set_default_name (default_name)
Set default for all job names.
Sets a default value to use for the job name and long name if it cannot be guessed from the environment. This is used by produtil.setup.setup's jobname= argument. This will override the fallback= arguments of both jobname() and joblongname()
Parameters
default_name the name
Definition at line 39 of file batchsystem.py.
Referenced by produtil.setup.setup().
set_jobid()
def produtil.batchsystem.set_jobid (jobid)
Sets the value that jobid() should return.
Parameters
jobid the id
Definition at line 56 of file batchsystem.py.
set_joblongname()
def produtil.batchsystem.set_joblongname (joblongname)
Sets the value that joblongname() should return.
Parameters
joblongname the new long name
Definition at line 62 of file batchsystem.py.
set_jobname()
def produtil.batchsystem.set_jobname (jobname)
Sets the value that jobname() should return.
Parameters
jobname the name
Definition at line 50 of file batchsystem.py.
Variable Documentation
NONAME
produtil.batchsystem.NONAME = "NONAME"
Name for jobs that have no name.
Definition at line 21 of file batchsystem.py.
UNSPECIFIED
produtil.batchsystem.UNSPECIFIED = FakeClass()
Constant for unspecified arguments.
Definition at line 17 of file batchsystem.py.