METplus: produtil.prog Namespace Reference
produtil.prog Namespace Reference
Implements the produtil.run: provides the object tree for representing shell commands.
Detailed Description
Implements the produtil.run: provides the object tree for representing shell commands.
Do not load this module directly except for type checking (instanceof(o,produtil.prog.Runner)). It is meant to be used only by the produtil.run module. This module is part of the implementation of a shell-like syntax for running programs. The rest of the implementation is in the produtil.run and produtil.pipeline modules. MPI programs are implemented by the produtil.mpiprog and produtil.mpi_impl.
This module implements a shell-like syntax of running shell programs from Python. This module should not be used directly: the produtil.run implements critical parts of the functionality. Specifically, this module implements the Runner and ImmutableRunner classes. It also knows how to convert them to produtil.pipeline.Pipeline objects for actual execution.
Runner — This class represents a process that could be run. It keeps track of all possible aspects of running a process, including the command, arguments, environment variables, stdout stream, stderr stream, stdin stream, and a list of functions or callable objects to run before executing the problem. Provides public functions to modify the Runner.
ImmutableRunner — A Runner that cannot be changed: when modifying the Runner, it returns a new object. This is to implement shell aliases. For example, one could make an ImmutableRunner for program to index GRIB2 files. All the user would have to do is add the GRIB2 file as an argument, and capture the output.
Note that the actual work of creating the Runner or ImmutableRunner, or turning them into Pipeline objects done by the produtil.run module. Turning MPI programs into Runner objects is done by the produtil.mpiprog module and produtil.mpi_impl package, with the public interface in produtil.run. Hence, nobody would ever load this module directly, except for type checking (ie.: to see if your argument is a Runner before passing it to produtil.run.checkrun)..
Classes
class EqualInEnv
Raised when converting a Runner or pipeline of Runners to a POSIX sh string if there is an equal ("=") sign in an environment variable name.
class EqualInExecutable
Raised when converting a Runner or pipeline of Runners to a posix sh string if a Runner's executable contains an equal ("=") sign.
class ExitStatusException
Raised to indicate that a program generated an invalid return code.
class FileOpener
This is part of the internal implementation of Runner, used to convert it to a produtil.pipeline.Pipeline for execution.
class ImmutableRunner
An copy-on-write version of Runner.
class InvalidPipeline
Raised when the caller specifies an invalid input or output when piping a Runner into or out of another object.
class InvalidRunArgument
Raised to indicate that an invalid argument was sent into one of the run module functions.
class MultipleStderr
Raised when the caller specifies more than one destination for a Runner's stderr.
class MultipleStdin
Raised when the caller specifies more than one source for the stdin of a Runner.
class MultipleStdout
Raised when the caller specifies more than one destination for a Runner's stdout.
class NoSuchRedirection
Raised when trying to convert a pipeline of Runners to a POSIX sh string, if a redirection in the pipeline cannot be expressed in POSIX sh.
class NotValidPosixSh
Base class of exceptions that are raised when converting a Runner or pipeline of Runners to a POSIX sh command, if the Runner cannot be expressed as POSIX sh.
class NotValidPosixShString
Raised when converting a Runner or pipeline of Runners to a POSIX sh string.
class OutIsError
Instructs a Runner to send stderr to stdout.
class OverspecifiedStream
Raised when one tries to specify the stdout, stderr or stdin to go to, or come from, more than one location.
class PrerunNotValidPosixSh
Raised when trying to convert a pipeline of Runners to a POSIX sh string if the pipeline has a prerun object that lacks a to_shell function.
class ProgSyntaxError
Base class of exceptions raised when a Runner is given arguments that make no sense.
class Runner
Represents a single stage of a pipeline to execute.
class StreamGenerator
This is part of the internal implementation of Runner, and is used to convert it to a produtil.pipeline.Pipeline for execution.
class StreamReuser
Arranges for a stream-like object to be sent to the stdout, stderr or stdin of a Runner.
class StringInput
Represents sending a string to a process's stdin.
Functions
def shvarok (s)
Returns True if the specified environment variable name is a valid POSIX sh variable name, and False otherwise.
def shstrok (s)
Returns True if the specified string can be expressed as a POSIX sh string, and false otherwise.
def shbackslash (s)
Given a Python str, returns a backslashed POSIX sh string, or raises NotValidPosixShString if that cannot be done.
Function Documentation
shbackslash()
def produtil.prog.shbackslash (s)
Given a Python str, returns a backslashed POSIX sh string, or raises NotValidPosixShString if that cannot be done.
Parameters
s a string to backslash
Definition at line 158 of file prog.py.
Referenced by produtil.prog.FileOpener.to_shell(), produtil.prog.StringInput.to_shell(), produtil.prog.Runner.to_shell(), and produtil.mpiprog.MPIRank.to_shell().
shstrok()
def produtil.prog.shstrok (s)
Returns True if the specified string can be expressed as a POSIX sh string, and false otherwise.
Parameters
s a string
Definition at line 148 of file prog.py.
Referenced by produtil.prog.shbackslash().
shvarok()
def produtil.prog.shvarok (s)
Returns True if the specified environment variable name is a valid POSIX sh variable name, and False otherwise.
Parameters
s an environment variable name
Definition at line 139 of file prog.py.