METplus: produtil.run Namespace Reference
produtil.run Namespace Reference
A shell-like syntax for running serial, MPI and OpenMP programs.
Detailed Description
A shell-like syntax for running serial, MPI and OpenMP programs.
This module implements a shell-like syntax for launching MPI and non-MPI programs from Python. It recognizes three types of executables: mpi, "small serial" (safe for running on a batch node) and "big serial" (which should be run via aprun if applicable). There is no difference between "small serial" and "big serial" programs except on certain architectures (like Cray) where the job script runs on a heavily-loaded batch node and has compute nodes assigned for running other programs.
Program Types
There are three types of programs: mpi, serial and "big non-MPI." A "big" executable is one that is either OpenMP, or is a serial program that cannot safely be run on heavily loaded batch nodes. On Cray architecture machines, the job script runs on a heavily-populated "batch" node, with some compute nodes assigned for "large" programs. In such environments, the "big" executables are run on compute nodes and the small ones on the batch node.
mpi('exename') = an executable "exename" that calls MPI_Init and MPI_Finalize exactly once each, in that order.
exe('exename') = a small non-MPI program safe to run on a batch node
bigexe('exename') = a big non-MPI program that must be run on a compute node it may or may not use other forms of parallelism
You can also make reusable aliases to avoid having to call those functions over and over (more on that later). Examples:
Python: wrf=mpi('./wrf.exe')
Python: lsl=alias(exe('/bin/ls')['-l'].env(LANG='C',LS_COLORS='never'))
Those can then be reused later on as if the code is pasted in, similar to a shell alias.
Serial Execution Syntax
Select your serial programs by exe('name') for small serial programs and bigexe('name') for big serial programs. The return value of those functions can then be used with a shell-like syntax to specify redirection and piping. Example:
shell version: ls -l / | wc -l
Python version: run(exe('ls')['-l','/'] | exe('wc')['-l'])
Redirection syntax similar to the shell (< > and << operators):
run((exe('myprogram')['arg1','arg2','...'] < 'infile') > 'outfile')
Note the extra set of parentheses: you cannot do "exe('prog') < infile
outfile" because of the order of precedence of Python operators
Append also works:
run(exe('myprogram')['arg1','arg2','...'] >> 'appendfile')
You can also send strings as input with <<
run(exe('myprogram')['arg1','arg2','...'] << 'some input string')
One difference from shells is that < and << always modify the beginning of the pipeline:
shell: cat < infile | wc -l
Python #1: (exe('cat') < 'infile') | exe('wc')['-l']
Python #2: exe('cat') | (exe('wc')['-l'] < 'infile')
Note that the last second one, equivalent to cat|wc -l<infile, would NOT work in a shell since you would be giving wc -l two inputs.
Parallel Execution Syntax
Use mpi('exename') to select your executable, use [] to set arguments, use multiplication to set the number of ranks and use addition to combine different executables together into a multiple program multiple data (MPMD) MPI program.
Run ten copies of ls -l:
run(mpirun(mpiserial(('ls')['-l'])*10))
Run HyCOM coupled HWRF: one wm3c.exe, 30 hycom.exe and 204 wrf.exe:
run(mpirun(mpi('wm3c.exe') + mpi('hycom.exe')*30 + mpi('wrf.exe')*204))
You can set environment variables, pipe MPI output and handle redirection using the mpirun() function, which converts MPI programs into an bigexe()-style object (Runner):
Shell version:
result=$(mpirun -n 30 hostname | sort -u | wc -l)
Python version:
result=runstr(mpirun(mpi('hostname')*30) | exe['sort']['-u'] | exe['wc']['-l'])
Aliases
If you find yourself frequently needing the same command, or you need to store a command for multiple uses, then then you should define an alias. Let's say you want "long output" format Japanese language "ls" output:
exe('ls')['-l','/path/to/dir'].env(LANG='JP')
but you find yourself running that on many different directories. Then you may want to make an alias:
jplsl=alias(exe('ls')['-l'].env(LANG='JP'))
The return value jplsl can be treated as an exe()-like return value since it was from exe() originally, but any new arguments will be appended to the original set:
run(jplsl['/path/to/dir'])
Note that if we did this:
badlsl=exe('ls')['-l'].env(LANG='JP')  # Bad! No alias!
run(badlsl['/'])  # will list /
run(badlsl['/home'])  # will list / and /home
run(badlsl['/usr/bin']) # will list / /home and /usr/bin
goodlsl=alias(exe('ls')['-l'].env(LANG='JP')
run(goodlsl['/'])  # will list /
run(goodlsl['/home'])  # will list /home
run(goodlsl['/usr/bin']) # will list /usr/bin
Then the run(badlsl['/home']) would list /home AND / which is NOT what we want. Why does it do that? It is because badlsl is not an alias — it is a regular output from exe(), so every time we call its [] operator, we add an argument to the original command. When we call alias() it returns a copy-on-write version (goodlsl), where every call to [] creates a new object.
Note that alias() also works with pipelines, but most operations will only modify the last the command in the pipeline (or the first, for operations that change stdin).
Functions
def make_mpi (mpi_name=produtil.mpi_impl.NO_NAME, kwargs)
Creates an MPI implementation object for the specified MPI implementation.
def detect_mpi ()
Called by functions inside produtil.run to automatically detect the available MPI implementation.
def alias (arg)
Attempts to generate an unmodifiable "copy on write" version of the argument.
def batchexe (name, kwargs)
Returns a prog.ImmutableRunner object that represents a small serial program that can be safely run on a busy batch node.
def exe (name, mpiimpl=None, kwargs)
Returns a prog.ImmutableRunner object that represents a large serial program that must be run on a compute node.
def bigexe (name, kwargs)
Alias for exe() for backward compatibility.
def mpirun (arg, mpiimpl=None, kwargs)
Converts an MPI program specification into a runnable shell program suitable for run(), runstr() or checkrun().
def make_pipeline (arg, capture, mpiimpl=None, kwargs)
This internal implementation function generates a prog.PopenCommand object for the specified input, which may be a prog.Runner or mpiprog.MPIRanksBase.
def runbg (arg, capture=False, kwargs)
Not implemented: background execution.
def waitprocs (procs, logger=None, timeout=None, usleep=1000)
Not implemented: background process monitoring.
def runsync (logger=None, mpiimpl=None)
Runs the "sync" command as an exe().
def run (arg, logger=None, sleeptime=None, kwargs)
Executes the specified program and attempts to return its exit status.
def checkrun (arg, logger=None, kwargs)
This is a simple wrapper round run that raises ExitStatusException if the program exit status is non-zero.
def openmp (arg, threads=None, mpiimpl=None)
Sets the number of OpenMP threads for the specified program.
def runstr (arg, logger=None, kwargs)
Executes the specified program or pipeline, capturing its stdout and returning that as a string.
def mpi (arg, kwargs)
Returns an MPIRank object that represents the specified MPI executable.
def mpiserial (arg, kwargs)
Generates an mpiprog.MPISerial object that represents an MPI rank that executes a serial (non-MPI) program.
Variables
module_logger = logging.getLogger('produtil.run')
Default logger used by some functions if no logger is given.
Function Documentation
alias()
def produtil.run.alias (arg)
Attempts to generate an unmodifiable "copy on write" version of the argument.
The returned copy will generate a modifiable duplicate of itself if you attempt to change it.
Returns
a produtil.prog.ImmutableRunner
Parameters
arg a produtil.prog.Runner or produtil.prog.ImmutableRunner
Definition at line 267 of file run.py.
batchexe()
def produtil.run.batchexe (name, kwargs)
Returns a prog.ImmutableRunner object that represents a small serial program that can be safely run on a busy batch node.
Parameters
name the executable name or path
kwargs passed to produtil.prog.Runner.__init__
Returns
a new produtil.prog.ImmutableRunner
Definition at line 281 of file run.py.
Referenced by produtil.testing.parsetree.EmbedBash.run().
bigexe()
def produtil.run.bigexe (name, kwargs)
Alias for exe() for backward compatibility.
Use exe() instead.
Definition at line 303 of file run.py.
checkrun()
def produtil.run.checkrun (arg, logger = None, kwargs)
This is a simple wrapper round run that raises ExitStatusException if the program exit status is non-zero.
Parameters
arg the produtil.prog.Runner to execute (output of exe(), bigexe() or mpirun()
logger a logging.Logger to log messages
kwargs The optional run=[] argument can provide a different list of acceptable exit statuses.
Definition at line 456 of file run.py.
detect_mpi()
def produtil.run.detect_mpi ()
Called by functions inside produtil.run to automatically detect the available MPI implementation.
Detects the available MPI implementation - but that isn't as simple as it sounds. The detection logic requires calling produtil.run. Hence, produtil.run must be usable during the call to detect_mpi(). The way this is handled is in three steps:
Set the MPI implementation to "no MPI." This will allow all serial (non-OpenMP, non-MPI) calls to succeed.
Run the MPI implementation detection functions. These will be able to use produtil.run to execute serial programs to detect the MPI implementation.
If an MPI implementation is detected, set the MPI implementation to that one.
Note
MPI implementation detection only happens during the first call to detect_mpi(). Any later calls will return the cached result from _detected_mpi.
Returns
a subclass of produtil.mpi_impl.mpi_impl_base.ImplementationBase for generation of produtil.prog.Runner objects from openmp or mpi program specifications.
See also
_detected_mpi
Definition at line 221 of file run.py.
Referenced by produtil.run.exe(), produtil.run.make_mpi(), produtil.run.make_pipeline(), produtil.run.mpirun(), produtil.run.openmp(), and produtil.run.runsync().
exe()
def produtil.run.exe (name, mpiimpl = None, kwargs)
Returns a prog.ImmutableRunner object that represents a large serial program that must be run on a compute node.
Note
This function does NOT search $PATH on Cray. That ensures the $PATH will be expanded on the compute node instead. Use produtil.fileop.find_exe() if you want to explicitly search the PATH before execution.
Parameters
name the executable name or path
kwargs passed to produtil.prog.Runner.__init__
Returns
a new produtil.prog.ImmutableRunner
Definition at line 289 of file run.py.
Referenced by produtil.run.bigexe(), and produtil.testing.script.ProdutilRunner.mpirunner().
make_mpi()
def produtil.run.make_mpi (mpi_name = produtil.mpi_impl.NO_NAME, kwargs)
Creates an MPI implementation object for the specified MPI implementation.
Creates an object suitable for passing to the mpiimpl argument of various functions in produtil.run. The object will implement the requested MPI implementation. This object is NOT used to initialize the produtil.run; instead it is simply returned.
Returns
an MPI implementation object for the specified arguments
Parameters
mpi_name the name of the MPI implementation. If mpi_name=None, an mpiimpl for pure serial programs is returned. If no mpi_name is given, the local machine's available MPI implementation is detected and returned.
Note
When mpi_name is unset, the detection of the MPI implementation is redone, even if it had been done before by another call to get_mpi() or detect_mpi()
Parameters
kwargs additional arguments passed to produtil.mpi_impl.get_mpi()
See also
produtil.mpi_impl.impi.Implementation.detect()
Definition at line 183 of file run.py.
Referenced by produtil.testing.script.ProdutilRunner.__init__().
make_pipeline()
def produtil.run.make_pipeline (arg, capture, mpiimpl = None, kwargs)
This internal implementation function generates a prog.PopenCommand object for the specified input, which may be a prog.Runner or mpiprog.MPIRanksBase.
Parameters
arg the produtil.prog.Runner to convert. This is the output of exe(), bigexe() or mpirun()
capture if True, capture the stdout into a string
kwargs additional keyword arguments, same as for mpirun()
Definition at line 327 of file run.py.
Referenced by produtil.run.run(), produtil.run.runbg(), and produtil.run.runstr().
mpi()
def produtil.run.mpi (arg, kwargs)
Returns an MPIRank object that represents the specified MPI executable.
Parameters
arg the MPI program to run
kwargs logger=L for a logging.Logger to log messages
Definition at line 525 of file run.py.
Referenced by produtil.testing.script.ProdutilRunner.mpirunner().
mpirun()
def produtil.run.mpirun (arg, mpiimpl = None, kwargs)
Converts an MPI program specification into a runnable shell program suitable for run(), runstr() or checkrun().
Options for kwargs:
allranks=True — to run on all available MPI ranks. This cannot be used if a specific number of ranks (other than 1) was requested in the arg.
logger=L — a logging.Logger for log messages
Other platform-specific arguments. See produtil.mpi_impl for details.
Parameters
arg the mpiprog.MPIRanksBase describing the MPI program to run. This is the output of the mpi() or mpiserial() function.
kwargs additional arguments to control output.
Returns
a prog.Runner object for the specified mpiprog.MPIRanksBase object.
Definition at line 307 of file run.py.
Referenced by produtil.testing.script.ProdutilRunner.mpirunner().
mpiserial()
def produtil.run.mpiserial (arg, kwargs)
Generates an mpiprog.MPISerial object that represents an MPI rank that executes a serial (non-MPI) program.
The given value MUST be from bigexe() or exe(), NOT from mpi().
Parameters
arg the MPI program to run
kwargs logger=L for a logging.Logger to log messages
Definition at line 532 of file run.py.
openmp()
def produtil.run.openmp (arg, threads = None, mpiimpl = None)
Sets the number of OpenMP threads for the specified program.
Warning
Generally, when using MPI with OpenMP, the batch system must be configured correctly to handle this or unexpected errors will result.
Parameters
arg The "arg" argument must be from mpiserial, mpi, exe or bigexe.
threads The optional "threads" argument is an integer number of threads. If it is not specified, the maximum possible number of threads will be used. Note that using threads=None with mpirun(...,allranks=True) will generally not work unless the batch system has already configured the environment correctly for an MPI+OpenMP task with default maximum threads and ranks.
Returns
see run()
Definition at line 473 of file run.py.
Referenced by produtil.testing.script.ProdutilRunner.mpirunner().
run()
def produtil.run.run (arg, logger = None, sleeptime = None, kwargs)
Executes the specified program and attempts to return its exit status.
In the case of a pipeline, the highest exit status seen is returned. For MPI programs, exit statuses are unreliable and generally implementation-dependent, but it is usually safe to assume that a program that runs MPI_Finalize() and exits normally will return 0, and anything that runs MPI_Abort(MPI_COMM_WORLD) will return non-zero. Programs that exit due to a signal will return statuses >255 and can be interpreted with WTERMSIG, WIFSIGNALLED, etc.
Parameters
arg the produtil.prog.Runner to execute (output of exe(), bigexe() or mpirun()
logger a logging.Logger to log messages
sleeptime time to sleep between checks of child process
kwargs ignored
Definition at line 434 of file run.py.
Referenced by produtil.run.checkrun(), and produtil.testing.parsetree.EmbedBash.run().
runbg()
def produtil.run.runbg (arg, capture = False, kwargs)
Not implemented: background execution.
Runs the specified process in the background. Specify capture=True to capture the command's output. Returns a produtil.prog.PopenCommand. Call poll() to determine process completion, and use the stdout_data property to get the output after completion, if capture=True was specified.
Bug:
produtil.run.runbg() is not implemented
Warning
this is not implemented
Parameters
arg the produtil.prog.Runner to execute (output of exe(), bigexe() or mpirun()
capture if True, capture output
kwargs same as for mpirun()
Definition at line 359 of file run.py.
runstr()
def produtil.run.runstr (arg, logger = None, kwargs)
Executes the specified program or pipeline, capturing its stdout and returning that as a string.
If the exit status is non-zero, then NonZeroExit is thrown.
Example:
runstr(exe('false'),ret=(1))
succeeds if "false" returns 1, and raises ExitStatusError otherwise.
Parameters
arg The "arg" argument must be from mpiserial, mpi, exe or bigexe.
logger a logging.Logger for logging messages
kwargs You can specify an optional list or tuple "ret" that contains an alternative list of valid return codes. All return codes are zero or positive: negative values represent signal-terminated programs (ie.: SIGTERM produces -15, SIGKILL produces -9, etc.)
Definition at line 494 of file run.py.
runsync()
def produtil.run.runsync (logger = None, mpiimpl = None)
Runs the "sync" command as an exe().
Definition at line 428 of file run.py.
waitprocs()
def produtil.run.waitprocs (procs, logger = None, timeout = None, usleep = 1000)
Not implemented: background process monitoring.
Waits for one or more backgrounded processes to complete. Logs to the specified logger while doing so. If a timeout is specified, returns False after the given time if some processes have not returned. The usleep argument is the number of microseconds to sleep between checks (can be a fraction). The first argument, procs specifies the processes to check. It must be a produtil.prog.Pipeline (return value from runbg) or an iterable (list or tuple) of such.
Bug:
produtil.run.waitprocs() is untested
Warning
This is not tested and probably does not work.
Parameters
procs the processes to watch
logger the logging.Logger for log messages
timeout how long to wait before giving up
usleep sleep time between checks
Definition at line 380 of file run.py.