METplus: produtil.testing.setarith Namespace Reference
produtil.testing.setarith Namespace Reference
Set arithmetic logic utilities.
Detailed Description
Set arithmetic logic utilities.
This implements a simple set logic language, and uses it to combine Python sets. It operates on produtil.testing.utilities.ListableSet objects. The main entry point, arithparse(), returns a result of the same type.
Examples:
elements=ListableSet(["cat","dog","orange","salmon","bin"])
sets={ "alive":    ListableSet(["cat","dog","orange","salmon"]),
       "colors":   ListableSet(["orange","salmon"]),
       "commands": ListableSet(["cat","bin"]),
       "verbs":    ListableSet(["cat","dog","bin"])
       }
# Request a single set:
arithparse("alive",sets,elements)
#  --> ListableSet(["cat","dog","orange","salmon"])
# Subtraction of two sets:
arithparse("minus(alive,colors)",sets,elements)
#  --> ListableSet(["cat","dog"])
# Union of two sets:
arithparse("union(colors,commands)",sets,elements)
#  --> ListableSet(["orange","salmon","cat","bin"])
# Intersection of two sets:
arithparse("inter(alive,verbs)",sets,elements)
#  --> ListableSet(["cat","dog"])
# Individual elements:
arithparse("{cat,orange}")
#  --> ListableSet(["cat","orange"])
# Combination of the above:
arithparse("minus(inter(union({dog,orange},commands),alive),verbs)")
#  --> ListableSet(["dog"])
Classes
class ArithException
Raised for parser errors in the inputs to the set arithmetic parser (arithparse).
class ArithKeyError
Raised when an element or set is requested that does not exist.
Functions
def arithparse (spec, sets, elements)
Main entry point to the setarith module.
def _arithtoken (spec)
Tokenizes a set arithmetic expression.
def each_not_all (sets)
Iterates over the given ListableSet, yielding everything except the special set "*".
def _arithparse_set (tokiter, elements)
Parses an explicit set definition.
def _arithparse_list (tokiter, sets, elements)
Iterates over the arguments to a set arithmetic function, yielding sets.
def _arithparse_expr (tokiter, sets, elements)
Evaluates one set arithmetic expression.
def _arithparse_top (tokiter, sets, elements)
Evaluates the null string, or one set arithmetic expression.
Function Documentation
_arithparse_expr()
def produtil.testing.setarith._arithparse_expr (tokiter, sets, elements) protected
Evaluates one set arithmetic expression.
Parses any expression with balanced parentheses. That can be anything from the entire string to a single set name.
Parameters
tokiter a produtil.testing.utilities.peekable object that iterates over the expression.
sets A mapping from set name to produtil.testing.utilities.ListableSet objects that represent each set.
elements All known elements. This is a superset of all other sets, and may contain additional elements.
Returns
the resulting ListableSet
Definition at line 205 of file setarith.py.
Referenced by produtil.testing.setarith._arithparse_list(), and produtil.testing.setarith._arithparse_top().
_arithparse_list()
def produtil.testing.setarith._arithparse_list (tokiter, sets, elements) protected
Iterates over the arguments to a set arithmetic function, yielding sets.
Calls _arithparse_expr() on each argument.
Parameters
elements All known elements. This is a superset of all other sets, and may contain additional elements.
sets A mapping from set name to produtil.testing.utilities.ListableSet objects that represent each set.
See also
arithparse()
Returns
Nothing; this is an iterator.
Definition at line 169 of file setarith.py.
Referenced by produtil.testing.setarith._arithparse_expr().
_arithparse_set()
def produtil.testing.setarith._arithparse_set (tokiter, elements) protected
Parses an explicit set definition.
Parses a list of elements:
{element1,element2,element3}
Parameters
tokiter a peekable iterator that yields tokens
elements All known elements. This is a superset of all other sets, and may contain additional elements.
Returns
a new ListableSet
Definition at line 127 of file setarith.py.
Referenced by produtil.testing.setarith._arithparse_expr().
_arithparse_top()
def produtil.testing.setarith._arithparse_top (tokiter, sets, elements) protected
Evaluates the null string, or one set arithmetic expression.
When given the null string, this immediately returns an empty ListableSet. Otherwise, it passes control to _arithparse_expr() to parse the resulting expression.
Parameters
tokiter a produtil.testing.utilities.peekable object that iterates over the expression.
sets A mapping from set name to produtil.testing.utilities.ListableSet objects that represent each set.
elements All known elements. This is a superset of all other sets, and may contain additional elements.
Returns
the resulting ListableSet
Definition at line 270 of file setarith.py.
Referenced by produtil.testing.setarith.arithparse().
_arithtoken()
def produtil.testing.setarith._arithtoken (spec) protected
Tokenizes a set arithmetic expression.
See also
arithparse()
Definition at line 78 of file setarith.py.
Referenced by produtil.testing.setarith.arithparse().
arithparse()
def produtil.testing.setarith.arithparse (spec, sets, elements)
Main entry point to the setarith module.
Performs the specified set arithmetic on the given elements and sets, returning the resulting set.
Parameters
spec A setarith language expression describing the operation.
sets A mapping from set name to produtil.testing.utilities.ListableSet objects that represent each set.
elements All known elements. This is a superset of all other sets, and may contain additional elements.
Definition at line 49 of file setarith.py.