METplus: produtil.cluster Namespace Reference
produtil.cluster Namespace Reference
Provides information about the cluster on which this job is running.
Detailed Description
Provides information about the cluster on which this job is running.
Classes
class Cluster
Stores information about a computer cluster.
class NOAAGAEA
Represents the NOAA GAEA cluster.
class NOAAJet
The NOAA Jet Cluster.
class NOAATheia
class NOAAWCOSS
Represents the NOAA WCOSS clusters, Tide, Gyre and the test system Eddy.
class NOAAZeus
Represents the NOAA Zeus cluster.
class UCARYellowstone
Represents the Yellowstone cluster.
class WCOSSCray
This subclass of NOAAWCOSS handles the new Cray portions of WCOSS: Luna and Surge.
class WisconsinS4
Represents the S4 cluster.
Functions
def set_cluster (there)
Sets the current cluster (module-level "here" variable) to the given value.
def where ()
Guesses what cluster the program is running on, and if it cannot, returns a cluster named "noname" with reasonable defaults.
def longname ()
Synonym for here.longname.
def name ()
Synonym for here.name.
def group_quotas ()
Synonym for here.group_quotas.
def acl_support ()
Synonym for here.acl_support.
def no_access_control ()
True if the cluster provides no means to control access to files.
def use_acl_for_rstdata ()
Synonym for here.use_acl_for_rstdata.
def ncepprod ()
Are we on NCEP production?
def partition ()
Returns system-specific information about what part of the system you are on.
Variables
DO_NOT_SET = object()
Special values for parameters that should not be set.
here = None
The Cluster object for the local cluster.
Function Documentation
acl_support()
def produtil.cluster.acl_support ()
Synonym for here.acl_support.
Will call the "where()" function if "here" is uninitialized.
Definition at line 134 of file cluster.py.
group_quotas()
def produtil.cluster.group_quotas ()
Synonym for here.group_quotas.
Will call the "where()" function if "here" is uninitialized.
Definition at line 128 of file cluster.py.
Referenced by produtil.fileop.deliver_file().
longname()
def produtil.cluster.longname ()
Synonym for here.longname.
Will call the "where()" function if "here" is uninitialized.
Definition at line 116 of file cluster.py.
name()
def produtil.cluster.name ()
Synonym for here.name.
Will call the "where()" function if "here" is uninitialized.
Definition at line 122 of file cluster.py.
ncepprod()
def produtil.cluster.ncepprod ()
Are we on NCEP production?
Returns
True if the present machine is the NCEP production machine. Note that this function may read a text file when it is called, and the return value may change during the execution of the program if the program is running during a production switch.
Definition at line 153 of file cluster.py.
no_access_control()
def produtil.cluster.no_access_control ()
True if the cluster provides no means to control access to files.
This is true if the cluster uses group ids for quotas, and provides no access control list support.
Definition at line 140 of file cluster.py.
partition()
def produtil.cluster.partition ()
Returns system-specific information about what part of the system you are on.
Definition at line 163 of file cluster.py.
set_cluster()
def produtil.cluster.set_cluster (there)
Sets the current cluster (module-level "here" variable) to the given value.
Bad things may happen if this is not a subclass of Cluster. #
Parameters
there A Cluster object for this local cluster.
Definition at line 72 of file cluster.py.
Referenced by produtil.setup.setup().
use_acl_for_rstdata()
def produtil.cluster.use_acl_for_rstdata ()
Synonym for here.use_acl_for_rstdata.
Will call the "where()" function if "here" is uninitialized.
Definition at line 147 of file cluster.py.
Referenced by produtil.fileop.deliver_file().
where()
def produtil.cluster.where ()
Guesses what cluster the program is running on, and if it cannot, returns a cluster named "noname" with reasonable defaults.
The result is stored in the module scope "here" variable.
Definition at line 80 of file cluster.py.
Referenced by produtil.cluster.acl_support(), produtil.cluster.group_quotas(), produtil.cluster.longname(), produtil.cluster.name(), produtil.cluster.ncepprod(), produtil.cluster.no_access_control(), produtil.cluster.partition(), produtil.setup.setup(), and produtil.cluster.use_acl_for_rstdata().
Variable Documentation
DO_NOT_SET
produtil.cluster.DO_NOT_SET = object()
Special values for parameters that should not be set.
Definition at line 13 of file cluster.py.
here
produtil.cluster.here = None
The Cluster object for the local cluster.
Do not modify.
Definition at line 70 of file cluster.py.