METplus: produtil.log Namespace Reference
produtil.log Namespace Reference
Configures logging.
Detailed Description
Configures logging.
This module configures logging for stdout, stderr and the jlogfile. It also contains the jlogger, a logger.Logger object that is used to log directly to the jlogfile, and jlogdomain: a string name of the logger domain for the jlogfile.
Classes
class JLogFormatter
This subclass of MasterLogFormatter does not include exception information in the log file.
class JLogHandler
Custom LogHandler for the jlogfile.
class MasterLogFormatter
This is a custom log formatter that inserts the thread or process (logthread) that generated the log message.
class MasterLogHandler
Custom LogHandler for the master process of a multi-process job.
class ThreadLogger
Custom logging.Logger that inserts thread information.
Functions
def postmsg (message)
Sends the message to the jlogfile logging stream at level INFO.
def set_jlogfile (filename)
Tells the jlogger to log to the specified file instead of the current jlogfile.
def stdout_is_stderr ()
Returns True if it can determine that stdout and stderr are the same file or terminal.
def mpi_redirect (threadname, stderrfile, stdoutfile, threadlevel=logging.WARNING, masterlevel=logging.INFO, openmode=None, logger=None)
Used to split to multiple logging streams.
def configureLogging (jlogfile=None, level=logging.INFO, jloglevel=logging.INFO, japplevel=logging.ERROR, eloglevel=logging.WARNING, ologlevel=logging.NOTSET, thread_logger=False, masterdomain='master')
Configures log output to stderr, stdout and the jlogfile.
Variables
string logthread = ''
string for log messages to indicate thread number/name
string jlogdomain = 'jlog'
Logging domain for the jlogfile.
jlogger = logging.getLogger(jlogdomain)
A logging.Logger for the jlogdomain.
jloghandler = None
A logging.LogHandler for the jlogger.
masterlogger = None
Master log stream for MPI-split jobs.
masterdomain = None
Logging domain for the masterlogger.
Function Documentation
configureLogging()
def produtil.log.configureLogging (jlogfile = None, level = logging.INFO, jloglevel = logging.INFO, japplevel = logging.ERROR, eloglevel = logging.WARNING, ologlevel = logging.NOTSET, thread_logger = False, masterdomain = 'master')
Configures log output to stderr, stdout and the jlogfile.
Configures log file locations and logging levels for all streams.
Note
Important notes when choosing levels:
level - sets the global minimum log level. Anything below this level will be discarded regardless of other settings.
jloglevel - this limit is applied before japplevel
Parameters
jlogfile path to the jlogfile. Default: use os.environ('jlogfile') if set. Otherwise, stderr.
level minimum logging level globally. Set to INFO by default. Change this to logging.DEBUG if you're debugging the program.
jloglevel minimum logging level to send to jlogfile
japplevel minimum logging level to send to jlogfile from all domains except that specified in jlogdomain. Be careful when changing this as it logs directly to the WCOSS-wide jlogfile in operations.
eloglevel minimum logging level to send to stderr from ALL logs Set to None to disable stderr logging
ologlevel minimum logging level to send to stdout from ALL logs Default: logging.NOTSET (no filtering) Set to None to disable stdout logging.
thread_logger True to include the thread name in log messages.
masterdomain The logging domain that will send messages to the main log stream for the job, even within individual ranks of mpi-split jobs
Definition at line 339 of file log.py.
Referenced by produtil.log.mpi_redirect(), and produtil.setup.setup().
mpi_redirect()
def produtil.log.mpi_redirect (threadname, stderrfile, stdoutfile, threadlevel = logging.WARNING, masterlevel = logging.INFO, openmode = None, logger = None)
Used to split to multiple logging streams.
When the Python script splits itself into multiple processes via MPI, this function is called to redirect stdout to stdoutfile, stderr to stderrfile, and produce a new logging stream to the original stderr, with a logging level set to masterlevel. That new logging stream is called the "master log" and will receive any messages at level masterlevel or higher, and any messages sent to the jlogdomain.
This can also be used to redirect ONLY stdout, in which case no master logging stream is set up. That is requested by stderrfile=None.
Parameters
threadname the name of this process for logging purposes
stderrfile file to receive stderr
stdoutfile file to receive stdout
masterlevel log level to send to master log stream
openmode integer mode to use when opening files
logger a logging.Logger for logging errors while splitting the log stream.
Definition at line 244 of file log.py.
Referenced by produtil.log.JLogHandler.set_jlogfile().
postmsg()
def produtil.log.postmsg (message)
Sends the message to the jlogfile logging stream at level INFO.
This is identical to:
jlogger.info(message).
Parameters
message the message to log.
Definition at line 58 of file log.py.
set_jlogfile()
def produtil.log.set_jlogfile (filename)
Tells the jlogger to log to the specified file instead of the current jlogfile.
Also updates the jlogfile environment variable. The argument must be a filename.
Parameters
filename the new jlogfile
Definition at line 68 of file log.py.
stdout_is_stderr()
def produtil.log.stdout_is_stderr ()
Returns True if it can determine that stdout and stderr are the same file or terminal.
Returns False if it can determine they are not, or if the result is inconclusive.
Definition at line 135 of file log.py.
Referenced by produtil.log.configureLogging().
Variable Documentation
masterlogger
produtil.log.masterlogger = None
Master log stream for MPI-split jobs.
When a job is split via mpi_redirect, this logger will send data to the master log stream at lower log levels. This is configurable via calls to mpi_redirect()
Definition at line 39 of file log.py.