METplus: produtil.testing.parsetree Namespace Reference
produtil.testing.parsetree Namespace Reference
Parse tree classes for the produtil.testing suite.
Detailed Description
Parse tree classes for the produtil.testing suite.
The produtil.testing.parse.Parser class uses this module to construct a parse tree of the test suite. The tree consists of subclasses of BaseObject, connected to one another by scopes or operators. The Context class provides filename, line number, run mode, call stack, and other information which the BaseObject subclasses use for evaluation to literals.
Classes
class AtParse
Represents the "atparse" command, which parses files, converting @[varname] constructs into the variable's value.
class AutoDetectPlatform
Uses a list of Platform objects to detect the local platform.
class BaseObject
Base class of the parsetree hierarchy.
class BitCmp
Represents a bit-for-bit comparison between two files, as is done by the "cmp" shell command.
class Build
A Task that represents a build process (anything that constructs a program to be executed).
class Builtin
An abstract base class that represents a built-in operator, such as bit-wise comparison.
class Context
Represents the context from which a BaseObject is accessed.
class Copy
An operator that represents file copying.
class CopyDir
Represents a copy of a set of files from a source directory to the local directory.
class Criteria
Represents a list of output validation criteria.
class EmbedBash
Represents an embedded bash script.
class Environ
A read-only Scope that represents os.environ.
class Filters
Represents a list of input filters to run in sequence.
class Link
An operator that represents creation of a symbolic link.
class Md5Cmp
A class that will use store an MD5 sum of an executable for later validation.
class NccmpVars
Represents a bit-for-bit comparison between two files, as is done by the "cmp" shell command.
class Numeric
Represents a numeric literal.
class Platform
Represents a Task whose job is to determine the local platform.
class Rank
Represents a single MPI rank or group of MPI ranks with identical resource requirements and executable.
class Reference
Represents a reference to another variable.
class Scope
Represents a scope; the region of which a name binding can be evaluated.
class SpawnProcess
Represents a request to execute a process.
class String
Represents a string literal.
class Task
Represents a task that has a name, and can be executed as a batch job.
class Test
A Task that represents some Test to be run.
class TypelessObject
Represents an object that cannot be evauated in any context.
Functions
def fileless_context (scopes=None, filename=None, lineno=None, run_mode=None, logger=None, verbose=True)
Generates a Context object that is not connected to a Tokenizer.
def make_params (defscopes, kwargs)
Returns a new Scope with the given parameter list (function call definition)
def make_scope (defscopes, kwargs)
Creates a new scope with local variables defined.
def call_scope (scope, con, defscopes, kwargs)
Implements a function call.
def pack_ranks (nodesize, count)
Spreads count MPI ranks over the fewest possible nodes whose maximum PETs per node (ppn) is nodesize.
def expand_lists (iterable, max_depth=None)
Variables
null_value = BaseObject([])
A special constant that indicates a variable without a value.
Function Documentation
call_scope()
def produtil.testing.parsetree.call_scope (scope, con, defscopes, kwargs)
Implements a function call.
Parameters
scope the function to call
con Unused. This Context is passed to Scope.apply_parameters().
defscopes the call stack to the location at which the function call is made
kwargs arguments to the function call. These will override default values set in scope.
Returns
the function call, as a Scope
Definition at line 967 of file parsetree.py.
Referenced by produtil.testing.parsetree.Criteria.add_binary_operator(), and produtil.testing.parsetree.Filters.add_binary_operator().
fileless_context()
def produtil.testing.parsetree.fileless_context (scopes = None, filename = None, lineno = None, run_mode = None, logger = None, verbose = True)
Generates a Context object that is not connected to a Tokenizer.
This is to be used when resolving and evaluating objects from outside the workflow description.
Parameters
scopes Optional: the call stack, innermost scope first
filename Optional: a filename representative of the Context
lineno Optional: a line number representative of the Context
run_mode
Definition at line 102 of file parsetree.py.
Referenced by produtil.testing.parse.Parser.action_autodetect(), produtil.testing.parse.Parser.con(), produtil.testing.parsetree.Context.error(), produtil.testing.parsetree.Scope.resolve(), and produtil.testing.parsetree.Scope.use_from().
make_params()
def produtil.testing.parsetree.make_params (defscopes, kwargs)
Returns a new Scope with the given parameter list (function call definition)
Parameters
defscopes the new Scope's defining or calling location; a list of Scopes. This will be copied into the defscopes member variable.
kwargs (key,value) pairs mapping parameter name to the BaseObject value
Returns
a new Scope representing the given function definition
Definition at line 935 of file parsetree.py.
make_scope()
def produtil.testing.parsetree.make_scope (defscopes, kwargs)
Creates a new scope with local variables defined.
Parameters
defscopes the new Scope's defining or calling location; a list of Scopes. This will be copied into the defscopes member variable.
kwargs (key,value) pairs mapping variable name to the BaseObject value
Returns
a new Scope representing the given hash definition
Definition at line 949 of file parsetree.py.
Referenced by produtil.testing.parsetree.call_scope().
pack_ranks()
def produtil.testing.parsetree.pack_ranks (nodesize, count)
Spreads count MPI ranks over the fewest possible nodes whose maximum PETs per node (ppn) is nodesize.
Attempts to distribute the ranks per node as equally as possible. Any node will never have more than one or less than one rank than any other node.
Returns
a list of two-element lists. Each two element list contains a pair [number of nodes, PETs per node (ppn)] for nodes that have an identical number of PETs per node (ppn)
Parameters
nodesize the maximum number of PETS per node of any given compute node
count the number of MPI ranks
Definition at line 1730 of file parsetree.py.
Referenced by produtil.testing.parsetree.SpawnProcess.mpi_comm_size().
Variable Documentation
null_value
produtil.testing.parsetree.null_value = BaseObject([])
A special constant that indicates a variable without a value.
Warning
Terrible things will happen if you overwrite this.
Definition at line 284 of file parsetree.py.